### ISSUE TITLE
Add a constuctor with table name parameter

### ISSUE THREAD

**Issue by gonwan** [mybatis/generator#1000]
The generated meta class has only one constructor with default table name. It would be better to add the possibility to use a customized table name, which helps sql rewriting. See comments inline. 

```java
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", comments="Source Table: t_user")
    public static final class TUser extends AliasableSqlTable<TUser> {
        public final SqlColumn<Long> id = column("id", JDBCType.BIGINT);

        public final SqlColumn<String> username = column("username", JDBCType.VARCHAR);

        public final SqlColumn<String> password = column("password", JDBCType.VARCHAR);

        public TUser() {
            super("t_user", TUser::new);
        }

        /* !!! add this one !!! */
        public TUser(String tableName) {
            super(tableName, TUser::new);
        }

    }
```

**Comment by jeffgbutler** [comment]
@gonwan There is an enhancement in the upcoming release of MyBatis Dynamic SQL that might resolve this. `AliasableSqlTable` has a new method `withName(String tableName)` that will create a new instance with a different name. So in your example, you could create a new instance like this:

```java
TUser defaultUser = new TUser();
TUser anotherUser = defaultUser.withName("user2");
```

The pull request for this new feature is here: https://github.com/mybatis/mybatis-dynamic-sql/pull/572

This will be in MyBatis Dynamic SQL version 1.5. I will release it soon. Let me know if this will work for your use case.

**Comment by gonwan** [comment]
@jeffgbutler Thanks for quick reply. It seems to be just I want. I'll try it when released.

**Comment by jeffgbutler** [comment]
@gonwan Version 1.5.0 of MyBatis Dynamic SQL is released.

**Comment by gonwan** [comment]
Thank you! @jeffgbutler
