### ISSUE TITLE
Support to ignore GENERATED ALWAYS colums in insert / update statements

### ISSUE THREAD

**Issue by ilkomiliev** [mybatis/generator#104]
In our case the db (ibm db2) defines system time columns marked as GENERATED ALWAYS - these are not key columns. The generator generates them normally and the generated insert / update statements include these columns, causing db error to be thrown on insert / update, because the db does not permit the manipulation of these columns. On the other side, the values of these columns are needed in the application and they could not be ignored in general. What we need is some way to define these columns in the generator config as "special" in order to be able to handle the above situation - perhaps a property columnGeneratedAlways in the table element similar to columnOverride could be added for this purpose. More generic solution covering wider range of use cases will be to have something like includeInGeneratedInsert, includeInGeneratedUpdate, ... at column level. The only workaround currently is to use the insertSelective / updateSelective and manually set these columns to null prior to call them.

**Comment by jeffgbutler** [comment]
I've written some failing tests for this, now I'm thinking about a resolution.

I was hoping I could do something automatic, but I don't get enough information back from the JDBC driver to know if the column is GENERATED ALWAYS.  So I'll have to do something in configuration.

I'm leaning towards something like ```<columnOverride column="foo" isGeneratedAlways="true"/>``` and then ignoring that column in the inserts and updates.  This is basically your first option.

I could also do ```<columnOverride column="foo" includeInInsert="false" includeInUpdate="false"/>``` which is your second option.  But I can't think of a decent real world use case for this one and it is more verbose and potentially error prone.

What are your thoughts about the options?

**Comment by ilkomiliev** [comment]
I agree that the second option is indeed very "exotic" and probably only theoretical. The first option expresses very clear the intention of the columnOverride, so I agree that this is the better approach to implement it.
