### ISSUE TITLE
For snake case table names, is it possible to create a package?

### ISSUE THREAD

**Issue by naka-sho** [mybatis/generator#1041]
Is it possible to create a package for the snake case table names?

For example, let's say you have the following five tables:

```
stacked
stacked_user
stacked_book
stacked_book_task
stacked_book_purchase
```

Is it possible to have the following package configuration by running mbGenerator?

```
mapper
└── Stacked.java
└── stacked
         ├──StackedUser.java
         ├──StackedBook.java
         └── book
                  ├── StackedBookTask.java
                  └── StackedBookPurchase.java
```

The reason is that if there are many tables, the flat package structure will reduce the searchability.

**Comment by jeffgbutler** [comment]
You could write a plugin to do this. Basically, you would inspect the table name and change the record type. You could do this in the `initialized` method of a plugin. Here's an example of something similar that changes the name of the old example class from the deprecated runtimes: https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/main/java/org/mybatis/generator/plugins/RenameExampleClassPlugin.java
