### ISSUE TITLE
In the latest version, mariadb sets<property name="nullCatalogMeasCurrent" value="true"/>; Not working

### ISSUE THREAD

**Issue by mmm8955405** [mybatis/generator#1050]
`<jdbcConnection driverClass="org.mariadb.jdbc.Driver"  connectionURL="jdbc:mariadb://192.168.0.123:3306/archive" userId="root" password="test000000">
			<property name="nullCatalogMeansCurrent" value="true" />
		</jdbcConnection>`

https://mybatis.org/generator/usage/mysql.html

**Comment by mmm8955405** [comment]
it generator attempts to generate code for tables in the mariadb information schemas (sys, information_schema, performance_schema, etc.)

**Comment by jeffgbutler** [comment]
This appears to be a bug in the driver. I've submitted the following report to MariaDB: https://jira.mariadb.org/browse/CONJ-1103

**Comment by jeffgbutler** [comment]
@mmm8955405 In the meantime, I believe you could work around this by doing two things:

1. Set the database name in the `catalog` property of a table configuration
2. Add the property `ignoreQualifiersAtRuntime`

For example:

```xml
<table catalog="mydb" tableName="%">
  <property name="ignoreQualifiersAtRuntime" value="true" />
</table>
```

If you try this and it works then please let us know and we'll add this workaround to the documentation.

**Comment by mmm8955405** [comment]
> @mmm8955405 In the meantime, I believe you could work around this by doing two things:
> 
> 1. Set the database name in the `catalog` property of a table configuration
> 2. Add the property `ignoreQualifiersAtRuntime`
> 
> For example:
> 
> ```
> <table catalog="mydb" tableName="%">
>   <property name="ignoreQualifiersAtRuntime" value="true" />
> </table>
> ```
> 
> If you try this and it works then please let us know and we'll add this workaround to the documentation.

After I tested it, it really worked. Thank you.

**Comment by keeptrynjoy** [comment]
For those using the **MariaDB JDBC Driver 3.x or newer**, I found a more complete solution.

Instead of `nullCatalogMeansCurrent`, using the `nullDatabaseMeansCurrent` property resolved the issue perfectly, as it correctly handles metadata lookups for both catalogs and schemas.

This is the configuration that worked:

```xml
<jdbcConnection 
                driverClass="org.mariadb.jdbc.Driver"
                connectionURL="jdbc:mariadb://your.host:3306/YOUR_DB">
    <property name="nullDatabaseMeansCurrent" value="true" />
</jdbcConnection>
```
