### ISSUE TITLE
MyBatis3DynamicSql how generate xml file?

### ISSUE THREAD

**Issue by pondered** [mybatis/generator#1051]
i use `left join`， but i see example:
![t1](https://github.com/mybatis/mybatis-dynamic-sql/assets/10516978/77594c33-fc54-44c5-a9c9-0cd104fadeaf)
![t2](https://github.com/mybatis/mybatis-dynamic-sql/assets/10516978/b52f7ca0-4e48-41e2-b2fb-0084b1b65dbb)
![t2](https://github.com/mybatis/mybatis-dynamic-sql/assets/10516978/bbee7b38-f58e-485f-9cf8-594c5cd4f535)

return two table column, so i use new ResultMap, but  i see  `SimpleJoinResult` defined in xml

https://github.com/mybatis/mybatis-dynamic-sql/blob/8a7aad9ba9618df94b25864286b3ac2c7fe9cb0d/src/site/markdown/docs/select.md?plain=1#L146

but i use  MyBatis3DynamicSql 
<img width="460" alt="1" src="https://github.com/mybatis/mybatis-dynamic-sql/assets/10516978/1229080e-1a02-4ef8-a027-69aa6f35003f">

**Comment by jeffgbutler** [comment]
MyBatis Generator does not generate code for joins. The generated code for MyBatis3DynamicSql does not need any XML.

The examples you reference were hand coded.
