### ISSUE TITLE
How could I provide java.sql.Connection from my DataSource

### ISSUE THREAD

**Issue by viruscamp** [mybatis/generator#106]
How could I provide java.sql.Connection from dataSource in my app.
It can't iniatlize a Connection from driver and url from configration.

Could you make constructor of ConnectionFactory protected, and add a protected static setInstance method , so I can extend ConnectionFactory and replace the default .

**Comment by jeffgbutler** [comment]
I'll work on something to make it easier to supply your own connection.  I'm thinking of letting you plugin your own connection factory through a configuration item.  Something like

```xml
<context ...>
  ...
   <connectionFactory type="com.foo.ConnectionFactory"/>
  ...
</context>
```
