### ISSUE TITLE
Why doesn't it support generating controllers and services?

### ISSUE THREAD

**Issue by 3237704136** [mybatis/generator#1061]
Some simple business scenarios not only require POs and mappers, but also require the generation of controllers and services.Moreover, if the VO, POs, and DTO model strateqies are followed, there is also the need to generate VOs, POs, and DTOs. lt istroublesome to repeatedlv do highly coup ed thinas, sn't mab born precisely because it helps with deve opment? Why not trv togenerate more things? Are there any concerns?

**Comment by jeffgbutler** [comment]
I wrote an explanation about this years ago: https://mybatis.org/generator/philosophy.html

If you are recreating POs, VOs, DTOs, *Os, etc. that match the generated record classes it seems like a waste of time to me - just use the generated objects.

If instead you are mapping tables to a rich domain model, then you are thinking about relationships between tables and transactions. That is beyond the capabilities of the generator.

Nonetheless, if you think it is possible to generate such items for your use, then you could write a plugin to generate these additional items.
