### ISSUE TITLE
insert or insertSelective return 

### ISSUE THREAD

**Issue by CallMeXYZ** [mybatis/generator#107]
the return type of **insert** or **insertSelective** is **int**, what's it? When using generated keys, the id value is returned stored in the object parameter. I think the return type may cause some confusion~just a tip

**Comment by jeffgbutler** [comment]
This is the way MyBatis works.  inserts ,updates, and deletes always return int - the number of rows affected.

**Comment by CallMeXYZ** [comment]
sry just got it lol...
