### ISSUE TITLE
Can you give me a hint about automatic generation？

### ISSUE THREAD

**Issue by 3237704136** [mybatis/generator#1070]
Firstly, I'm sorry for not responding in a timely manner due to network issues.
------------------------------------------------------------------------------------------------------------------
I previously raised the issues of 1061，Ask why not generate templates and more models.
Jeffgbutler answered me，can read his previous blogs and list his viewpoints，I have gained something.
previous github link：https://github.com/mybatis/generator/issues/1061
------------------------------------------------------------------------------------------------------------------
However, I still have doubts。
Let me explain the usage scenarios of my program.
In the program, due to display reasons, the original data 0/1 is stored in the Po layer. However, in order to display the processed data yes/no to the user, the VO layer was born. Sometimes, the fields in the VO and Po layers are exactly the same, but most of the time, the fields in the VO layer are more than those in the Po layer. Additionally, the VO field may have fields that do not match the fields in the Po layer and require logical conversion.
The same goes for the dto 、query layer, which is a compromise made for display.
Because without detailed partitioning, users acquire too much redundant data. For example, if the user only needs to look at fields A and B, and the program also shows the C field to the user, this situation is not safe. Good program data should have permissions.
In addition, when initializing controllers and services, they are similar and can actually be extracted. Spring is doing this by opening up the Spring Data jpa and Spring Data Rest frameworks, defining a universal rest style basic plugin that can quickly develop a simple web.
However, I feel that it's not very flexible, so I used mybatis.
The usage of my project seems to be somewhere between the anemia model and the rich domain model.
I want the flexibility and simplicity of MyBatis, and I also want to enrich the basic transformation capabilities of models to cope with the transformation of different models. I need the concise and accurate presentation of different models, and I don't want to write too much code that focuses on models because it doesn't make much sense.
------------------------------------------------------------------------------------------------------------------
So, I need to use mybatis gen.
Mybatis gen simplifies the pressure on program po and jdbc layers，I also want mybatis gen to simplify the pressure on the vo, query, dto, service, and controller layers.
I am using mybatis dynamic SQL, and after a period of use, I have felt the charm of mybatis dynamic SQL
When I was using mybatis gen to generate code, I couldn't find an open interface to generate the mybatis dynamic SQL model.
Therefore, I would like to ask again in the hope of seeking help.
------------------------------------------------------------------------------------------------------------------

**Comment by jeffgbutler** [comment]
MyBatis Generator can generate code for MyBatis Dynamic SQL:

```xml
  <context id="dsql" targetRuntime="MyBatis3DynamicSql">
    ...
  </context>
```

As for your other application objects, you can write a plugin for MyBatis generator that can generate virtually any kind of code, but you would need to write that plugin. Here's an introductory page on writing plugins: https://mybatis.org/generator/reference/pluggingIn.html

**Comment by 3237704136** [comment]
> MyBatis Generator can generate code for MyBatis Dynamic SQL:
> 
> ```
>   <context id="dsql" targetRuntime="MyBatis3DynamicSql">
>     ...
>   </context>
> ```
> 
> As for your other application objects, you can write a plugin for MyBatis generator that can generate virtually any kind of code, but you would need to write that plugin. Here's an introductory page on writing plugins: https://mybatis.org/generator/reference/pluggingIn.html

ok，I'll take a look at the document first. I tried before and successfully generated the po and mapper in MyBatis3Dynamic Sql format, but I couldn't find the corresponding method to generate other modules

**Comment by 3237704136** [comment]
Turn off 1071, it seems like I can't turn it off. Next time I ask a question, I will throw out all the questions at once
https://github.com/mybatis/generator/issues/1071
--------------------------------------------------------------------------------------------------------------------------
Do you have plans in the future to allow MyBatis3Dynamic Sql to customize annotations？

**Comment by 3237704136** [comment]
> MyBatis Generator can generate code for MyBatis Dynamic SQL:
> 
> ```
>   <context id="dsql" targetRuntime="MyBatis3DynamicSql">
>     ...
>   </context>
> ```
> 
> As for your other application objects, you can write a plugin for MyBatis generator that can generate virtually any kind of code, but you would need to write that plugin. Here's an introductory page on writing plugins: https://mybatis.org/generator/reference/pluggingIn.html
---------------------------------------------------------------------------------------------------------------------
Doesn't it mean implementing the PluginAdapter interface and then overriding the method can be called? Why did I make an error during execution? Is there any operational error?
![image](https://github.com/mybatis/generator/assets/43770682/9bc2cd78-81e2-4fb2-ba66-033fe366e33b)
![image](https://github.com/mybatis/generator/assets/43770682/17878429-3a80-4464-8a92-b5683b632182)
![image](https://github.com/mybatis/generator/assets/43770682/49678ffb-03c6-4add-8a4b-43c43d7c5a7c)
![image](https://github.com/mybatis/generator/assets/43770682/49695612-723e-4324-8dfd-af3f199c2d8a)

**Comment by jeffgbutler** [comment]
I recommend that you read some example code - there are many plugins on GitHub. This repo has several examples: https://github.com/dcendents/mybatis-generator-plugins
