### ISSUE TITLE
Mybatis dynamic SQL cannot customize model annotations

### ISSUE THREAD

**Issue by 3237704136** [mybatis/generator#1071]
Mybatis dynamic SQL cannot customize model annotations，I think mybatis simple can customize the po layer model through Implements CommentGenerator，But Mybatis dynamic SQL can't do it.

**Comment by jeffgbutler** [comment]
I'm not sure what this means. Is this a duplicate question of #1070 ?

**Comment by 3237704136** [comment]
> I'm not sure what this means. Is this a duplicate question of #1070 ?

I don't think it's repetitive. One is how to generate other models, and the other is how to generate models using known methods. However, as a questioner, I follow the norms of community organizations. If there are any questions next time, I will merge them and ask them together. Sorry

**Comment by jeffgbutler** [comment]
The answer is the same for both questions - you can write a plugin to change virtually anything about the generated code, or to generate additional code.
