### ISSUE TITLE
If there are only two primary keys and both are selected, no generation will occur updateByPrimaryKeySelective

### ISSUE THREAD

**Issue by 3237704136** [mybatis/generator#1072]
if my table is 
![image](https://github.com/mybatis/generator/assets/43770682/e706ab00-b1c0-4efa-95ee-8530407f37d3)
The generator will not generate this function
![image](https://github.com/mybatis/generator/assets/43770682/f3be7b2f-146c-4650-975c-8883e313b0fe)
Is this a problem, or is the system itself designed like this

**Comment by jeffgbutler** [comment]
This is by design.
