### ISSUE TITLE
Feature request : add commentGenerator.dateFormat configurable item

### ISSUE THREAD

**Issue by viruscamp** [mybatis/generator#108]
If you have a configuration like this :
```xml
<commentGenerator>
  <property name="dateFormat" value="yyyy-MM-dd" />
</commentGenerator>
```
You will have generated comment like this :
@mbggenerated 2016-07-08
instead of 
@mbggenerated Fri Jul 08 09:23:37 CST 2016

**Comment by viruscamp** [comment]
This is my work:

[COMMENT_GENERATOR_DATE_FORMAT.diff.txt](https://github.com/mybatis/generator/files/353416/COMMENT_GENERATOR_DATE_FORMAT.diff.txt)

**Comment by jeffgbutler** [comment]
Thanks for your contribution!
