### ISSUE TITLE
Plugin API missing clientUpdateByPrimaryKeyMethodGenerated method for dynamic SQL runtime

### ISSUE THREAD

**Issue by octoape** [mybatis/generator#1116]
The plugin API is missing the **clientUpdateByPrimaryKeyMethodGenerated** method of the dynamic SQL runtime, and the callPlugins method of the UpdateByPrimaryKeyMethodGenerator class calls the clientUpdateByPrimaryKeyWithBLOBsMethodGenerated method.

**Comment by jeffgbutler** [comment]
I realize this is confusing.

There are two plugin methods "clientUpdateByPrimaryKeyWithoutBLOBsMethodGenerated" and "clientUpdateByPrimaryKeyWithBLOBsMethodGenerated". My thinking about it was that the dynamic SQL runtime does not make a distinction between "with BLOBs" and "without BLOBs", so the "with BLOBs" plugin method was accurate in all cases - the "without BLOBs" method would be inaccurate if the class actually had BLOB fields.

**Comment by octoape** [comment]
OK, understood.
Is it possible to add a clientUpdateByPrimaryKeyMethodGenerated method and call it in the UpdateByPrimaryKeyMethodGenerator class callPlugins method.
For compatibility clientUpdateByPrimaryKeyMethodGenerated calls clientUpdateByPrimaryKeyWithBLOBsMethodGenerated method by default.

**Comment by jeffgbutler** [comment]
This is a good idea.

**Comment by jeffgbutler** [comment]
Resolved via #1118
