### ISSUE TITLE
Mybatis Generator for Eclipse no longer accessible

### ISSUE THREAD

**Issue by hazendaz** [mybatis/generator#1129]
@jeffgbutler The site to download was shut down for open source some time ago.  @harawata was able to move his plugin over to github.  If possible could you two get together and see about getting this moved so its usable again?

**Comment by jeffgbutler** [comment]
I moved it to GitHub six months ago and updated the Eclipse marketplace listing. Here's the repo: https://github.com/jeffgbutler/mybatis-generator-update-site

**Comment by jeffgbutler** [comment]
This is the URL for the update site: https://jeffgbutler.github.io/mybatis-generator-update-site/

If you are using an old install of Eclipse/MBG then you might need to add this URL as an update site in your Eclipse configuration.

**Comment by hazendaz** [comment]
I tried marketplace but it would not complete.  Maybe its incorrect there.  But will try what you moved to.  Thanks for getting back so quickly!  Will let you now in a few.

**Comment by hazendaz** [comment]
Worked, got it!  Might be worth adding above to readme if not there.

**Comment by hazendaz** [comment]
assigned to myself, I can update the readme when I get a moment.
