### ISSUE TITLE
Expansion suggestions

### ISSUE THREAD

**Issue by shui888888** [mybatis/generator#1245]
Now supports the following writing style

criteria.andTypeEqualTo(questionQuery.getType());

How to implement the following or similar writing methods

criteria.andTypeEqualTo(questionQuery.getType() !=  null ,questionQuery.getType());

**Comment by jeffgbutler** [comment]
The legacy code runtime is deprecated and we won't be making any enhancements to it. If you will move to the new runtime based on MyBatis Dynamic SQL, then this function already exists.
