### ISSUE TITLE
about <table> schema attribute

### ISSUE THREAD

**Issue by ndsun** [mybatis/generator#1253]
I hava a question.When I use MBG to generator mapper.xml from a table, I should add schema attribute to avoid to scan other schemas. But I hope there is not schema prefix to the table name in the result xml file, how can I do? Fox example，my schema is RMS and table name is STUDENT, then in the result mapper file, the sql is like this : insert into RMS.STUDENT...，but I hope the sql is insert into STUDENT, without schema prefix.Hope your answer, thank you!

**Comment by jeffgbutler** [comment]
There's a property for this. See the documentation here: https://mybatis.org/generator/configreference/table.html

```xml
<table ... >
  <property name="ignoreQualifiersAtRuntime" value="true" />
</table>
```

**Comment by ndsun** [comment]
> There's a property for this. See the documentation here: https://mybatis.org/generator/configreference/table.html
> 
> ```
> <table ... >
>   <property name="ignoreQualifiersAtRuntime" value="true" />
> </table>
> ```

Got it, thank you very much！
