### ISSUE TITLE
Can I disable generation of getters and setters and have fields public?

### ISSUE THREAD

**Issue by korri123** [mybatis/generator#128]
I'm not using mybatis itself, rather just the generator. 

If I don't want the result to be Beans, is it possible to just have it generate a class with public fields?

**Comment by jeffgbutler** [comment]
Please use the mailing list for questions.

But yes, you can accomplish this by writing a simple plugin.

**Comment by korri123** [comment]
To anyone else looking for a solution, [here is a premade plugin](https://github.com/korri123/personal_files/blob/master/GeneratorPlugin.jar) I whipped out that does the job. 
I'm using the Maven plugin for generation and IntelliJ IDEA. It took me an hour to figure out how to configure this. 

This is the error I used to get: `[ERROR] Failed to execute goal org.mybatis.generator:mybatis-generator-maven-plugin:1.3.3:generate (default-cli) on project mbgplugin: Cannot instantiate object of type generators.extend.FieldMapperPlugin -> [Help 1]`

**Here are the steps:**
* In your generatorConfig.xml, inside `<context>` add 
```xml
<plugin type="generators.extend.FieldMapperPlugin"/>
```
* Executing a Maven command in IDEA: open the Maven tool window, click the icon with the m logo on top of a grey window to execute a command.
* Paste ```install:install-file -Dfile=/your-downloads-folder/GeneratorPlugin.jar -DgroupId=is.kormakur.generatorplugin -DartifactId=GeneratorPlugin -Dversion=1.0-SNAPSHOT -Dpackaging=jar -DgeneratePom=true```
* In your pom.xml, add a dependency INSIDE THE MAVEN PLUGIN, so it looks like this: 
```xml
<plugin>
         <groupId>org.mybatis.generator</groupId>
         <artifactId>mybatis-generator-maven-plugin</artifactId>
         <version>1.3.3</version>
         <dependencies>
              <dependency>
                  <groupId>is.kormakur.generatorplugin</groupId>
                  <artifactId>GeneratorPlugin</artifactId>
                  <version>1.0-SNAPSHOT</version>
              </dependency>
        </dependencies>
</plugin>
```
* Run your generate plugin!

**Extras**
* To stop the generator from camel casing your table names do this: 
```xml
<table tableName="account">
    <property name="useActualColumnNames" value="true"/>
</table>
```
* To remove the unnecessary comments (if you're not using mybatis itself) add
```xml
<commentGenerator>
    <property name="suppressAllComments" value="true"/>
</commentGenerator>
```
to `<context>` below the` <plugin>` tag.
