### ISSUE TITLE
IS_AUTOINCREMENT and IS_GENERATEDCOLUMN Not Supported by Older JDBC Drivers

### ISSUE THREAD

**Issue by dai19470** [mybatis/generator#136]
1.when i user tool to generator entity,dao,then throw a exception:
G:\java\mybatis>java -jar mybatis-generator-core-1.3.4.jar -configfile generator
Config.xml -overwrite
java.sql.SQLException: 列名无效
        at oracle.jdbc.driver.OracleStatement.getColumnIndex(OracleStatement.jav
a:3677)
        at oracle.jdbc.driver.OracleResultSetImpl.findColumn(OracleResultSetImpl
.java:2749)
        at oracle.jdbc.driver.OracleResultSet.getString(OracleResultSet.java:494
)
        at org.mybatis.generator.internal.db.DatabaseIntrospector.getColumns(Dat
abaseIntrospector.java:618)
        at org.mybatis.generator.internal.db.DatabaseIntrospector.introspectTabl
es(DatabaseIntrospector.java:221)
        at org.mybatis.generator.config.Context.introspectTables(Context.java:65
3)
        at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.
java:257)
        at org.mybatis.generator.api.MyBatisGenerator.generate(MyBatisGenerator.
java:189)
        at org.mybatis.generator.api.ShellRunner.main(ShellRunner.java:117)
2.the config file is:
<generatorConfiguration>
    <classPathEntry location="ojdbc.jar"/>
    <context id="DB2Tables" targetRuntime="MyBatis3">
        <commentGenerator>
            <property name="suppressDate" value="true"/>
           
            <property name="suppressAllComments" value="false"/>
        </commentGenerator>
      
        <jdbcConnection driverClass="oracle.jdbc.driver.OracleDriver" connectionURL="jdbc:oracle:thin:@192.168.70.95:1521:orcl1" userId="platform" password="platform">
        </jdbcConnection>
        <javaTypeResolver>
            <property name="forceBigDecimals" value="false"/>
        </javaTypeResolver>
         
        <javaModelGenerator targetPackage="com.joyintech.debt.dto" targetProject="src">
            <property name="enableSubPackages" value="true"/>
            <property name="trimStrings" value="true"/>
        </javaModelGenerator>
        
        <sqlMapGenerator targetPackage="com.joyintech.debt.map" targetProject="src">
            <property name="enableSubPackages" value="true"/>
        </sqlMapGenerator>
        
        <javaClientGenerator type="XMLMAPPER" targetPackage="com.joyintech.debt.mapper" targetProject="src">
            <property name="enableSubPackages" value="true"/>
        </javaClientGenerator>
        
        <table tableName="intd_project_approval" domainObjectName="IntdProjectApproval">
			
		</table>     
    </context>
</generatorConfiguration>

**Comment by jeffgbutler** [comment]
Can you post the SQL CREATE TABLE statement for intd_project_approval?  This error seems to be related to delimited column names so I'd like to see how the columns are defined.

**Comment by dai19470** [comment]
i also has a table named intd_project_approval,this is table :

**Comment by jeffgbutler** [comment]
I see the issue.  The generator is looking for some JSE 1.6 and JSE 1.7 features and the older Oracle drivers don't support that.  If you can upgrade your Oracle driver it might fix it.  I will also code around this issue for older drivers.
