### ISSUE TITLE
bug mysql driver version

### ISSUE THREAD

**Issue by sdcuike** [mybatis/generator#143]
mysql-connector-java-5.1.6,and 6.0.3 have errror: Column 'IS_GENERATEDCOLUMN' not found

when use  \mysql-connector-java-5.1.39.jar"  no error .

#  Use:MyBatis Generator Release 1.3.4 version

**Comment by jeffgbutler** [comment]
This is a duplicate of #136.  If you can use a JDBC driver that supports JDBC version 4.1 it should work.  I'll get a new release out hopefully over the weekend.
