### ISSUE TITLE
Why haven't "generate mybatis ibatis artifacts" in eclipse?

### ISSUE THREAD

**Issue by mowangxft** [mybatis/generator#144]
![image](https://cloud.githubusercontent.com/assets/16756450/18161201/93bdf8a4-7063-11e6-8b76-7be3d7f6b3d0.png)

**Comment by mowangxft** [comment]
I have installed the "org.mybatis.generator.eclipse.site-1.3.4.201608190045" in eclipse

**Comment by sdcuike** [comment]
FIle -> new ->MyBatis-> select  ## MyBatis Generator Configuration File , this generatre a configuration file ,you shoud config information, first

**Comment by mowangxft** [comment]
Yeah, I finished it.

**Comment by mowangxft** [comment]
But  no....

**Comment by jeffgbutler** [comment]
Please post questions to the mailing list if you are still having problems.
