### ISSUE TITLE
Column name in Java keywords auto-add suffix 

### ISSUE THREAD

**Issue by qiukeren** [mybatis/generator#156]
for example,when the column name has some keywords as "class","new",

the generated code does not work properly:

```
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dis_forum_activity.class
     *
     * @return the value of dis_forum_activity.class
     *
     * @mbggenerated Fri Sep 23 11:32:51 CST 2016
     */
    public String getClass() {
        return class;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dis_forum_activity.class
     *
     * @param class the value for dis_forum_activity.class
     *
     * @mbggenerated Fri Sep 23 11:32:51 CST 2016
     */
    public void setClass(String class) {
        this.class = class;
    }
```

what's more,

I am using 

```
                    <dependency>
                        <groupId>org.mybatis.generator</groupId>
                        <artifactId>mybatis-generator-maven-plugin</artifactId>
                        <version>1.3.4</version>
                    </dependency>
```

Is this a bug ? 
Or my version is too old?

**Comment by qiukeren** [comment]
```
        <table schema="discuz_bbs" tableName="dis_forum_activity">
            <columnOverride column="class" property="Classaa" />
        </table>
```

seems does not have the problem.


But if it is possible to have something more intelligence?
or a more convenient switcher as

```
<switch schema="discuz_bbs">
    <conflictKeyWords fix="addSuffix" property="_aa">
</switch>
```

**Comment by jeffgbutler** [comment]
Your workaround with the column override is correct.

I can add something that will check for Java reserved word and put a prefix on (like class to _class).  I already do this for SQL reserved words.

**Comment by clevertension** [comment]
@jeffgbutler , are you working on this issue? i think i can submit a PR for this feature

**Comment by jeffgbutler** [comment]
@clevertension I've taken a look at it and I don't think there's anything to do. The generator will already raise a warning when it encounters a reserved word and I think that is sufficient. It gets tricky in the case of "class" for example. We could generate a "_class" variable, but the generated getter "getClass" would still be a problem - and it's not clear what a reasonable default would be in that case.

WDYT?

**Comment by jeffgbutler** [comment]
Closing as "won't fix". Per the comment above, it is not clear what to do in cases like this, so we will rely on the warning and then force use of `<columnOverride>`
