### ISSUE TITLE
Can't support mysql jar after version of 1.6.0

### ISSUE THREAD

**Issue by heikehuan** [mybatis/generator#157]
The mysql jar version is 1.6.3 now.   And I wan't to create xml and interface mapper file with generator in my maven project, but I find that it can't support the mysql jar after version of 1.6.0 . So I must use 1.5.39 now, it worked correctly.  I don't know where is the problem, the generator maven plugin ? Or the generator itself?

This is my maven code : 
```
       <plugin>
                <groupId>org.mybatis.generator</groupId>
                <artifactId>mybatis-generator-maven-plugin</artifactId>
                <version>1.3.2</version>
                <configuration>
                    <configurationFile>${basedir}/src/main/resources/generator/generatorConfig.xml</configurationFile>
                    <overwrite>true</overwrite>
                    <verbose>true</verbose>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>5.1.39</version>
                    </dependency>
                </dependencies>
            </plugin>
```

**Comment by jeffgbutler** [comment]
Is there any error message or warning?  What are the symptoms?

You also might try using the latest version of the generator (1.3.5).

**Comment by heikehuan** [comment]
I test  it moment ago, the latest version of the generator (1.3.5) work well. But it has a new problem, it create all databases' all tables' xml file and interface file. It likes can't find correct database. When I downgrade the mysql jar version to 5.1.39, this problem is disappeared.

the datasource.properties file

    #the dabase connet infomation
    jdbc.driverClass = com.mysql.cj.jdbc.Driver
    jdbc.url = jdbc:mysql://localhost:3306/huan_blog?characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    jdbc.user = root
    jdbc.password = root

the generatorConfig.xml file

    <?xml version="1.0" encoding="UTF-8"?>
    
    <!DOCTYPE generatorConfiguration
    PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
    "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">
    
    <generatorConfiguration>
    <properties resource="generator/datasource.properties"/>
    
    <context id="Mysql" targetRuntime="MyBatis3Simple" defaultModelType="flat">
    <property name="beginningDelimiter" value="`"/>
    <property name="endingDelimiter" value="`"/>
    
    <jdbcConnection driverClass="${jdbc.driverClass}"
    connectionURL="${jdbc.url}"
    userId="${jdbc.user}"
    password="${jdbc.password}">
    </jdbcConnection>
    
    <javaModelGenerator targetPackage="${targetModelPackage}" targetProject="${targetJavaProject}"/>
    
    <sqlMapGenerator targetPackage="${targetXMLPackage}" targetProject="${targetResourcesProject}"/>
    
    <javaClientGenerator targetPackage="${targetMapperPackage}" targetProject="${targetJavaProject}"
     type="XMLMAPPER"/>
    
    <table tableName="%">
    <generatedKey column="id" sqlStatement="Mysql" identity="true"/>
    </table>
    </context>
    </generatorConfiguration>

**Comment by jeffgbutler** [comment]
I don't understand.

Did the Java and XML get generated?  If so, then what issue are you having with the generator?

**Comment by jeffgbutler** [comment]
No reply
