### ISSUE TITLE
Can we support create ResultMap Xml Element use result map rather than constructor map when set constructorBased as true

### ISSUE THREAD

**Issue by oleaster** [mybatis/generator#163]
Can we support create ResultMap Xml Element use result map rather than constructor map when set constructorBased as true. If use  constructor map, we need set all consturctor parameters, but sometimes i only want set part parameters for some sql statment.

**Comment by oleaster** [comment]
I  want there are consturctor method in java, meanwhile use result map instant of constructor map in ResultMap Xml Element.

**Comment by jeffgbutler** [comment]
Can you post an example of what you want generated?  I'm not understanding your question.

**Comment by oleaster** [comment]
Thanks a lot of your reply. I found a good way to resolve my problem.
