### ISSUE TITLE
Generator sqlMapGenerator and  javaClientGenerator into custom subpackages

### ISSUE THREAD

**Issue by Mylog** [mybatis/generator#165]
for example, when I set domainObjectName="test.Food" in <table> element. The corresponding sqlMap and javaClient will be generated into a subpackage too. 
 sqlMap  have a element targetPackage="com.xx.xml"
 sqlMap  will be generated into package  com.xx.xml.test
 javaClient have a element targetPackage="com.xx.map"
 javaClient will be generated into package  com.xx.map.test

**Comment by jeffgbutler** [comment]
This is by design - it was intended to give you a bit more control over the package name if you only wanted to change it for a few tables.  You could create a new ```<context>``` for this table and have total control over the packages, or you could write a plugin.  Configuring a new ```<context>``` is easier.

**Comment by Mylog** [comment]
The way you suggested is clearly understandable. Thanks a lot of your reply
