### ISSUE TITLE
Run As.. should include current project in classpath

### ISSUE THREAD

**Issue by leonbloy** [mybatis/generator#167]
In MyBatis generator 1.3.5 the menu option is deprecated in favor of "Run As...".

For me, the menu option works and "Run As..." gives an error (resource does not exist)

After some investigation, I found out that the default running configuration that is created does NOT include the current project in the classpath. After I manually added it, it worked.
I think that this goes against an Eclipse user expects. When we run some Java class (or practically anything) in the IDE, we expect that the "current" project is included in the classpath.

**Comment by leonbloy** [comment]
Also, the "Run as" command is way too silent, it should report something at console or popup.

**Comment by jeffgbutler** [comment]
I'm just trying to understand the use case and how to test - do you have a custom generator plugin in your project?

**Comment by leonbloy** [comment]
I was using an old version of  MyBatis generator, i've just installed (over a new fresh Eclipse Neon, Java 8 32 bits, windows 7) version 1.3.5 

In (say) my project  `Proj1` 
`src/mybatisgen/mybatisgen.properties`
`src/mybatisgen/mytables/cfg_table1.xml`

Where `cfg_table1.xml` has 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration
  PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
  "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">
<generatorConfiguration>
	<properties resource="mybatisgen/mybatisgen.properties" />
	...
</generatorConfiguration>
```

If I run this with the menu shortcut, it works. If I run it with "Run As -> Run MyBatisGenerator" it doesn't, the resource `mybatisgen/mybatisgen.properties` is not found because the classpath of the 
project is not included in the runConfiguration.
I need to go to Run -> Run Configurations... look for the corresponding MyBatis generator config and in the Classpath tab add an entry for the current project.

**Comment by jeffgbutler** [comment]
Got it.  

I just looked and I see that the JUnit runner adds the current project by default in the classpath tab of a new launch configuration.  That way it can be removed if for some reason it shouldn't be there.  I will follow that same convention.

Thanks for reporting this!

**Comment by leonbloy** [comment]
You're welcome. 
I'm not sure if this counts as a bug, but as I commented before, I fell the "Run as ..." command is too silent, the user has no feedback that it has worked. It would be nice if a message is printed to the console or something.
