### ISSUE TITLE
Column First letter  can't  Upper!!

### ISSUE THREAD

**Issue by hppryz** [mybatis/generator#170]
DB column:
CREATE TABLE `NewTable` (
`id`  int(11) NOT NULL AUTO_INCREMENT ,
`AA`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`BB`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`CC_DD`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`aa2`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`ABBB`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
`Accc`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,
PRIMARY KEY (`id`)
)
ENGINE=InnoDB
DEFAULT CHARACTER SET=utf8 COLLATE=utf8_general_ci
AUTO_INCREMENT=1
ROW_FORMAT=COMPACT
;

generatorConfig.xml:

......
<table schema="test" tableName="test"   enableCountByExample="false" enableUpdateByExample="false" enableDeleteByExample="false" enableSelectByExample="false" selectByExampleQueryId="false"> 
		<property name="useActualColumnNames" value="true"/>
	</table>
	 	    	
......

entity I got :

public class Test {
    private Integer id;

    private String AA;

    private String BB;

    private String CC_DD;

    private String aa2;

    private String ABBB;

    private String  accc;

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAA() {
        return AA;
    }

look at the last column ::!!!!!

 private String  accc;

the column name  is : 
`Accc`  varchar(255) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL ,

WTF!!

**Comment by jeffgbutler** [comment]
This is the generator trying to conform to the JavaBeans spec.  Section 8.8 of the spec implies that properties that begin with a single upper case letter are invalid.   IIRC MyBatis has some trouble with properties starting with a single uppercase letter also.

**Comment by hppryz** [comment]
@jeffgbutler  so , what can I do  with  this  ? just not use uppercase letter at  begin of a columnname ?

**Comment by jeffgbutler** [comment]
MBG should have generated getAccc() and setAccc() methods for you which will work.  So the only thing "wrong" is that the private field has a different case that you might otherwise expect.  This doesn't seem like a problem to me.
