### ISSUE TITLE
When to support mysql5.7+ json type?

### ISSUE THREAD

**Issue by lafengnan** [mybatis/generator#181]
Since MySQL5.7.8 native json type was introduced, when will to support it ?

**Comment by jeffgbutler** [comment]
What kind of support are you wanting?  If the MySql JDBC driver supports this data type, then MyBatis and the generator can probably work with it.

**Comment by lafengnan** [comment]
I checked the source of connector/j, MySQL json was translated into to java CHAR, if user want to use native json functions, should have to handle the format of string to store in MySQL. For example, if i want to store an object with toString() value: {"name": "mysql"}, the value is incorrect in MySQL and consequently could not use native json functions provided by MySQL.

**Comment by jeffgbutler** [comment]
I'm don't understand why you think this is an issue with MyBatis and/or the Generator.  Can you provide a failing test case?  If you can show us something that works with JDBC, but fails with MyBatis then we can investigate.

**Comment by lafengnan** [comment]
Thanks @jeffgbutler I was wondering how to use MySQL's native json functions with MBG, but in fact MBG actually could not know what queries user will do. hmmm....it does work with well serialized string(String should be json formatted). I will close this issue.
