### ISSUE TITLE
@Mapper exist in 1.3.5?

### ISSUE THREAD

**Issue by songmengmeng** [mybatis/generator#184]
Will be automatically generated in the annotation pattern？

**Comment by jeffgbutler** [comment]
Not currently.  I'll add a little plugin to do that.

**Comment by songmengmeng** [comment]
Fine,thanks.

**Comment by blackfrancis** [comment]
to anyone waiting for the 1.3.6 release; here is the Plugin code in the mean-time ;)

`	@Override
	public boolean clientGenerated(org.mybatis.generator.api.dom.java.Interface interfaze, TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
		
		interfaze.addAnnotation("@org.apache.ibatis.annotations.Mapper");
		
		boolean isGenerated =  super.clientGenerated(interfaze,  topLevelClass,  introspectedTable);
		return isGenerated;
	};`

**Comment by shx1545** [comment]
This is a bad practice,there is no need to annotate the project integrated with springboot, instead, there is a warning.
![image](https://user-images.githubusercontent.com/29303050/38986736-dcca709c-43ff-11e8-9b56-730b6f2a3fe5.png)
