### ISSUE TITLE
rootClass cannot be loaded

### ISSUE THREAD

**Issue by libra1010** [mybatis/generator#187]
configure set    <property name="rootClass" value="com.domain.BaseDomain"/>

BaseDomain.java
package com.domain;

public class BaseDomain {
    
    private Integer id;

  
   
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.ID
     *
     * @return the value of user.ID
     *
     * @mbg.generated Wed Jan 11 12:26:45 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.ID
     *
     * @param id the value for user.ID
     *
     * @mbg.generated Wed Jan 11 12:26:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }
}

Compile to base.jar

use
java -cp base.jar;mybatis-generator-core-1.3.5.jar org.mybatis.generator.api.ShellRunner -configfile configure.xml  -overwrite

BUT
Column username, specified for override in table user, does not exist in the table.
Root class cn.libra.domain.BaseDomain cannot be loaded, checking for member overrides is disabled for this class
WHY?

**Comment by jeffgbutler** [comment]
From what you posted, the base class is com.domain.BaseDomain - not cn.libra.domain.BaseDomain.

**Comment by jeffgbutler** [comment]
No response
