### ISSUE TITLE
Running MyBatis Generator With Maven In IDEA Failed, <properties> resource jdbc.properties does not exist

### ISSUE THREAD

**Issue by LewisCast** [mybatis/generator#188]
properties in generatorConfig.xml : `<properties resource="jdbc.properties"/>`

filepath : in my workspace, src/main/resoureces/jdbc.properties

plugin config:`<plugin>
                <groupId>org.mybatis.generator</groupId>
                <artifactId>mybatis-generator-maven-plugin</artifactId>
                <version>1.3.5</version>
                <configuration>
                    <verbose>true</verbose>
                    <overwrite>true</overwrite>
                </configuration>
            </plugin>`

error message in console:
`[ERROR] Failed to execute goal org.mybatis.generator:mybatis-generator-maven-plugin:1.3.5:generate (default-cli) on project JavaUtils: <properties> resource jdbc.properties does not exist -> [Help 1]`

I find that it worked when properties path like "src/main/java/jdbc.properties" , but it is unfriendly in maven.

**Comment by jeffgbutler** [comment]
No answer

**Comment by Ledar** [comment]
I add the properties file to POM as resource, and it works
`<resources>
	<resource>
		<directory>src/main/resources</directory>
		<includes>
			<include>**/*.properties</include>
		</includes>
	</resource>
</resources>`

**Comment by firefoxer1992** [comment]
Adding the properties file to POM as resource  as above  really helps me..
And in the jdbc.properties, if  there are some spaces in the end of the line, will also cause the problem.
