### ISSUE TITLE
something strange with	mysql-connector-java 6.0

### ISSUE THREAD

**Issue by CharlotteBao** [mybatis/generator#192]
I use mysql-connector-java 6.0.5 in my project, and found that, there is no any function like xxxByPrimaryKey im my mapper after run generator.
And changed to mysql-connector-java 5.1.x and re-run the task, these functions appear. 
I have no doubt if it is my bad or this a mybatis bug or mysql bug

**Comment by jeffgbutler** [comment]
This sounds like a MySql connector-j bug - my guess is something is wrong with the "getPrimaryKeys" method in their implementation of java.sql.DatabaseMetaData.

**Comment by CharlotteBao** [comment]
sure, i will ask them for some help.
