### ISSUE TITLE
org.apache.ibatis.binding.BindingException: Parameter 'orderByClause' not found.

### ISSUE THREAD

**Issue by zhengzhiren** [mybatis/generator#195]
```java
XxxExample example = new XxxExample();
example.createCriteria().andXxEqualTo(123);
example.setOrderByClause("id asc");
xxxMapper.selectByExample(example);
```
When I run the above code, I got this error:
> org.apache.ibatis.binding.BindingException: Parameter 'orderByClause' not found.

Then I digged into the generated xml code:

```xml
  <select id="selectByExample" parameterType="com.abc.XxxExample" resultMap="BaseResultMap">
    select
    <if test="example.distinct">
      distinct
    </if>
    <include refid="Base_Column_List" />
    from xxx
    <if test="example != null">
      <include refid="Example_Where_Clause_With_Alias" />
    </if>
    <if test="example.orderByClause != null">
      order by ${orderByClause}
    </if>
  </select>
```

I manually modified the **${orderByClause}** to **${example.orderByClause}** and the code worked.
Is this a bug?

mybatis 3.4.2
mybatis-spring 1.3.1
mybatis-generator-maven-plugin 1.3.5

**Comment by jeffgbutler** [comment]
This code isn't what comes out of the generator - so it has been modified by someone or some plugin.  The generator doesn't build "Example_Where_Clause_With_Alias" or "example.distinct".

**Comment by zhengzhiren** [comment]
Yes, the code is modified by another plugin. Thanks!

**Comment by jeffgbutler** [comment]
OK.  I assume this is a mistake the other plugin made.
