### ISSUE TITLE
Can we just have table and column remarks from db without auto-generated comments?

### ISSUE THREAD

**Issue by hollyshi** [mybatis/generator#197]
When I try to add table and column remarks from db table, I have to do the following,
`suppressAllComments = false`
`addRemarkComments = true`

However, when suppressAllComments is set to false, there will be plenty of comments like "This method was generated by MyBatis Generator."...

Any chance that I can just have those table and column remarks without the auto-generated comments?

**Comment by jeffgbutler** [comment]
CommentGenerator is a configurable interface. You can write your own  implementation and format the comments any way you want.

**Comment by hollyshi** [comment]
@jeffgbutler, thanks for the reply. I'll try it.

Good day.
