### ISSUE TITLE
How to sort importTypes in commentGenerator

### ISSUE THREAD

**Issue by litttlefisher** [mybatis/generator#198]
<img width="741" alt="qq20170301-100104 2x" src="https://cloud.githubusercontent.com/assets/19563352/23442833/08feb1b8-fe66-11e6-9dcc-a7c2566c1999.png">

Because of using checkstyle, I need to sort Imports ,please tell me how to sort it in commentGenerator.
ths!

**Comment by jeffgbutler** [comment]
I'm not sure what you are asking, or what this has to do with the commentGenerator.

Please use the mailing list for further questions.

**Comment by litttlefisher** [comment]
in TopLevelClass.java line 129
you sort the importedTypes by default sort type
I hope you can priovide a interface to custom sort type.
<img width="1141" alt="qq20170305-071918 2x" src="https://cloud.githubusercontent.com/assets/19563352/23583064/6d4aa03a-0174-11e7-8bae-54fa5fe6d6ce.png">
I hope I can have my custom method to replace this codes.

I am a chinese coder, please ignore my poor English.

thx!
