### ISSUE TITLE
Using driver for postgresql 9.4, generator not generating classes for views

### ISSUE THREAD

**Issue by rdcockrell** [mybatis/generator#200]
When running the generator for a postgresql 9.4 database, it correctly generates classes for tables but does not do anything for views.  Even when specifically defined in a table section as a "tableName", it acts as if it does not exist.

**Comment by jeffgbutler** [comment]
This is probably an issue in the JDBC driver.  I found this PR that might be related:  https://github.com/pgjdbc/pgjdbc/pull/405.

So my first suggestion is to try a newer driver to see if the issue is resolved.

**Comment by jeffgbutler** [comment]
No response.
