### ISSUE TITLE
How to sort importTypes?

### ISSUE THREAD

**Issue by litttlefisher** [mybatis/generator#201]
in TopLevelClass.java line 129
you sort the importedTypes by default sort type
I hope you can priovide a interface to custom sort type.
<img width="1141" alt="qq20170305-071918 2x" src="https://cloud.githubusercontent.com/assets/19563352/23583064/6d4aa03a-0174-11e7-8bae-54fa5fe6d6ce.png">
I hope I can have my custom method to replace this codes.

I am a chinese coder, please ignore my poor English.
In addition, I don't know how to mail you, can you provide a mail address ?
thx!

**Comment by jeffgbutler** [comment]
You would need to write your own JavaFormatter.  Write a class that implements `org.mybatis.generator.api.JavaFormatter` and configure it in your `<context>`.   It is not a trivial task, but you could copy the code from TopLevelClass and modify it as you want.

Please see this page for instructions on how to access the mailing list:

http://www.mybatis.org/generator/index.html
