### ISSUE TITLE
if it is possible Criteria andXxx Method don't check null?

### ISSUE THREAD

**Issue by ricardo0624** [mybatis/generator#204]
Hello, mybatis generator is really great.I like it very much,and it helps me a lot.
but, when I use it in query scene,andXxx method checks null.
if Criteria check null, in query scene,the query param is not required ,so the code is that
``
                String x= vo.getX();
		if (StringUtils.isNotBlank(x)) {
			criteria.andXLike(x+ '$');
		}
		String y= vo.getY();
		if (StringUtils.isNotBlank(y)) {
			criteria.andYLike(y+ '%');
		}
		Integer z= vo.getZ();
		if (null != z) {
			criteria.andZEqualTo(z);
		}
`
so I wonder if it is possible for generator don't check null?
thanks  a lot for your works.

**Comment by jeffgbutler** [comment]
Are you asking if it is possible for the generated code to ignore criteria if the value is null and/or blank?  As you know, then generated code doesn't work that way.  But you could add your own criteria methods to do this.  Just override the andXXX methods in the Example.Criteria class.

**Comment by ricardo0624** [comment]
@jeffgbutler thanks you.

> then generated code doesn't work that way

1. yeah,I mean that
2. why doesn't work that way?
3. It is hard to override andXXX methods,If I choose to override,rather than I check null

actually,if if ignore criteria if the value is null and/or blank,maybe more convenient for developers.
Thanks a lot for your work

**Comment by TroyTae** [comment]
@ricardo0624 
Now MBG makes a exception when use null in parameter.
So I write same code as you like this:
```
public List<Test> selectList(Integer key1, Integer key2, String code) {
        TestExample example = new TestExample ();
        TestExample.Criteria criteria = example.createCriteria();

        criteria.andCompanySnEqualTo(key1);

        if(key2 != null) criteria.andMemberSnEqualTo(key2);
       
        if(code!= null) criteria.andKindCodeEqualTo(code);

        return mapper.selectByExample(example);
    }
```

I think check null is not bad idea, but blank is may impossible.
There is case that search blank data.

**Comment by JYDxl** [comment]
@ricardo0624 
add a custom PluginAdapter GeneratorConfig like this:
package org.github.spring.mybatis.generator;

import java.util.List;

import org.mybatis.generator.api.IntrospectedTable;
import org.mybatis.generator.api.PluginAdapter;
import org.mybatis.generator.api.dom.java.InnerClass;
import org.mybatis.generator.api.dom.java.Method;
import org.mybatis.generator.api.dom.java.TopLevelClass;

public class MethodParamNonNullOpsPlugin extends PluginAdapter {
    @Override
    public boolean modelExampleClassGenerated(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        InnerClass criteria = this.getCriteria(topLevelClass);
        InnerClass generatedCriteria = this.getGeneratedCriteria(topLevelClass);
        if (generatedCriteria == null) return true;
        if (criteria == null) return true;

        String methodBetween = "Between";
        String methodNull = "Null";
        String methodIn = "In";
        String methodCriteria = "Criteria";
        String methodValid = "Valid";
        String methodCriterion = "Criterion";

        for (Method method : generatedCriteria.getMethods()) {
            String name = method.getName();
            if (name.endsWith(methodBetween)) continue;
            if (name.endsWith(methodNull)) continue;
            if (name.endsWith(methodIn)) continue;
            if (name.endsWith(methodCriteria)) continue;
            if (name.endsWith(methodValid)) continue;
            if (name.endsWith(methodCriterion)) continue;

            String origin = method.getBodyLines().get(0);
            origin = "if(value != null) ".concat(origin);
            method.getBodyLines().set(0, origin);
        }

        return true;
    }

    @Override
    public boolean validate(List<String> warnings) {
        return warnings.isEmpty();
    }

    InnerClass getCriteria(TopLevelClass topLevelClass) {
        InnerClass criteria = null;
        for (InnerClass innerClass : topLevelClass.getInnerClasses()) {
            if ("Criteria".equals(innerClass.getType().getShortName())) {
                criteria = innerClass;
                break;
            }
        }
        return criteria;
    }

    InnerClass getGeneratedCriteria(TopLevelClass topLevelClass) {
        InnerClass generatedCriteria = null;
        for (InnerClass innerClass : topLevelClass.getInnerClasses()) {
            if ("GeneratedCriteria".equals(innerClass.getType().getShortName())) {
                generatedCriteria = innerClass;
                break;
            }
        }
        return generatedCriteria;
    }
}

**Comment by jeffgbutler** [comment]
I'm going to close this as I don't plan to make changes in the legacy code generators.  There is a general solution for this in MyBatis Dynamic SQL version 1.0.1 with optional conditionals.
