### ISSUE TITLE
oracle set remark my advise in org.mybatis.generator.internal.db.DatabaseIntrospector

### ISSUE THREAD

**Issue by aimatwinning** [mybatis/generator#210]
in the while (rs.next()) :

`if ("Oracle".equals(databaseMetaData.getDatabaseProductName())) {
                String sql = "select COMMENTS from user_col_comments where TABLE_NAME=? AND COLUMN_NAME=?";
                PreparedStatement pstmt = databaseMetaData.getConnection().prepareStatement(sql);

                pstmt.setString(1, tc.getTableName());
                pstmt.setString(2, rs.getString("COLUMN_NAME"));

                ResultSet rss = pstmt.executeQuery();
                if (rss.next()) {
                    introspectedColumn.setRemarks(rss.getString("COMMENTS"));
                }
            }else {
                introspectedColumn.setRemarks(rs.getString("REMARKS"));
            }`

is that all right?

**Comment by jeffgbutler** [comment]
Please ask questions on the mailing list.

**Comment by aimatwinning** [comment]
nope, if you do not, I will rebuild a jar for myself.




发自网易邮箱大师
On 03/26/2017 21:56, Jeff Butler wrote:

Closed #210.
