### ISSUE TITLE
mapper namespace of xml when javaClientGenerator configed

### ISSUE THREAD

**Issue by CallMeXYZ** [mybatis/generator#211]
As the doc says, the  `javaClientGenerator` config is an optional choice. 
If so, can we customize the `namespace` of `<mapper>` tag in the xml? Now the value is `targetPackage`+tableName+'Mapper'.

**Comment by jeffgbutler** [comment]
Please ask future questions on the mailing list.

In MyBatis the namespace in the XML must match the name of the interface.  You can change the values using the `mapperName` attribute on a `<table>` configuration.  See this page for information:

http://www.mybatis.org/generator/configreference/table.html
