### ISSUE TITLE
Error getting autogenerated key from INSERT

### ISSUE THREAD

**Issue by mesier** [mybatis/generator#213]
Hello!
I met the same problem like discribe here: http://mybatis-user.963551.n3.nabble.com/missing-keyColumn-value-in-Options-annotation-td4026292.html 
Briefly - I generate a POJOs and Mappers, but option "keyColumn" didn't set (absent ever). Then I got an error 
_"org.mybatis.spring.MyBatisSystemException: nested exception is org.apache.ibatis.executor.ExecutorException: Error getting generated key or setting result to parameter object. Cause: org.apache.ibatis.executor.result.ResultMapException: Error attempting to get column #1 from result set.  Cause: java.sql.SQLException: Запрошено недопустимое преобразование"_
Could anybody explain is a parameter "keyColumn" really need for getting autogenerated keys, as mentioned in the issue above (follow the link) and how to set this parameter from generator config file? I tried many options but nothing help...
I use:
Oracle 12.1.0.1;  
MybatisGenerator 1.3.5;  
MyBatis 3.4.1 and 
MybatisSpring 1.3.0

**Comment by TroyTae** [comment]
http://www.mybatis.org/generator/configreference/generatedKey.html

Did you add "generatedKey" in your "table" element?
If you already added, set attrubute "sqlStatement" like this:
```
<table tableName="table" schema="sample">
    <generatedKey column="id" sqlStatement="select sys_guid() from dual" />
</table>
```

**Comment by mesier** [comment]
Sure, but without any "select" since my entities should generate also from PostgreSQL by choosing different Maven profile. 
        <table tableName="t_%">
            <property name="useActualColumnNames" value="false"/>
            <generatedKey column="ID" sqlStatement="JDBC" identity="true" />
        </table>
This options is ok for PostgreSQL but not for Oracle and I would like to fix it..

**Comment by TroyTae** [comment]
Hmm that is strange.
I have a same problem like you.
But I fixed it using sqlStatement="select sys_guid() from dual"...

**Comment by TroyTae** [comment]
@mesier 
https://github.com/cxjava/mybatis-generator-core/blob/master/src/test/resources/tsm_oracle.xml

How about seeing this?
```
<table tableName="USER_INFO" schema="tsm">
	<property name="ignoreQualifiersAtRuntime" value="true" />
	<property name="runtimeTableName" value="USER_INFO" />
	<generatedKey  column="ID" sqlStatement="select SEQ_USER_INFO.NEXTVAL from dual" />
</table>
```

**Comment by jeffgbutler** [comment]
I'm going to assume this is resolved.  If you have further questions, please use the mailing list.
