### ISSUE TITLE
How to get the mysql  table index info and judge the field Whether it is unique key?

### ISSUE THREAD

**Issue by AnonymMan** [mybatis/generator#217]
For example,following is create table sql, 

**CREATE TABLE `xxxxx` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'id',
  `xxxx_no` varchar(64) NOT NULL COMMENT 'xxx_no',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_xxxx_no` (`xxxx_no`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='xxxxxxx';**

Can i get index info about idx_xxxx_no by generator api? Thanks

**Comment by jeffgbutler** [comment]
The generator does not retrieve index information from the database, so it won't know about unique constraints.

What would you want the generator to do with that information?

**Comment by AnonymMan** [comment]
@jeffgbutler Thanks a lot for your answer,I want to get the index information to generate batch custom sql with many table,like **select * from xxxxx where (unique key)=xxxx**. Is there some way can implement it? Thanks

**Comment by jeffgbutler** [comment]
OK I understand what you're trying to do.  But as I said, then generator doesn't retrieve index information from the database currently.

You could write a plugin that would add selectByXXXX type of methods to the generated code (and set some property in the configuration stating which column is considered unique).  I think it would be easiest to reuse the selectByExample code generating something like this:

```java
public Foo selectbyXXXX(String xxxx) {
  FooExample example = new FooExample();
  example.createCriteria().andXXXXEqualTo(xxxx);
  List<Foo> records = selectByExample(example);
  return records.size() == 0 ? null : records.get(0);
}
```

**Comment by AnonymMan** [comment]
@jeffgbutler  Thanks for your answer,i am already implement it by this way.
