### ISSUE TITLE
Does it support more than two federated query tables?

### ISSUE THREAD

**Issue by TGK-sain** [mybatis/generator#218]
I would like to know if it supports more than two federated query tables . like it :
`select a.id as id,
			a.create_date as createDate,a.user_id as userId,b.nick_name as nickName,
			c.name as modifyUserName,
			a.remark as remark 
		from 
			io a 
                join
                        user b on a.user_id = b.id 
		left join 
                       staff c on a.modify_user_id = c.id 
		left join 
                       user_bank d on a.user_id=d.user_id
		where 
			a.status = 11
		and 
                        a.user_id= #{userId}
	`

**Comment by jeffgbutler** [comment]
No it doesn't.

Please ask questions on the user mailing list.
