### ISSUE TITLE
about enhance mybatis-generator code

### ISSUE THREAD

**Issue by zhizhi555555** [mybatis/generator#221]
Hi, I no see any junit code after the mybatis code have generated, so i think is that have time to enhance the code about generate this project's junit code,thanks !

**Comment by zhizhi555555** [comment]
which i mean is about generate the crud code , could you also provide the junit test about the crud code?

**Comment by jeffgbutler** [comment]
I think you are asking for the generator to also generate unit tests.  I think it is dangerous to generate unit tests against a live database.  My favorite strategy is to use something like HSQLDB to build an in memory DB and run tests against that.  But that's probably more than could reasonably be generated.

One other way to think about it is that this is generated code and you can trust the generator.  There are hundreds of unit tests in the generator build that test the generated code.  Not to say that there aren't still some bugs remaining - there probably are.  But it would be better to write generator tests to expose those bugs, and then fix them for everyone.

You could write a plugin to generate unit test shell method in your environment, but most IDEs already contain some form of unit test generation.

**Comment by npm622** [comment]
Sorry for eavesdropping, but I figured I provide an approach I took a while back regarding this topic:
As with most answers here, it starts with writing your own plugin.  If you write your own plugin, you can start to write you own unit tests however you see fit.  I also had my plugin re-create (as best it could given the introspected data MBG returns) a 'create-schema.sql' script that would in fact re-create the introspected database schema but under a new (read: test) name.
This way you can both a) avoid testing against a live database and b) control exactly how and what you feel the need to test in the first place.
I know its very hand-wavy (my previously mentioned code is very old and wouldn't be of much use here), but at the time I did end up getting some great results from it all. 

    On Thursday, April 27, 2017 9:33 AM, Jeff Butler <notifications@github.com> wrote:
 

 I think you are asking for the generator to also generate unit tests. I think it is dangerous to generate unit tests against a live database. My favorite strategy is to use something like HSQLDB to build an in memory DB and run tests against that. But that's probably more than could reasonably be generated.One other way to think about it is that this is generated code and you can trust the generator. There are hundreds of unit tests in the generator build that test the generated code. Not to say that there aren't still some bugs remaining - there probably are. But it would be better to write generator tests to expose those bugs, and then fix them for everyone.You could write a plugin to generate unit test shell method in your environment, but most IDEs already contain some form of unit test generation.—

**Comment by jeffgbutler** [comment]
Thanks for the insight!  One of my main motivations in writing the plugin mechanism was so that I could always answer "yes" to any request - you can do anything you want to do in a plugin 😃 

There's no such thing as eavesdropping in open source - it's open!
