### ISSUE TITLE
about catalog and scheme in generating tablename in sql

### ISSUE THREAD

**Issue by limng06** [mybatis/generator#222]
first there is no 'catalog' in oracle 
while i want to have a subPackage 
i used the runtimeCatalog to generate the subPackage,  eg.( subpackage.tablename)
but it generate the tablename in sql ,too.

i have tried to use 'runtimeCatalog' and i'gnoreQualifiersAtRuntime' , but they don't work together!

**Comment by jeffgbutler** [comment]
Oracle has schema - you can use that to generate subpackages.

Please use the mailing list for future questions.
https://groups.google.com/forum/#!forum/mybatis-user
