### ISSUE TITLE
Bug: don't generate XXXWithBLOBs model if the table has only one BLOB column.

### ISSUE THREAD

**Issue by ruknow** [mybatis/generator#225]
Method: `org.mybatis.generator.internal.rules.ConditionalModelRules.generateRecordWithBLOBsClass`
Line: 84
`    public boolean generateRecordWithBLOBsClass() {
        int otherColumnCount = introspectedTable.getPrimaryKeyColumns().size()
                + introspectedTable.getBaseColumns().size();

        return otherColumnCount > 1
                && introspectedTable.getBLOBColumns().size() > 1;  //this line
    }
`
to be: 
` && introspectedTable.getBLOBColumns().size() > 0;`

**Comment by TroyTae** [comment]
@ruknow 
I think this is not bug...
If you set defaultModelType "conditional"(http://www.mybatis.org/generator/configreference/context.html), BLOBs model generates when table has two or more BLOB columns.
How about set your context attribute like this:
```<context defaultModelType="hierarchical">```

**Comment by ruknow** [comment]
@TroyTae 
I see, thank you!
