### ISSUE TITLE
mybatis-generator-gradle-plugin

### ISSUE THREAD

**Issue by cuisongliu** [mybatis/generator#228]
hi，I have implemented the Gradle version of mybatis generator plugin.
Almost have all the features, But the default value of a parameter is slightly modified.
**overwrite default is true.**
Can add to  [mybatis-generator-gradle-plugin](https://github.com/cuisongliu/mybatis_generator_gradle_plugin) the official document ?
Default language is Chinese.The plugin already uploads to  [plugins.gradle.org](https://plugins.gradle.org/plugin/com.cuisongliu.plugin.mybatis-generator).
Thanks a lot.

**Comment by jeffgbutler** [comment]
Nice work!

Please feel free to add information about this to the WIKI page here:
https://github.com/mybatis/generator/wiki/Third-Party-Tools

You could also announce it on the user mailing list.

**Comment by cuisongliu** [comment]
I was very happy to receive your reply.
I already append mybatis generator Gradle plugin to [WIKI](https://github.com/mybatis/generator/wiki/Third-Party-Tools) page.

**Comment by jeffgbutler** [comment]
Thank you!  Please let us know if we can do anything to help.
