### ISSUE TITLE
推荐使用MyBatis的GUI逆向工程

### ISSUE THREAD

**Issue by shenzhenMirren** [mybatis/generator#236]
这是一款开源的MyBatis逆向帮助工具目前支持Oracle , SqlServer , MySQL , PostgreSql数据库可以从实体类到service;源码地址https://github.com/shenzhenMirren/MyBatis-CMEU

**Comment by jeffgbutler** [comment]
I'm not sure what you are asking for with this issue.  You can add notice of new tools to this wiki page:

https://github.com/mybatis/generator/wiki/Third-Party-Tools

**Comment by jeffgbutler** [comment]
No response.
