### ISSUE TITLE
Spring 4.3.8 discussion (rehash)

### ISSUE THREAD

**Issue by hazendaz** [mybatis/generator#242]
Back in 2015, #41 was eventually declined due to what I feel are very small set of warnings in test code but very valid in any real generated code.  While I believe there are people still generating java 4 based code, I highly doubt any reasonable environment would be targetting java 1.4 as a runtime.  Plus there are a lot more warnings in the main code with missing overrides among other things so this doesn't drastically change the overall warning count and only affects java2 module.

That said, I'd like to re-introduce getting back on track with spring 4.3.8.RELEASE to start with.  We already pulled in springs legacy code to a mybatis module back in 2015 so the hook to spring 3 is no longer required.  While it issues deprecation warnings in the java2 module, I can easily prevent the warnings in the generated code so long as we upgrade the java requirement there to java 1.5.  That would address the issue raised in #41.

When looking over these modules, the baseline even for java5 module is actually java 6.  So I feel bringing the java2 module up to require java 1.5 is a small price to pay to get annotations if it's important enough to ignore the warnings generated off using such old code.

The alternative is to just ignore the few warnings this introduces and to which I personally feel anyone generating that code should be getting those warnings so they know to eventually fully upgrade.

Either way, I have this fixed easily enough and ready to go.

**Comment by jeffgbutler** [comment]
I feel pretty strongly that the mybatis-generator-systests-ibatis2-java2 project should stay at Java 1.4.  That modules's reason for existence is to make sure that the generator doesn't generate any code with annotations, generics, etc. - stuff that is supported in 1.5 onward - when targeting a Java 1.4 environment.  Raising the level beyond 1.4 would make those tests invalid.

As for the Spring level, please remember that this is a test dependency only.  Raising the Spring level would change nothing about the code that is generated, or any code that we actually publish - but it would add useless warnings to my workspace.  I may be a more obsessive about this than most, but I really strive to keep warnings to a minimum.  Raising this dependency level would do nothing to improve the functionality or reliability of the code we publish, but it would do a lot to make things more annoying for, mainly, me.

I have never heard any complaint about this on the mailing lists - which leads me to believe that no one is using this anyway.

The real solution to all this is to remove iBatis support from the generator.  I'd like to do that anyway.  So how about I add a warning to the iBatis targeted generators stating that they will be removed in the next release?  Then I'll remove all the iBatis code (and the horrifying Spring dependency) after the next release sometime this summer.

**Comment by hazendaz** [comment]
ok - sounds like a plan.  I'll close this.
