### ISSUE TITLE
If shielded jdbcType, don't let it output?

### ISSUE THREAD

**Issue by liuwenfeng554** [mybatis/generator#259]
generator:
&lt;resultMap id="BaseResultMap" type="xxxx">
    &lt;id column="id" jdbcType="VARCHAR" property="id" />
    &lt;result column="father_id" jdbcType="VARCHAR" property="fatherId" />
&lt;/resultMap>

Looking forward to the results:
&lt;resultMap id="BaseResultMap" type="xxxx">
    &lt;id column="id"  property="id" />
    &lt;result column="father_id" property="fatherId" />
&lt;/resultMap>

**Comment by jeffgbutler** [comment]
There is no configuration method from removing the jdbcType from the generated result map.  You could write a plugin to do that if you feel you need to do it.

Please ask future questions on the user mailing list.

https://groups.google.com/forum/#!forum/mybatis-user
