### ISSUE TITLE
About generating a uuid type of primary key

### ISSUE THREAD

**Issue by wangh09** [mybatis/generator#260]
Hi,  I'm wondering if mbg could generate uuid ? I already seen that it can generate an int valued primary key by:
 tableConfiguration.setGeneratedKey(new GeneratedKey("id", "mysql", true, null));

Thanks !

**Comment by jeffgbutler** [comment]
Please use the mailing list for future questions.

MBG does not generate IDs.  The generated key function is for retrieving a key that was generated by the database (usually from a sequence or identity column).  You could certainly generate a UUID on your own before inserting a record.
