### ISSUE TITLE
Some Problems

### ISSUE THREAD

**Issue by 601345138** [mybatis/generator#262]
1.Generated Example cannot execute fuzzy queries. For example,if you want to generate sql where clause like username like xxx, the generated sql doesn't contain ‘%’, for example:

`public Criteria andUsernameLike(String value) {
      addCriterion("username like", value, "username");
      return (Criteria) this;
}`

I want to generate sql such as '%username%' or '_username_' or '%username_' or '_username%' etc.

`public Criteria andUsernameLike(String value) {
      addCriterion("username like", "‘’%" + value “%'”, "username");
      return (Criteria) this;
}` 

2.Cannot generate select sql(not example) for views.It cause a lot of problems:cannot generate selectByPrimary(I know views doesn't have primary key, but I want to specify a column(or two) as primary key), cannot generate common select sql and so on.
3.Cannot generate common select sql and example select sql at the same time. If query has many criteria(>5), I'd choose common sql rather than example, because using example has to write a lot of java code of query criteria, if query criteria changed, a lot of code have to be modified.

4.The generated common select sql doesn't support fuzzy queries for string column.The developer have to write a lot of code such as:

`<if test="funname != null">
	<bind name="_funname" value="'%'+funname+'%'"/>
</if>`

5.Cannot generate code by relationship between tables.If the relationship between tables is many to many, the generated code cannot identify this. The developer has to write a lot of code to bulid relationship between tables and a lot of select sql have to be rewrite. For example:
`<resultMap id="BaseResultMap" type="cn.edu.nuc.article.entity.Article">
	<id column="articleid" jdbcType="INTEGER" property="articleid" />
	<result column="title" jdbcType="VARCHAR" property="title" />
	<result column="publishtime" jdbcType="TIMESTAMP" property="publishtime" />
	<result column="copywriter_id" jdbcType="INTEGER" property="copywriterId" />
	<result column="auditor_id" jdbcType="INTEGER" property="auditorId" />
	<result column="inst_id" jdbcType="INTEGER" property="instId" />
	<result column="processinstance_id" jdbcType="VARCHAR" property="processinstanceId" />
	<result column="articlestate" jdbcType="INTEGER" property="articlestate" />
	<result column="clickcount" jdbcType="BIGINT" property="clickcount" />
	<result column="downloadcount" jdbcType="BIGINT" property="downloadcount" />

	<association property="copywriter" javaType="cn.edu.nuc.article.entity.User">
		<id column="copywriterid" jdbcType="INTEGER" property="userid" />
		<result column="copywritername" jdbcType="VARCHAR" property="usertruename" />
	</association>

	<collection property="attachments" ofType="cn.edu.nuc.article.entity.Attachment">
		<id column="attachmentid" jdbcType="INTEGER" property="attachmentid" />
		<result column="filename" jdbcType="VARCHAR" property="filename" />
		<result column="filesize" jdbcType="INTEGER" property="filesize" />
		<result column="uploadtime" jdbcType="TIMESTAMP" property="uploadtime" />
		<result column="attachtype" jdbcType="INTEGER" property="attachtype" />
		<result column="fileid" jdbcType="VARCHAR" property="fileid" />
	</collection>

	<collection property="receivers" ofType="cn.edu.nuc.article.entity.User">
		<id column="receiverid" jdbcType="INTEGER" property="userid" />
		<result column="receivername" jdbcType="VARCHAR" property="usertruename" />
		<association property="institution" javaType="cn.edu.nuc.article.entity.Institution">
			<id column="receiver_inst_id" jdbcType="INTEGER" property="instid" />
			<result column="receiver_inst_name" jdbcType="VARCHAR" property="instname" />
		</association>
	</collection>
</resultMap>`

**Comment by jeffgbutler** [comment]
1. I realize the "by example" methods are limited and they won't work the way you are requesting here.  I have been working on a project to make it much easier to extend the example queries and make them more flexible, but that will come with the loss of backward compatibility.  You can see what I'm working on here:  https://github.com/jeffgbutler/mybatis-dynamic-sql.  I can't say when this will be ready, but I've been working on it for several months and I am feeling pretty comfortable with the API.

2. The generator will generate code for views - it does not know the difference between a view and a table.  Are you using PostgreSQL?  You might have hit on this issue: #200.  Also, you can use the VirtualPrimaryKey plugin to simulate a primary key for views (or tables) that don't have a primary key defined in the database.

3. I'm not sure exactly what you mean by this, but again the VirtualPrimaryKey plugin might help.

4. This is what SelectByExample is for.

5. This has been discussed many times over the years.  I have no plans to add relationship support to the generator at this time - although I am working on join support in the project I mentioned above.  But coding something that works for joins automatically is very difficult - and it would also be difficult to configure properly in the generator configuration.  I continue to believe that joins are probably best coded by hand.
