### ISSUE TITLE
Example full support or methods.

### ISSUE THREAD

**Issue by abel533** [mybatis/generator#263]
There is a common `Example` in my [Common Mapper](https://github.com/abel533/Mapper). It supports `or() `and `and ()`, as well as `orLike`, `orEqual` and other methods.

Does MBG need such functions?

If necessary, I will add to MBG and then submit a merge request.

Use as following:
```java
XXExmaple example = new XXExample();

example.and().andIdEquals(1).orIdGreaterThen(50).or().orIdLess(100);

```

Sql like this.
```sql
where (id = 1 or id >= 50) or (id < 100)
```

The following figure is common `Example`. Only for reference, and will not be added to the MBG.

![example](https://user-images.githubusercontent.com/1787798/28120335-52412a2a-674a-11e7-8e58-c8172c50d4b5.png)

**Comment by jeffgbutler** [comment]
My current plan is to deprecate the current example code in favor of the new utility I'm working on here: https://github.com/jeffgbutler/mybatis-dynamic-sql.  I really dislike the huge amount of code that gets generated in the example classes, and even with that huge amount of generated code, the example classes are still so inflexible.

With the new utility, the amount of generated code will dramatically decrease and all the example functionality will be moved into a common utility that is very flexible and easy to extend.

I hope to get an initial version of this out in the next month or two.  I'm working through making sure the API is robust and flexible, but the basic functionality is all complete at this point.

So with that in mind, I'm not really interested in adding even more generated code to the current example classes.

I'm open to comments and other ideas about this.  I'd be interested in your thoughts in light of my current plans.

**Comment by abel533** [comment]
@jeffgbutler I think this new way is more flexible and powerful than Example. I am very interested in this project and I will find time to learn.

**Comment by jeffgbutler** [comment]
@abel533 thanks for your feedback!

**Comment by i3587616** [comment]
[mybatis-dynamic-sql](https://github.com/jeffgbutler/mybatis-dynamic-sql).不会用。
我想用 example.and() 加入Or  语句。比如a=1 and (b=2 or b=3) 这样子的。
网上教的方法是        public Criteria andDtidOr(Long mid) {
            addCriterion("(om_tid ="+ mid +" or om_did =" + mid +")");
            return (Criteria) this;
        }
但是这个是拼接不是那种 ：叫形参还是什么的方式。会有注入的风险。
你是怎么办到的，还有人说要修改源码。我看了你那个[Common Mapper](https://github.com/abel533/Mapper)。
不知道方法在那，and()的

**Comment by i3587616** [comment]
@abel533

**Comment by i3587616** [comment]
@jeffgbutler i see.but i need time to study it and i use the old run time in my company project.
i modify the  <sql id="Example_Where_Clause"> and example to solve the and or problem.
when i have more time i will study the [MyBatis Dynamic SQL] and use it to my company project
