### ISSUE TITLE
How can I get the Generator work status is overwrite in PluginAdapter ? 

### ISSUE THREAD

**Issue by liyiorg** [mybatis/generator#264]
CMD 
```java
java -jar mybatis-generator-core-x.x.x.jar -configfile \temp\generatorConfig.xml -overwrite
```
Can I get the MBG work status is overwrite in PluginAdapter ? 

```java
public class MyGeneratorPlugin extends PluginAdapter {
           
       //TODO  get MBG work status is overwrite
}
```

**Comment by jeffgbutler** [comment]
There is no support for retrieving that setting in a plugin.  Code generation is the same regardless of that setting.  The setting is only used when writing results.  You could write your own ShellCallback if you need to change something about how the files are written.

Please use the mailing list for future questions.
