### ISSUE TITLE
Update by example selective without ids

### ISSUE THREAD

**Issue by Monika93** [mybatis/generator#265]
I used 1.3.2 version of a generator. Few tables have many operations made on their rows by external applications and I have to make sure I don't make an update on a row in the tables when it was already changed. In most cases I got an object with id to make operations and save it in database, but when working with these tables, I use updateByExampleSelective instead of updateByPrimaryKey to filter by column with row state and id, but then I need to keep in mind to set null on id of updated object to not get SQL exception from the database.

I want to not take care about updating ids and tried to fix it by updating a myBatis Generator to latest 1.3.5, make use of "isGeneratedAlways" column override attribute and add it to columns with "generatedKey" element. It works, but the attribute isn't created for such task like this.

**Comment by jeffgbutler** [comment]
I'm not sure what you mean,  Can you give an example of something you think is incorrect?

**Comment by jeffgbutler** [comment]
No response.

**Comment by Monika93** [comment]
I try to call `updateByExampleSelective(object, example)` with just modified object from database (with ID included), and then I get SQL exception -232 "`A SERIAL column id may not be updated`" because of the attempt to update ID. [Informix](https://www.ibm.com/support/knowledgecenter/en/SSGU8G_11.70.0/com.ibm.em.doc/errors.html) advices to not include serial columns into update statement.

Right now, I need to set ID as null for modified object which was already in database before calling the `updateByExampleSelective` method to pass the generated SQL. I would like to avoid that. Alternatively, I can use `<columnOverride column="id" isGeneratedAlways="true"/>` for all primary key columns, but as I said, it's tiresome to add it for every table in configuration.

I think the generator should skip adding SET statements entirely for serial columns in `updateByExampleSelective` method, based on SERIAL type of the column or by use of `<generatedKey>` for column to skip.
