### ISSUE TITLE
Redundant mapperName and sqlProviderName

### ISSUE THREAD

**Issue by Monika93** [mybatis/generator#266]
I recently upgraded a version of used myBatis Generator from 1.3.2 to 1.3.5. I noticed that mapper and sqlProvider classes aren't generated in the same subpackages as the model class. It looks like the generator ignores the subpackage defined in domainObjectName.

I found a workaround by adding mapperName and sqlProviderName to each table in configuration file, with subpackages and full names of classes. I think it should work like in old version of generator, without this troublesome work.

**Comment by jeffgbutler** [comment]
I agree this is a regression.  Will have a fix shortly.

**Comment by jeffgbutler** [comment]
I believe this PR has restored the old functionality.

If you are able to test with the snapshot build, please let us know if this is working as it used to.
