### ISSUE TITLE
A bug for javaModelGenerator config constructorBased with only one column is blob

### ISSUE THREAD

**Issue by itfsw** [mybatis/generator#267]
when db columns has only one column is blob, plugin will only generate java model with full column constructor.so BaseResultMap will not found the constructor!

**Comment by TroyTae** [comment]
We found this bug: https://github.com/mybatis/generator/issues/205
And this fix will apply 1.3.6.
If you need to fix this bug now, change defaultModelType "hierachy" or build your own code in your local.
![image](https://user-images.githubusercontent.com/20078201/28701196-7263634e-738f-11e7-9dea-8cf5a4a0d64b.png)

**Comment by itfsw** [comment]
thanks for your job.
