### ISSUE TITLE
How to merge Java file

### ISSUE THREAD

**Issue by whaiming** [mybatis/generator#269]
public String mergeJavaFile(String newFileSource,
            String existingFileFullPath, String[] javadocTags, String fileEncoding)
            throws ShellException {
        throw new UnsupportedOperationException();
    }

**Comment by TroyTae** [comment]
@whaiming 
Using this method:
```
public static void writeFile(String outDir, String content) throws IOException {
	FileOutputStream fos = new FileOutputStream(new File(outDir), false);
	OutputStreamWriter osw = new OutputStreamWriter(fos, StandardCharsets.UTF_8);
	BufferedWriter bw = new BufferedWriter(osw);
	bw.write(content);
	bw.close();
}
```
But this issue does not seem to be related to this project...
Please search for these issues in the future.

**Comment by whaiming** [comment]
Thank you! But I do not mean that, in this project, I hope that the generated Java files can be merged as XML files rather than simple coverage. However, in this project did not give an implementation, just throw an UnsupportedOperationException.

**Comment by TroyTae** [comment]
@whaiming 
What kind of XML?
Can you show me a sample code?

**Comment by TroyTae** [comment]
Oh I see. I find that code:
https://github.com/mybatis/generator/blob/a19303b6505bb45a62ee9bf9de378bbff84369cd/core/mybatis-generator-core/src/main/java/org/mybatis/generator/internal/DefaultShellCallback.java#L113

**Comment by TroyTae** [comment]
@whaiming 
Look at this url:
https://github.com/mybatis/generator/blob/a19303b6505bb45a62ee9bf9de378bbff84369cd/core/mybatis-generator-core/src/main/java/org/mybatis/generator/api/ShellCallback.java#L28-L31

Maybe default ShellCallback doesn't support merging java files.

**Comment by whaiming** [comment]
@TroyTae Thank you!You are right, this project did not give the realization。MergeJavaFile () This method simply throws an exception, so I would like to ask if there is no one to try in this way to achieve Java code merge

**Comment by jeffgbutler** [comment]
Java code merge is only supported when running in Eclipse.  The code is here:

https://github.com/mybatis/generator/blob/master/eclipse/org.mybatis.generator.eclipse.core/src/org/mybatis/generator/eclipse/core/callback/EclipseShellCallback.java

**Comment by whaiming** [comment]
@jeffgbutler Thank you! I use the IntelliJ IDEA, but today I simply achieved that method.

**Comment by whaiming** [comment]
@jeffgbutler Will you support IntelliJ IDEA later?

**Comment by jeffgbutler** [comment]
I don't plan on writing anything for IntelliJ.  The current merger is strongly tied to the Eclipse Java Parser and AST,  My long range plan is to rewrite the merger using http://javaparser.org so it can run everywhere.  I don't have any timetable for that.

**Comment by Paul0523** [comment]
I am very much looking forward to use that new feature you said, thank you.
