### ISSUE TITLE
A Chinese version of the this document

### ISSUE THREAD

**Issue by abel533** [mybatis/generator#27]
I translate this document with my friends, a Chinese version is provided.

Document address:http://mbg.cndocs.tk/

I have the source code of `site/xhtml`  

**Can add this Chinese version to the official document ?**

git address:http://git.oschina.net/free/mybatis-generator-core

`site/xhtml`address:http://git.oschina.net/free/mybatis-generator-core/tree/master/src/site

If you can, you can check out from the above address.

My email address is:abel533@gmail.com

**Comment by jiangchao0304** [comment]
got it  thanks

**Comment by windlikeman** [comment]
in fact,there is no chinese document ...

**Comment by jeffgbutler** [comment]
This is so old so I'm not sure if it is still valid. If you would like to contribute, please make a pull request with the Chinese version. Thanks!
