### ISSUE TITLE
table schema other schema exists issue

### ISSUE THREAD

**Issue by OrangesHuang** [mybatis/generator#270]
The schema in MysqL names auth2_relation belongs to me，and sys schema belongs to others.
In my generator.xml ,table schema is auth2_relation, but in sys is have view not belongs to me .it will not work because the other view can't read into mybatis generator

**Comment by jeffgbutler** [comment]
I'm sorry, but I don't understand this question.

I will say that MySql schema's are difficult to work with and it is usually best not to put the schema in your generator configuration.  See here: http://www.mybatis.org/generator/usage/mysql.html

**Comment by OrangesHuang** [comment]
For Example, In my DataBase have two schema, One is called to "auth2", the Two is called to "sys" that belongs to others. I don't have jurisdiction to open it. but I can see how many view in this schema and that views's name. In my generator.xml the <tabe  tableName= "%" schema="auth2">,  I think it just work in schema called "auth2". but it's not work as I think. It Will find "sys" and try to see that view that can't open , then it break and can't work with issue.

**Comment by jeffgbutler** [comment]
In my tests, I don't see this behavior.  But as stated in the link I provided, it is not a good idea to specify a schema in MySql.  So I recommend you use a connection string like this

```
jdbc:mysql://localhost/auth2
```
And a generator configuration like this:

```SQL
<table tableName= "%" />
```
Please use the mailing list for any future questions.

**Comment by OrangesHuang** [comment]
![image](https://user-images.githubusercontent.com/13177793/29302901-b222568c-81ba-11e7-835a-15a1ddb80045.png)
this my generator.xml tableName="%" schema="auth2_relation"
auth2_relation is my schema
![image](https://user-images.githubusercontent.com/13177793/29302901-b222568c-81ba-11e7-835a-15a1ddb80045.png)
but when i run , it want to read View 'sys.host_summary'
![image](https://user-images.githubusercontent.com/13177793/29302921-e3e038f6-81ba-11e7-8240-c09b98782189.png)

**Comment by jeffgbutler** [comment]
I see you are using the new version of Connector/J.    That version has what I consider to be a bug in that it returns information from the system schemas when it wasn't asked for.  This is different from version 5 of Connector/j.

You can do one of the following:

1. Use version 5.x of Connector/J
2. Add the property "nullCatalogMeansCurrent=true" to your URL or connection properties

**Comment by OrangesHuang** [comment]
thx~
