### ISSUE TITLE
replaceAll table prefix to domain

### ISSUE THREAD

**Issue by yangdailin** [mybatis/generator#275]
`I found that <table tableName="t_user" domainObjectName="User"> only set one table to domain, if i use <table tableName="%">to all tables to domains, is there can add new features that replaceAll table prefix before to domain? such as <table tableName="%"><TableRenamingRule searchString="T" replaceString=""/></table>`

**Comment by jeffgbutler** [comment]
Please see #176.  This is in the snapshot builds, but not released yet.

**Comment by jeffgbutler** [comment]
I see from your comments in #176 that this works for you.  I'll try to cut a release in the next week or two.

**Comment by pecdew** [comment]
hi! @jeffgbutler, When will the new version be released?
I can not wait any more 😊
