### ISSUE TITLE
Extends PluginAdapter and override the method of initialized, run with introspectedTable.getRemarks() is empty by DB MySQL .

### ISSUE THREAD

**Issue by liyiorg** [mybatis/generator#276]
MySQL  introspectedTable.getRemarks() is empty.
```java

public class MyPlugin extends PluginAdapter{
        
        @Override
	public void initialized(IntrospectedTable introspectedTable) {
		
		String remarks = introspectedTable.getRemarks();
		System.out.println(remarks );  //output empty text
	}
}

```

**Comment by jeffgbutler** [comment]
The generator is retrieving the remarks from DatabaseMetaData.  In MySql, Connector/J only returns remarks if you set the connection property ```useInformationSchema=True```.  So make sure you have that property set and try again.

Please ask further questions on the mailing list.
