### ISSUE TITLE
About rootClass issue

### ISSUE THREAD

**Issue by yishuihancheng** [mybatis/generator#282]
I use rootClass in MBG config, but was stuck by the rootClass property
this is my MBG config
`<javaModelGenerator targetProject="src/main/java"
                            targetPackage="com.tulip.drama.service.user.model">
            <property name="enableSubPackages" value="true"/>
            <property name="rootClass" value="com.tulip.service.user.model.BaseEntity"/>
            <property name="trimStrings" value="true"/>
</javaModelGenerator>`

this is my BaseEntity class

public class BaseEntity implements Serializable {
    private Status status;
    private Date createTime;
    private Date updateTime;
    public Status getStatus() {
        return status;
    }
    public void setStatus(Status status) {
        this.status = status;
    }
    public Date getCreateTime() {
        return createTime;
    }
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return updateTime;
    }
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}

User class was generated by MBG, like this
public class User extends BaseEntity {
    private String name;
    private Integer age;
    private Status status;
    private Date createTime;
    private Date updateTime;
    public String getName() {
        return name;
    }
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
    public Integer getAge() {
        return age;
    }
    public void setAge(Integer age) {
        this.age = age;
    }
    public Status getStatus() {
        return status;
    }
    public void setStatus(Status status) {
        this.status = status;
    }
    public Date getCreateTime() {
        return createTime;
    }
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    public Date getUpdateTime() {
        return updateTime;
    }
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}

My question is that why User class still have the properties of id, status, createTime and updateTime,  it overrides the same properties of super class. But the document explain the use of rootClass in the following:
This property can be used to specify a root class for all generated Java model objects. MyBatis Generator will specify this value as the super class of the primary key object, if the table has a primary key, or the record object otherwise. This value may be overridden by specifying the rootClass property on a Table configuration.
Important: If MyBatis Generator is able to load the root class, then it will not override a property in the root class that exactly matches a property that would normally be generated. An exact match of a property is defined as follows

Property name matches exactly
Property is of the same type
Property has a "getter" method
Property has a "setter" method
If specified, the value of this property should be a fully qualified class name (like com.mycompany.MyRootClass).

Did I miss something. Or it is designed like this

**Comment by yishuihancheng** [comment]
#1 Are we faced with the same problem?

**Comment by jeffgbutler** [comment]
Most likely this is caused by your root class not being on the generator's class path when you run it.  There was probably a warning about this issued when you ran the generator.

Please ask future questions on the mailing list.

**Comment by yishuihancheng** [comment]
Hi BaseEntity class and User class are in the same package, do I still need to put the related jar to the  generator's class path?

**Comment by jeffgbutler** [comment]
Yes - the root class must be in the class path so it can be introspected.

**Comment by leonbloy** [comment]
In case this helps:

I'm not sure this is a bug, probably not, but I wasted some time till I got it working.

In most respects (practically in all respects), these two lines are equivalent:

		<columnOverride column="NumberDocument" property="numDoc" javaType="String"  />

		<columnOverride column="NumberDocument" property="numDoc" javaType="java.lang.String"  />

Well, it turns that for this matching, they are not! Only when I tried (desperately) to write the second one the matching worked.
