### ISSUE TITLE
MSSQL datetime query slow

### ISSUE THREAD

**Issue by huangshanongfushan** [mybatis/generator#284]
Hello,I got a problem now . I use Mybatis genertor for MSSQL, if there is a column which type is datetime and its has index, when I search results with java codes and using the datetime column ,the results comes very slow.If I use the sql in mssm tools,the results commes very fast.

**Comment by jeffgbutler** [comment]
I can't imagine this has anything to do with the generator.  You might try a plain JDBC program as a test to see if MSSQL is slow in general with datetime columns and JDBC.

**Comment by jeffgbutler** [comment]
No response.
