### ISSUE TITLE
Support default interface methods in JavaVisibility enum

### ISSUE THREAD

**Issue by nickmakes** [mybatis/generator#287]
In a few plugins, I would like the ability to leverage Java 8's "`default` visibility" for a few method implementations.

Not sure I have a great idea as to resolve this, because `DEFAULT` visibility already exists as an enum to denote package private.  Moreover, this visibility obviously wouldn't apply for all cases (read: `JavaElement`s), but only for methods in interfaces.  However, it would be nice to have this available.

**Comment by nickmakes** [comment]
**UPDATED:**

My current workaround involves leveraging the `JavaMethod` wrapper class I've already written from previous hacks.  I added the field `Boolean defaultMethod` along with its getter/setter to the `JavaMethod` class (which extends mbg's `Method` dom class and overrides `getFormattedContent`).

> For context, I'm overriding the method's formatted content class for aesthetic purposes, I prefer extra spaces after opening and before closing parens when parameters are present in the method signature.

Anyways, I added an extra `else if` block to the existing `if ( !interfaceMethod )` case...

```java
if ( !interfaceMethod) {
  sb.append ( this.getVisibility().getValue() );

  // add static, final, synchronized, native, and abstract keywords if necessary
} else if ( BooleanUtils.isTrue( defaultMethod ) }
  sb.append( "default" );
}
```

**Comment by jeffgbutler** [comment]
I added support for default and static interface methods nearly a year ago in #182. 

 It's terrible that there hasn't been a release of the generator in so long.  I will get on that.

**Comment by npm622** [comment]
Ah that's awesome. Glad to see I was on the right track there. And absolutely no apologies needed, you owe nothing considering all you already do for this community. 

Sent from my iPhone

On Oct 30, 2017, at 11:30 AM, Jeff Butler <notifications@github.com> wrote:

I added support for default and static interface methods nearly a year ago in #182.

It's terrible that there hasn't been a release of the generator in so long. I will get on that.
