### ISSUE TITLE
<table tableName="Auth_UserRole" alias="Auth_UserRole$"/> <table tableName="%" alias="%$"/>

### ISSUE THREAD

**Issue by yeziwen** [mybatis/generator#288]
a example like this:

table tableName="Auth_UserRole" alias="Auth_UserRole$"

 i want to use the rule for all the tables like this:

table tableName="%" alias="%$"

but ,it do not.
so i have to do like this:
table tableName="Auth_Role" alias="Auth_Role$"
table tableName="Auth_User" alias="Auth_User$"
able tableName="Auth_UserRole" alias="Auth_UserRole$"

**Comment by yeziwen** [comment]
`<table tableName="Auth_Role" alias="Auth_Role$"/>
   <table tableName="Auth_User" alias="Auth_User$"/>
   <table tableName="Auth_UserRole" alias="Auth_UserRole$"/>`

**Comment by clcy1243** [comment]
u could write new plugin to do this. like  RenameExampleClassPlugin;

**Comment by jeffgbutler** [comment]
Closing - can be accomplished with a plugin
