### ISSUE TITLE
Can't get SqlServer Comment

### ISSUE THREAD

**Issue by brainysoon** [mybatis/generator#289]
```
  <commentGenerator>
            <!-- 是否去除自动生成的注释 true：是 ： false:否 -->
            <property name="suppressAllComments" value="false"/>
        </commentGenerator>
        <!--数据库连接的信息：驱动类、连接地址、用户名、密码 -->
        <jdbcConnection driverClass="com.microsoft.sqlserver.jdbc.SQLServerDriver"
                        connectionURL="jdbc:sqlserver://47.92.150.231:1433;Database=CDISDEBUG;useInformationSchema=true"
                        userId="sa"
                        password="gD123">
        </jdbcConnection>
```

I use SqlServer 2012 ,and I want generating comment but failed.

**Comment by jeffgbutler** [comment]
Add `<property name="addRemarkComments" value="true"/>` to your `<commentGenerator>` configuration.  This will add database remarks if they can be retrieved from the database metadata.

See here for documentation:

http://www.mybatis.org/generator/configreference/commentGenerator.html

I will say that the databases vary widely in their support of this and I don't know personally if this will work in SQL server.  But it is the best we can do.

**Comment by brainysoon** [comment]
Thanks any way, but it's not working in SqlServer.

**Comment by brainysoon** [comment]
I guess It's SqlServer's problems, I read SqlServer document that the JdbcDriver can't get the right comment from  SqlServer.

**Comment by jeffgbutler** [comment]
OK.  Nothing we can do about that unfortunately.
