### ISSUE TITLE
The Mapper Class lose method when use mysql-connector-java 6.x or higher

### ISSUE THREAD

**Issue by pky920216344** [mybatis/generator#291]
# normal:
public interface SysUserMapper {
    long countByExample(SysUserExample example);

    int deleteByExample(SysUserExample example);

    int deleteByPrimaryKey(String userId);

    int insert(SysUser record);

    int insertSelective(SysUser record);

    List<SysUser> selectByExample(SysUserExample example);

    SysUser selectByPrimaryKey(String userId);

    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);

    int updateByPrimaryKeySelective(SysUser record);

    int updateByPrimaryKey(SysUser record);
}
# error
public interface testMapper{
    long countByExample(SysUserExample example);

    int deleteByExample(SysUserExample example);

    int insert(SysUser record);

    int insertSelective(SysUser record);

    List<SysUser> selectByExample(SysUserExample example);

    int updateByExampleSelective(@Param("record") SysUser record, @Param("example") SysUserExample example);

    int updateByExample(@Param("record") SysUser record, @Param("example") SysUserExample example);
}

**Comment by jeffgbutler** [comment]
It looks like there isn't a primary key associated with your table.  The generator simply uses whatever information it can obtain about the table from the JDBC driver.

You could use the VirtualPrimaryKey plugin to tell the generator what columns act like a primary key.  See here for details:

http://www.mybatis.org/generator/reference/plugins.html

**Comment by pky920216344** [comment]
It may  not as like what you say.The problem happened only when I was using mysql-connector-java 6.x or higher.Using mysql-connector-java 5.x will not.

**Comment by zhubenle** [comment]
I've had this problem too, The jar I used was mysql-connector-java-5.1.30-bin.jar

**Comment by jeffgbutler** [comment]
This must be some issue in the MySql driver.  If the driver doesn't return primary key information, then the generator will not generate the methods related to primary keys.

**Comment by harawata** [comment]
Try adding `useInformationSchema=true` to the connection URL.
For example: `jdbc:mysql://127.0.0.1/test?useInformationSchema=true`

**Comment by pky920216344** [comment]
The idea is so good, thank you

**Comment by jeffgbutler** [comment]
This seems resolved with the MySql URL change.

**Comment by jeffgbutler** [comment]
The docs are here: https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-url-format.html

Multiple properties are separated with `&`

jdbc:mysql://localhost:3306/91majiong?serverTimezone=UTC&useInformationSchema=true
