### ISSUE TITLE
secondary meter create

### ISSUE THREAD

**Issue by xuegangliu** [mybatis/generator#292]
How to implement the table query.MyBatis Generator secondary meter create

**Comment by jeffgbutler** [comment]
I don't understand what you are asking.

**Comment by xuegangliu** [comment]
Generator xml implement table CURD
example
(select * from t_201711)
(select * from t_201712)

**Comment by jeffgbutler** [comment]
I'm sorry, I still don't understand what you are asking.

**Comment by jeffgbutler** [comment]
No response.
