### ISSUE TITLE
`mvn clean install` generate Error<s> under mybatis-generator-maven-plugin project

### ISSUE THREAD

**Issue by Baozhb** [mybatis/generator#30]
Does any body encounter this situations:
when I use `mvn clean install` under mybatis-generator-maven-plugin directory. I got **ERRORS**:
[INFO] Checking unresolved references to org.codehaus.mojo.signature:java16:1.1
[INFO]
[INFO] --- maven-bundle-plugin:2.5.3:manifest (bundle-manifest) @ mybatis-genera
tor-maven-plugin ---
[ERROR] Manifest org.mybatis.generator:mybatis-generator-maven-plugin:maven-plug
in:1.3.3-SNAPSHOT : The default package '.' is not permitted by the Import-Packa
ge syntax.
 This can be caused by compile errors in Eclipse because Eclipse creates
valid class files regardless of compile errors.
The following package(s) import from the default package null
[ERROR] Error(s) found in manifest configuration
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.410s
[INFO] Finished at: Sat Mar 07 17:02:00 CST 2015
[INFO] Final Memory: 33M/441M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.felix:maven-bundle-plugin:2.5.3:manife
st (bundle-manifest) on project mybatis-generator-maven-plugin: Error(s) found i
n manifest configuration -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionE
xception
I think there maybe something wrong when maven-bundle-plugin in process. But I can not find why after an afternoon's Google search.

More stranger, when I run `mvn install` twice after `mvn clean`. I will get an **BUILD SUCCESS** result.

My purpose is to import mybatis-generator project into my eclipse. and I want to build the project just with a command `mvn clean install` under the **generator/core** directory. But with this error, the purpose is out of reache.

**NOTE**
my envirentment:
maven: 3.1.1
jdk: 1.7.0_07

Any help will be appreciated.

**Comment by jeffgbutler** [comment]
I do not have this issue when I run the build.  My best guess is that you either don't have the current source, or that something is corrupt in your local Maven repo.

If you continue to have questions, please use the mailing list.  We do not use github for questions.

**Comment by Baozhb** [comment]
Thanks for your reply and advice.
And after hours search and observation, I eventually can make a one fire `mvn clean install` to build the mybatis-generator **SUCCESS**.
Firstly, when I run `mvn install` and the command is **FAILED**, **AND** generate a Class "HelpMojo.java" which is under the **Default package** and one .class file "HelpMojo.class"(Error message is like the previous post). Then run `mvn install` secondly, I will got a **SUCCESS**.

The issue, I best guess is "maven-bundle-plugin" do not allow the a Class in a **Default package**.

So, my solution is to configure the "maven-plugin-plugin" plugin to generate the "HelpMojo.java" under a package called "mojo.help". It is work even I do not know why and I think this solution does not beautiful.

But anyway, It works.

If something I was wrong, please give me some information.

Thanks for your reply and advice again.

**Comment by jeffgbutler** [comment]
I was able to duplicate this.  It is an Eclipse bug, but there is a work around.

Your problem report was not very clear.  This issue does not happen when you run maven from the command line, it only happens when you run maven through eclipse.

**Comment by Baozhb** [comment]
Sorry for my poor English!

But the problem I encountered was happened exactly when I run maven from the command line.
When I import it to Eclipse, I also encounter a problem which is because the lower version of my m2eclipse-mavenarchiver.

Very glad to give some little help.

Thanks for you great work too!
