### ISSUE TITLE
when you use MyBatis3DynamicSQL & RowBoundsPlugin, "default" was missed in mapper file.

### ISSUE THREAD

**Issue by yoker** [mybatis/generator#303]
There have not `default` keyword in front of `selectByExampleWithRowbounds` interface method if you choice `RowBoundsPlugin` & `MyBatis3DynamicSQL`.
as a result, you got an error when you compile the project.

version: 1.3.6

**Comment by jeffgbutler** [comment]
Yeah - RowBoundsPlugin won't work with the new runtime.  It's more complex than adding the default modifier.  I'll work on a fix for that.
