### ISSUE TITLE
Can distinct work other field except id? 

### ISSUE THREAD

**Issue by wangleigithub** [mybatis/generator#305]
I found if use setDistinct(true),  the output sql will like: select distinct id , name ,sex .... from xxx, if I want distinct other field , for example : select id , distinct name, sex .... from xxx , how can I do?

**Comment by jeffgbutler** [comment]
This is standard SQL - distinct means that the entire row will be distinct.

https://www.w3schools.com/sql/sql_distinct.asp

You will need to write custom SQL if you need something different than this.
