### ISSUE TITLE
addRemarkComments can not include table and column remarks from db table

### ISSUE THREAD

**Issue by ywlLinux** [mybatis/generator#312]
in the new targetRuntime MyBatis3DynamicSql，addRemarkComments can not include table and column remarks from db table

**Comment by TroyTae** [comment]
@ywlLinux 
FYI
http://www.mybatis.org/generator/configreference/commentGenerator.html
![image](https://user-images.githubusercontent.com/20078201/34854138-287d7164-f77b-11e7-994b-e9bf4716270e.png)

**Comment by jeffgbutler** [comment]
Thanks for reporting!  This is an error in the MyBatis3DynamicSql runtime only.
