### ISSUE TITLE
Generate two selectByExampleWithRowbounds method?

### ISSUE THREAD

**Issue by qq592304796** [mybatis/generator#313]
Add this configuration
`<plugin type="org.mybatis.generator.plugins.RowBoundsPlugin"/>`
Multiple table elements
`mvn -Dmybatis.generator.overwrite=true mybatis-generator:generate`
mybatis-generator-maven-plugin.version:1.3.5,1.3.6
There will be one Mapper.xml contains two selectByExampleWithRowbounds method

**Comment by TroyTae** [comment]
@qq592304796 
![image](https://user-images.githubusercontent.com/20078201/34854037-8cc8ec80-f77a-11e7-81c2-3b25706f1d67.png)
Now I used RowBoundsPlugin too.
But generator seems to work to well. (version 1.3.5/6)
Can you show me your generated code?

**Comment by qq592304796** [comment]
I checked my code, discovery is my problem
found configured with two of the same table elements
![table](https://user-images.githubusercontent.com/26601421/34861439-bff98d7e-f79f-11e7-849c-126319871057.png)
![xml](https://user-images.githubusercontent.com/26601421/34861441-c4b5c04e-f79f-11e7-9a4c-d99b20c6dcca.png)
thanks @TroyTae

**Comment by jeffgbutler** [comment]
Assuming this is resolved.

**Comment by 12ycli** [comment]
Have you guys found a solution?

**Comment by 12ycli** [comment]
I just found two same methouds and deleted one of them. It works!
