### ISSUE TITLE
Unsigned JdbcType is resolved to only signed JavaType , which won't it overflow?

### ISSUE THREAD

**Issue by 51Bigod** [mybatis/generator#314]
For Example , SMALLINT  is resolved to Short ,
     The scope of the Short is  -32768 ~ 32767,
     The scope of the Signed SMALLINT is also -32768 ~ 32767,
 but 
     The scope of the Unsigned SMALLINT is also  0 ~ 65535,
which won't it overflow?

**Comment by 51Bigod** [comment]
Thank you for your contribution , I think I've got the answer by [.](http://www.mybatis.org/generator/usage/mysql.html) 
`MySql supports both signed, and unsigned, numeric fields. These are not JDBC types, so MyBatis generator cannot automatically account for these types of fields. The Java data types are always signed. This can lead to a loss of precision when using unsigned fields. The solution is to provide a <columnOverride> for any unsigned numeric field in MySql`

**Comment by jeffgbutler** [comment]
This is how MySql works.  You'll need to do the `<columnOverride>`

**Comment by 51Bigod** [comment]
Thanks
