### ISSUE TITLE
domainObjectRenamingRule issue

### ISSUE THREAD

**Issue by TroyTae** [mybatis/generator#316]
Now I try to create prefix before domainObject.
So I find a document about domainObjectRenamingRule.
[ http://www.mybatis.org/generator/configreference/domainObjectRenamingRule.html ]

![image](https://user-images.githubusercontent.com/20078201/34853927-cd0e2c5c-f779-11e7-92cb-4040c0e5c0b0.png)
But therer is no definition in DTD.
This feature is not update yet?

**Comment by jeffgbutler** [comment]
It's in the DTD here: http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd

**Comment by TroyTae** [comment]
@jeffgbutler 
![image](https://user-images.githubusercontent.com/20078201/34865933-fbac5e1e-f7bd-11e7-8935-d409643741a1.png)
Now I use like this.
But I can't see it.

**Comment by TroyTae** [comment]
@jeffgbutler 
I'm sorry this is my IDE bug.
After change version, IDE use 1.3.2 version jar file;;
