### ISSUE TITLE
About jsr310

### ISSUE THREAD

**Issue by LiZhenNet** [mybatis/generator#324]
Is mybatis generator support jsr310？
I can not find any useful infomation from [whatsNew](http://www.mybatis.org/generator/whatsNew.html)。

**Comment by jeffgbutler** [comment]
Not currently, but it is something I should add as MyBatis now supports these types.

**Comment by jeffgbutler** [comment]
Resolved via #326

**Comment by LiZhenNet** [comment]
Thanks，Happy Chinese new year。
