### ISSUE TITLE
Feature request: Mapper.updateByExampleSelective() allow updating to null

### ISSUE THREAD

**Issue by monrealis** [mybatis/generator#325]
It would be nice if I could use `Mapper.updateByExampleSelective(record, examaple)` to set some columns to `null` values. Is there a way to do it? Is there an existing plugin that allows something similar?

`null` is the most frequently used value in enterprise databases, after all :)

**Comment by jeffgbutler** [comment]
updateByExample (not selective) will set null values.  updateByExample will set column values to null if the property in the record is null.  updateByExampleSelective will not update columns if the property in the record is null.

With the new MyBatisDynamicSQL runtime you could control this differently on each column.

**Comment by monrealis** [comment]
Thanks, I didn't know about it (http://www.mybatis.org/mybatis-dynamic-sql/docs/update.html). It reminds me a little bit of JPA criteria API, which has bigger complexity than `updateByExampleSelective()` and looks like a little bit of overhead for a simple use case of updating a column to null. There is so little that is lacking in current implementation `updateByExampleSelective()`:)
By the way, can those `SqlColumn` and `SqlTable` classes be generated with MyBatis generator (http://www.mybatis.org/mybatis-dynamic-sql/docs/quickStart.html)?

**Comment by monrealis** [comment]
The problem with `updateByExample()` is that it updates _all_  columns. It might be OK for one record (and even then it is usually inconvenient, because most likely you will have to read the row before updating so that you don't have to fill all 100 columns), but not for many records.
If you want to reset one column to null for 2/3 of all rows in a big table, there is no way, as reading and updating one by one is not what you want.

**Comment by monrealis** [comment]
Feature could be implemented in this way:
* Generate enum (or a simple class) `TableColumns` for each table, with members for each column
* Add `TableColumns... affectedColumns` parameter to `updateByExample()`
* Or alternatively add `TableColumns... columnsToUpdateToNull` to `updateByExampleSelective()`

P.S. Do you know if there exists a plugin that generates something similar to `TableColumns`?

**Comment by jeffgbutler** [comment]
The generator will generate everything needed for MyBatisDynamicSQL - see http://www.mybatis.org/generator/whatsNew.html for some details about how to make that happen.  You just need to set the target runtime like this: `<context targetRuntime="MyBatis3DynamicSql">`

One of my main motivations for creating MyBatisDynamic SQL is to make these kinds of requests easier.  The current generated code is pretty brittle and hard to modify - it would take a very complex plugin to make this work in the old style.

**Comment by monrealis** [comment]
You did a great job creating a library. It's a little bit confusing that both http://www.mybatis.org/mybatis-3/dynamic-sql.html and http://www.mybatis.org/mybatis-dynamic-sql/ documentation pages are called "Dynamic SQL", and the first one is on top in Google :)

Since model classes generated for both `targetRuntime="MyBatis3"` and `targetRuntime="MyBatis3DynamicSql"` seem to be the same, perhaps it would be worth having a value `targetRuntime="MyBatis3+DynamicSql"` so that the `<context>` does not have to be duplicated if you want to use both. It's just an idea.
