### ISSUE TITLE
domainObjectRenamingRule  Do not work

### ISSUE THREAD

**Issue by fanhualei** [mybatis/generator#327]
I use 1.3.6   run generator with java

<dependency>
    <groupId>org.mybatis.generator</groupId>
    <artifactId>mybatis-generator-core</artifactId>
    <version>1.3.6</version>
</dependency>

**Comment by jeffgbutler** [comment]
Can you provide any details?

**Comment by fanhualei** [comment]
1：add <property name="prefix" value="wu_"/>, wil print Exception org.mybatis.generator.exception.XMLParserException: XML Parser Error on line 59  

2:add <domainObjectRenamingRule searchString="wk_" />, domainObjectRenamingRule Do not work


next si  my config 

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration
        PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
        "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">

<generatorConfiguration>

    <classPathEntry location="/home/fan/IdeaProjects/wukong-framework/wukong-generator/src/main/resources/mysql-connector-java-5.1.45-bin.jar" />


    <context id="wukong-generator" targetRuntime="MyBatis3DynamicSql">

        <plugin type="org.mybatis.generator.plugins.ToStringPlugin"/>
        <plugin type="com.wukong.generator.plugins.WukongPlugin"/>

        <commentGenerator>
            <property name="suppressAllComments" value="true" />
            <property name="suppressDate" value="true" />
        </commentGenerator>


        <property name="prefix" value="wu_"/>
        <property name="ignores" value=""/>


        
        <jdbcConnection driverClass="com.mysql.jdbc.Driver"
                        connectionURL="jdbc:mysql://127.0.0.1:3306/wukong_read?useSSL=false"
                        userId="root"
                        password="rootmysql">
        </jdbcConnection>

        <javaTypeResolver >
            <property name="forceBigDecimals" value="false" />
        </javaTypeResolver>

        
        <javaModelGenerator targetPackage="com.wukong.examples.entity" targetProject="log">
            <property name="enableSubPackages" value="true" />
            <property name="trimStrings" value="true" />
        </javaModelGenerator>

        
        <sqlMapGenerator targetPackage="com.wukong.examples.mapper"  targetProject="log">
            <property name="enableSubPackages" value="true" />
        </sqlMapGenerator>

        
        <javaClientGenerator type="XMLMAPPER" targetPackage="com.wukong.examples.dao"  targetProject="log">
            <property name="enableSubPackages" value="true" />
        </javaClientGenerator>


        
        <table tableName="wk_order" >
            <generatedKey column="order_id" sqlStatement="Mysql" identity="true"/>
            <domainObjectRenamingRule searchString="wk_" />
        </table>
    </context>
</generatorConfiguration>

**Comment by jeffgbutler** [comment]
Your `<property>` tags are in the wrong place in the `<context>` - that is probably causing the parse error.

You might want to try `<domainObjectRenamingRule searchString="^wk_" />`

**Comment by jeffgbutler** [comment]
No response
