### ISSUE TITLE
1.3.6 version,how to resolve nullvalue

### ISSUE THREAD

**Issue by Liesport758** [mybatis/generator#329]
i use jdk8.code below,
List<Banner> banners=bannerMapper.selectByExample()
				.where(BannerDynamicSqlSupport.name,isLike(vo.getName()))
				.orderBy(BannerDynamicSqlSupport.createAt.descending())
				.build().execute();
if vo.getName if null ,this condition don't use,how to realize?

**Comment by jeffgbutler** [comment]
This is an issue/question for https://github.com/mybatis/mybatis-dynamic-sql.

What would you want to happen in this case - all rows returned?

**Comment by Liesport758** [comment]
maybe .just like use mapper.xml

**Comment by jeffgbutler** [comment]
Closing as this is for MyBatis Dynamic SQL.  I've been thinking about this a bit and it is difficult to come up with a consistent strategy for optional criteria.
