### ISSUE TITLE
Use relative path for  mysql-connector-java-{version}.jar

### ISSUE THREAD

**Issue by qintianjie** [mybatis/generator#331]
MBG use absolute path to config  mysql-connector-java-{version}.jar which is not easy for multi engineer team, I think the start desire is let only one change the model & mapper.

I have update   org.mybatis.generator.config.xml.MyBatisGeneratorConfigurationParser.java to have relate path to the jar.

Please confirm whether can merge to the source to make team engineer more convenient.

Thanks.

Some example:
mysql-connector-java.jar  =====> src/main/resources/mysql-connector-java.jar
./mysql-connector-java.jar  =====> project_dir/mysql-connector-java.jar  // mvn run dir
/path/to/mysql-connector-java.jar  =====>  absolute path

[MyBatisGeneratorConfigurationParser.txt](https://github.com/mybatis/generator/files/1809586/MyBatisGeneratorConfigurationParser.txt)

**Comment by qintianjie** [comment]
modify version is  1.3.7-SNAPSHOT

**Comment by jeffgbutler** [comment]
Thank you for your contribution!  Could you make this into a pull request so we could see what you've changed?

I looked at it enough to ask that you remove the System.out.println statement.  Also, please remove the tabs and use 4 spaces for indent.

**Comment by jeffgbutler** [comment]
I also commented on your pull request. The `<classPathEntry>` element will already accept a relative path and it is resolved relative to user.dir. So I don't think any change is needed.
