### ISSUE TITLE
double "." in xml file cause by StringUtility.java class.

### ISSUE THREAD

**Issue by SBLiuEason** [mybatis/generator#334]
im chinese,so English is poor.in ur project ,directory:\internal\util\StringUtility line 49,u can remove code "else if(sb.length > 0){...}",this code will add another separate "." in mapper xml,cause double separate "." in mapper xml.plz deal it,thx.

**Comment by jeffgbutler** [comment]
Are you using MySQL?  This usually happens when you've specified a schema in your configuration - MySQL doesn't properly support schema.

Please read this page about how to configure the generator for MySQL: http://www.mybatis.org/generator/usage/mysql.html

**Comment by SBLiuEason** [comment]
thx a lot,i dont know schema configuration before.I think I should read document in detail.its a long way.
