### ISSUE TITLE
how to reset mapper class method name;

### ISSUE THREAD

**Issue by MisterChangRay** [mybatis/generator#335]
i want change method name and class name; 
 long countByExample(RolePermissionMapQuery example);
to
 long countByQuery(RolePermissionMapQuery example);

,,,,,,
org.mybatis.generator.plugins.RenameExampleClassPlugin
this plugin not support change methods name;

**Comment by jeffgbutler** [comment]
1. In you plugin, override the `initialized` method
2. On the `introspectedTable`, call the `setCountByExampleStatementId` method with any name you want

**Comment by MisterChangRay** [comment]
thanks，i've already solved it

**Comment by Cavva79** [comment]
@MisterChangRay how have you solved?
