### ISSUE TITLE
Is nested class supported?

### ISSUE THREAD

**Issue by reAsOn2010** [mybatis/generator#337]
```
            <columnOverride column="status"
                            typeHandler="org.apache.ibatis.type.EnumOrdinalTypeHandler"
                            javaType="cn.patest.core.SubmissionModelProtos$SubmissionStatus"/>
```
My generator config is like above, but `cn.patest.core.SubmissionModelProtos$SubmissionStatus` is an nested class. Then the generated java code says

```
import cn.patest.core.SubmissionModelProtos$SubmissionStatus
```

It seems that generator cannot handle this fully qualified class name properly, or am I missing something in configuration ?

**Comment by jeffgbutler** [comment]
Nested classes aren't supported.
