### ISSUE TITLE
why the generator generate selectByExample method have more information？

### ISSUE THREAD

**Issue by SuperDubbo** [mybatis/generator#338]
hi ,why the generator generate selectByExample method have more infomation. like this,"false' as QUERYID,"

![qq 20180406113428](https://user-images.githubusercontent.com/20811216/38402385-87848ddc-398e-11e8-9475-4cb125508037.png)

**Comment by jeffgbutler** [comment]
You must have `selectByExampleQueryId="false"` in your configuration.  Just remove it from the configuration and re-generate.

**Comment by SuperDubbo** [comment]
@jeffgbutler If i have selectByExampleQueryId="false" in my configuration,and re-generate.But it does't work.i use mysql version is 5.6.37,And use mysql-connector-java-5.1.35 Driver.My configuration is like this:
		<table tableName="account_info" domainObjectName="AccountInfo" enableCountByExample="false" enableUpdateByExample="false" enableDeleteByExample="true" enableSelectByExample="true" selectByExampleQueryId="false">

**Comment by SuperDubbo** [comment]
<table tableName="account_info" domainObjectName="AccountInfo" enableCountByExample="false" enableUpdateByExample="false" enableDeleteByExample="true" enableSelectByExample="true" selectByExampleQueryId="false">

**Comment by jeffgbutler** [comment]
Remove it completely:

```xml
<table tableName="account_info" domainObjectName="AccountInfo" enableCountByExample="false"
    enableUpdateByExample="false" enableDeleteByExample="true" enableSelectByExample="true">
```

**Comment by SuperDubbo** [comment]
@jeffgbutler I have remve it completely.But it does not work.
<table tableName="account_info" domainObjectName="AccountInfo" enableCountByExample="false"
    enableUpdateByExample="false" enableDeleteByExample="true" enableSelectByExample="true">

**Comment by SuperDubbo** [comment]
<table tableName="account_info" domainObjectName="AccountInfo" enableCountByExample="false"
    enableUpdateByExample="false" enableDeleteByExample="true" enableSelectByExample="true">

**Comment by jeffgbutler** [comment]
selectByExampleQueryId adds what you are complaining about in the selectByExample method.  That's the connection.

Removing selectByExampleQueryId and running the generator again should generate a new method without the queryid.  It looks like you might have comments turned off, so the code merger won't work.  Make sure to delete the old stuff before running the generator again.

**Comment by SuperDubbo** [comment]
Sorry,It's my carelessness,I run the generator again.And it works,I solved it.Thank guy! @jeffgbutler

**Comment by SuperDubbo** [comment]
And <code>selectByExampleQueryId="false"</code> in  configuration effect different from remove it from the configuration. I think this may confuse the generator users.Why not Enhanced the generator,and make the effect become the same? My English is very poor, My English is very poor, I do not know if you understand my ideas, thank you again!
