### ISSUE TITLE
How can I get the file which named mybatis-generator-config_1_0.dtd

### ISSUE THREAD

**Issue by neikochan** [mybatis/generator#340]
Something help！
         When I use this url to download the file,but it does't work,what can i do for next，brother？you can see what the troubble I‘ve maken through the image’s url
(https://user-images.githubusercontent.com/35319432/38780866-97eaa67e-410f-11e8-9209-0687511640a0.png)

How can I get the file which named mybatis-generator-config_1_0.dtd
   http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd

**Comment by jeffgbutler** [comment]
I assume you are being blocked by some firewall.  Here's a link the file in source:

https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/main/resources/org/mybatis/generator/config/xml/mybatis-generator-config_1_0.dtd
