### ISSUE TITLE
Can you provider a function or configuration node that generator can generate examples and models in different directory?

### ISSUE THREAD

**Issue by tbwork** [mybatis/generator#343]
This is critical in Dubbo-based micro-service architecture system.

**Comment by jeffgbutler** [comment]
You can do this with a plugin.  Look at this plugin for a good starting point:

https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/main/java/org/mybatis/generator/plugins/RenameExampleClassPlugin.java

**Comment by tbwork** [comment]
I've enhanced mybatis-generator by adding a javaExampleGenerator node to support the settings of example files. How about that I pull a request to you?

**Comment by jeffgbutler** [comment]
Do you mean that you've changed the XML configuration for this?  If so, then I am not interested in making that change since it can be accomplished with a very simple plugin.

If you mean that you have a plugin you would like to share, then feel free to add a link to your project here: https://github.com/mybatis/generator/wiki/Third-Party-Tools

**Comment by tbwork** [comment]
@jeffgbutler Yes, writing a plugin can be a selection but maybe not the best choice. Why do you put the two different things (model and example) together at the beginning of designing the mybatis-generator? Many recruitment ask me this question.

**Comment by jeffgbutler** [comment]
@tbwork I have no idea why recruiters would ask that question - it seems like a meaningless question to me.

One of my goals in the generator is to make it relatively easy to change how the code is generated if you don't like the defaults. This is a case where you can use an existing mechanism to change the defaults, so I see no need to make the configuration XML even more complex than it already is.

In the new runtime for MyBatis Dynamic SQL there is no longer an example class at all, so this will become irrelevant for the future. I suppose that would be my answer to a recruiter if asked - the example class was necessary for the old style of generated code, but is no longer necessary and should be avoided for new projects.

**Comment by tbwork** [comment]
@jeffgbutler OK, sounds convincible.  Your land, you decide. :)
