### ISSUE TITLE
Context defaultModelType extend?

### ISSUE THREAD

**Issue by liyiorg** [mybatis/generator#344]
Context defaultModelType like  "flat"
```xml
<context id="PTables" targetRuntime="MyBatis3" defaultModelType="flat"> </context >
```
But, when the table has multiple primary key,  will generate a primary key class , another class that holds any columns in the table

**Comment by jeffgbutler** [comment]
Can you provide more detail?  This is working in the tests, so either you've found a new bug, or something is misconfigured.

**Comment by liyiorg** [comment]
Oh, is not bug.  I want generate custom model.  The table has one or multiple primary key ,multiple blob columns and other columns.   when the table  has one primary key, just generate all columns in one class . but when the table has multiple primary key , I want generate a primary key class , another class that holds any columns in the table .   Can you help me,  What should I do？  Thanks !

**Comment by jeffgbutler** [comment]
Try this...

```xml
<context id="PTables" targetRuntime="MyBatis3" defaultModelType="conditional"> </context >
```
