### ISSUE TITLE
it don't support yml

### ISSUE THREAD

**Issue by Liesport758** [mybatis/generator#345]
in generatorConfig.xml,for example
![image](https://user-images.githubusercontent.com/10843358/38973543-f509deee-43d8-11e8-9326-22b17c1e4380.png), if it is yml file,i cann't get the  properties to use {}

**Comment by jeffgbutler** [comment]
You are correct.  YML is not supported.  Use a regular Java properties file.

**Comment by kid1412621** [comment]
@jeffgbutler Is possible to config without XML file, generatorConfig.xml ? replace with properties or json or yaml or somthing/
