### ISSUE TITLE
Primary Key Information Missing with MySql

### ISSUE THREAD

**Issue by otterslide** [mybatis/generator#349]
I've used the generator before and it has worked perfectly with my current setup.

I recently upgraded Eclipse and re-installed the generator, now I am getting this error:
"WARNING: Cannot obtain primary key information from the database, generated objects may be incomplete"
I am using Eclipse Oxygen and Generator 1.3.6.
I downloaded the latest Mysql Connector 5.1.46, but it's still not working to get the keys. 

Any ideas what I can do to get the key information? It really is missing in the XML files.
Thanks.

**Comment by otterslide** [comment]
I was able to set up a local update site to 1.3.5 , and install that version which has the "Generate Mybatis Artifacts" right-click menu item.
When it that way it works fine. When I run with Run As - > Mybatis Generator, it has problems with the primary keys still, but at least I have a way to make it work for now.

**Comment by jeffgbutler** [comment]
Some questions:

1. Are you using the same version of Connector/J in both cases?
2. When using "Run As -> MyBatis Generator", are you referencing Connector/J from a `<classPathEntry>` in your configuration, or are you adding Connector/J to the launch configuration classpath?
3. Any other difference between what's working and what isn't?

**Comment by otterslide** [comment]
Run As was overriding my classpathEntry config line in the XML and was
using. 6.0.6 from the Maven classpath. So with Connector 6.0.6 it doesn't
work correctly.
I see there are newer versions now 8+, I will give it a try later.
Thanks!

**Comment by jeffgbutler** [comment]
Assuming this was a driver bug.

**Comment by alphatan** [comment]
# A Note

I was led here by the same problem. Then, hope a note would help the other victims.

# Cause

This problem is caused by the catalog setting of `mysql` driver.

# Solution

1. Append the `nullCatalogMeansCurrent=true` to the `connectionUrl` property
or
1. set the `catalog`  attribute in `<table>` element explicitly.

# Example

```xml
<jdbcConnection
    connectionURL="jdbc:mysql://127.0.0.1:3306/test?useSSL=false&amp;nullCatalogMeansCurrent=true"
    driverClass="com.mysql.cj.jdbc.Driver"
    password=""
    userId="root" />
```

```xml
<table catalog="test" tableName="blog" />
```
