### ISSUE TITLE
About org.mybatis.generator.internal.db.DatabaseIntrospector#getColumns

### ISSUE THREAD

**Issue by liubo-tech** [mybatis/generator#358]
In the line 509,the code is 
ResultSet rs = databaseMetaData.getColumns(localCatalog, localSchema, localTableName, "%");

I use the mysql-connector-java-8.0.11.jar,and the driver class is com.mysql.cj.jdbc.Driver.
I don't think you can use localCatalog, localCatalog is the table config's attribute.
that can get all the databases,but i want to get the database in the connectionURL,
i have to add the "nullCatalogMeansCurrent=true" in the connectionURL.

**Comment by jeffgbutler** [comment]
MySQL is inconsistent in their usage of catalog and schema. You have found the workaround.

This is documented on the MySQL usage page here: http://www.mybatis.org/generator/usage/mysql.html

**Comment by liubo-tech** [comment]
Thanks.I got it
