### ISSUE TITLE
support page query?

### ISSUE THREAD

**Issue by flaming-archer** [mybatis/generator#360]
I think this generator should support page query.like limit x,y。

**Comment by jeffgbutler** [comment]
The MyBatisDynamicSQL runtime has some support for making paging queries. You can look at the example code to understand how to make it work: https://github.com/mybatis/mybatis-dynamic-sql/tree/master/src/test/java/examples/paging

**Comment by KING754** [comment]
why not  support generate the about limit code in  the mybatis-generator-core-*.jar.
feel some body need the codes.
