### ISSUE TITLE
mybatis-generator-maven-plugin doesn't support resource folder named ‘resource’，It must be ‘resources

### ISSUE THREAD

**Issue by bluehr** [mybatis/generator#361]
My project's resource folder name is ‘**resource**’ then i config it in <configurationFile>tab 
![image](https://user-images.githubusercontent.com/25925297/41136327-59d0300c-6b08-11e8-8fa0-f1b5490a9f71.png)
 But I found it still wrong
![image](https://user-images.githubusercontent.com/25925297/41136496-204944c6-6b09-11e8-920a-c0c64867dbba.png)
 I use ‘mybatis-generator:generate -X’command to see the detail msg as follow
 The 'configurationFile' is work 
![image](https://user-images.githubusercontent.com/25925297/41136564-64cf257a-6b09-11e8-99c5-177d5116c5c8.png)
 it still report can't find default setting 'src\main\**resources**'
![image](https://user-images.githubusercontent.com/25925297/41136675-e9e55040-6b09-11e8-9a23-fbf6024c6ece.png)

 The only solution I found to this problem was to modify the resource folder named ‘**reources**’

**Comment by jeffgbutler** [comment]
Have you configured your POM with this non-standard folder structure? You should have something like this:

```xml
<resources>
  <resource>
    <directory>${basedir}/src/main/resource</directory>
  <resource>
</resources>
```

**Comment by jeffgbutler** [comment]
No response
