### ISSUE TITLE
Is there any elegant way to access the name of properties of XXXDynamicSqlSupport when customizing a plugin?

### ISSUE THREAD

**Issue by ElliotMok** [mybatis/generator#364]
@jeffgbutler 
Since the 1.1.0 version of mybatis-dynamic-sql has added the ability to modify SQL after generation which made some extensions such as paginated feature that has been demonstrated in the [test case](https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/paging/LimitAndOffsetTest.java) possible, it's spontaneously for me to try to using mybatis-generator(MBG) plugin to generate those code automatically.

But it seems inevitable that the the name of properties of XXXDynamicSqlSupport would be referenced in the mapper method and I have no idea that is there any elegant way to access the name of properties of XXXDynamicSqlSupport when customizing a plugin.

**Comment by jeffgbutler** [comment]
I've added mew methods to the IntrospectedTable class to allow you to access/change the name in plugins in #348. Is this what you're looking for? It's not released yet, but will be soon.

**Comment by jeffgbutler** [comment]
No response.
