### ISSUE TITLE
Is there a switch control <sql> label generator?

### ISSUE THREAD

**Issue by zhengzwe** [mybatis/generator#380]
![image](https://user-images.githubusercontent.com/23271003/42669013-0db23686-8686-11e8-887a-944d9da6f729.png)
![image](https://user-images.githubusercontent.com/23271003/42669038-29716f90-8686-11e8-9e8a-b784e435ddeb.png)
不想生成<sql> 标签，可以配置不生成么

**Comment by jeffgbutler** [comment]
I don't understand the question. You can change the column list ids in a plugin - is that what you are asking?

**Comment by jeffgbutler** [comment]
No response.
