### ISSUE TITLE
Primary Key Information Missing with MySql + wrong SQL generation

### ISSUE THREAD

**Issue by sgdesmet** [mybatis/generator#385]
mybatis generator version: 1.3.7
mysql connector version: 8.0.11

During generation the following error is logged:

    [WARNING] Cannot obtain primary key information from the database, generated objects may be incomplete

This seems to be different from #349, see below:

This appears to occur when the following conditions are met:
- not specifying the `catalog` for a `table` in your `generatorConfiguration` 
- the mysql instance has multiple databases. 

When calling the `DataBaseMetaData.getPrimaryKeys(...)` implementation by the mysql connector without supplying a catalog, the connector will attempt to retrieve the primary key info for the tablename in each existing database/catalog. This will result in an `SqlException` when the table is not present in all of the other catalogs. Subsequently, the ` Cannot obtain primary key...` exception is logged by `DatabaseIntrospector`.

**However**, when adding the catalog attribute to `table`, the SQL generated is now wrong, as it will include two dots to separate catalog and table name.
E.g.:

        @Delete({
            "delete from demodatabase..demotable",
             "where id = #{id,jdbcType=BIGINT}"
        })

**Comment by jeffgbutler** [comment]
My guidance with MySQL is to not use schema or catalog in the table configuration and specify the schema or database on the JDBC URL: http://www.mybatis.org/generator/usage/mysql.html

If this doesn't work for you, you could specify the catalog as you have here and then use the table property "ignoreQualifiersAtRuntime" to keep the schema/catalog/database out of the generated SQL.

I haven't used MySQL in quite a while so something might have changed. If you find information that should be added to the page above, please feel free to send in a pull request.

**Comment by sgdesmet** [comment]
That is indeed the advice I followed, my JDBC URL looks like `jdbc:mysql://localhost:3306/demodatabase`. Nevertheless, in that case the schema or catalog is not passed to `DataBaseMetaData.getPrimaryKeys(...)` so the driver still tries to get the primary key info for the specified table in all databases. This is probably more of an issue with the MySQL driver itself, so apologies for raising an issue here.

I can work around it by specifying the catalog and setting the property "ignoreQualifiersAtRuntime" to true, thank you!

**Comment by sgdesmet** [comment]
Update, seems like I didn't read the mysql page carefully enough, I was missing `<property name="nullCatalogMeansCurrent" value="true" />` in my jdbcConnection. 
Adding this ensures correct behaviour, my apologies again.
