### ISSUE TITLE
Invalid XXXDynamicSqlSupport class generated with MyBatis3DynamicSQL runtime

### ISSUE THREAD

**Issue by sgdesmet** [mybatis/generator#387]
When  you override the `domainObjectName` with a name that also happens to be a column name for that table, the resulting 'XXXDynamicSqlSupport' will have two fields with the same name, so compilation will fail.

For example, suppose I have e table `translations` which also has a column `translation` (amongst others) but I would like the name of the class to be `Translation` instead of `Translations`, then the resulting `TranslationDynamicSqlSupport` will have two translation fields:

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2018-08-01T14:04:25.342+02:00", comments="Source Table: translations")
    public static final Translation translation = new Translation();

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2018-08-01T14:04:25.342+02:00", comments="Source field: translations.translation")
    public static final SqlColumn<String> translation = translation.translation;

**Comment by jeffgbutler** [comment]
What do you think the generator should generate in a case like this? My initial thought is to simply not generate the column shortcut (the second field in your example).

**Comment by sgdesmet** [comment]
That may be the best option indeed as you can just get the column via the table shortcut, but could that not be potentially confusing as to why a particular column shortcut is not present?

But the other options are perhaps a bit verbose as well: 

    public static final SqlColumn<String> translationTranslation = translation.translation;

is maybe not great?

Unless you pre- or suffix the table shortcut? E.g.:

    public static final Translation translationTable = new Translation();
    
    public static final SqlColumn<String> translation = translationTable.translation;

**Comment by sgdesmet** [comment]
Indeed none are great, so a comment might be the best option.
