### ISSUE TITLE
A bug on MySQL 8.0.11

### ISSUE THREAD

**Issue by Aerothief** [mybatis/generator#388]
mybatis generator 1.3.7 + jdbc 8.0.11
It will always make file for mysql.user whatever I config(video.user);

**Comment by jeffgbutler** [comment]
Please read this page for MySQL usage notes: http://www.mybatis.org/generator/usage/mysql.html

You probably need to set the `nullCatalogMeansCurrent` property.

**Comment by jeffgbutler** [comment]
No response
