### ISSUE TITLE
Could not get MySql Table's comment from IntrospectedTable

### ISSUE THREAD

**Issue by CenJIl** [mybatis/generator#390]
Sometime we need to add an Annotation like this @ApiModel(value="{table.comment}") ,it seems you had also noticed that. introspectedTable.getRemarks() is a good idea,but it doesn't work on MySql.
Hope it works.
` if ("MYSQL".equals(databaseProductName)) {
                Statement stmt = this.databaseMetaData.getConnection().createStatement();
                ResultSet rs = stmt.executeQuery(
      new StringBuilder().append("SHOW TABLE STATUS LIKE 
 '").append(atn.getTableName()).append("'").toString());
                while (rs.next())
                    table.setRemark(rs.getString("COMMENT"));
                closeResultSet(rs);
                stmt.close();
            }`

**Comment by jeffgbutler** [comment]
Try adding `useInformationSchema=true` to your JDBC URL - this is required to obtain database comments in MySQL.
