### ISSUE TITLE
can you add a configuration to set the date to the LocalDate which in java1.8？

### ISSUE THREAD

**Issue by deadmanno3** [mybatis/generator#391]

**Comment by jeffgbutler** [comment]
There is a property on the `<javaTypeResolver>` that will force JSR-310 types:

http://www.mybatis.org/generator/configreference/javaTypeResolver.html

**Comment by deadmanno3** [comment]
oh
I see,thank you!

Jeff Butler <notifications@github.com> 于2018年8月8日周三 下午8:05写道：
