### ISSUE TITLE
how to self join

### ISSUE THREAD

**Issue by ether007** [mybatis/generator#392]
when self join
`
 SelectStatementProvider q = select(id, name)
                .from(UserDynamicSqlSupport.user,"u1")
                .leftJoin(UserDynamicSqlSupport.user2,"u2").on(UserDynamicSqlSupport.user2.pid,equalTo(id))
                .where(id, isGreaterThan(1))
                .build()
                .render(RenderingStrategy.MYBATIS3);
`
generator sql is
`
select u2.id, u2.name from t_user u2 left join t_user u2 on u2.id = u2.pid where u2.id > ?
`

**Comment by jeffgbutler** [comment]
This should be a report for MyBatis Dynamic SQL: https://github.com/mybatis/mybatis-dynamic-sql

**Comment by jeffgbutler** [comment]
Closed in favor of https://github.com/mybatis/mybatis-dynamic-sql/issues/54
