### ISSUE TITLE
MBG not support mutiple place holder on property

### ISSUE THREAD

**Issue by girllee** [mybatis/generator#395]
### When using ${aa.bb}.${cc.dd}.${ee.ff} on one property, MBG parse the generatorConfig.xml will failed.
e.g.
**generator.property**
`gen.code.package=org.girllee.boot.dao

gen.code.domain=domain

gen.code.mapper=mapper

gen.code.db=pg`

**partial generatorConfig.xml**
`<javaModelGenerator targetPackage="${gen.code.package}.${gen.code.domain}.${gen.code.db}" targetProject="src/main/java">
			<property name="enableSubPackages" value="true"/>
			<property name="trimStrings" value="true"/>
		</javaModelGenerator>
		<sqlMapGenerator targetPackage="${gen.code.package}.${gen.code.mapper}.${gen.code.db}" targetProject="src/main/java">
			<property name="enableSubPackages" value="true"/>
		</sqlMapGenerator>
		<javaClientGenerator type="XMLMAPPER" targetPackage="${gen.code.package}.${gen.code.mapper}.${gen.code.db}"
							 targetProject="src/main/java">
			<property name="enableSubPackages" value="true"/>
		</javaClientGenerator>`

I debug into the MyBatisGeneratorConfigurationParser.java  and found that the start index and end index calculate wrong value when a newString generated ( line 733 734) if a place holder's length bigger than it's value's length.

**original code**
 ` start = newString.indexOf(OPEN, end);  
 end = newString.indexOf(CLOSE, end);`

**Comment by jeffgbutler** [comment]
This is fixed in #394
