### ISSUE TITLE
integration of springboot and lombok

### ISSUE THREAD

**Issue by FJarvan** [mybatis/generator#396]
my project is based on springboot（multi-modules），how i can use mybatis-generator to integrate lombok

**Comment by jeffgbutler** [comment]
Please see the mybatis/spring-boot-starter project for information about Spring Boot integration: https://github.com/mybatis/spring-boot-starter

Someone has published a plugin for adding lombok annotations. You can see about that here: https://github.com/mybatis/generator/wiki/Third-Party-Tools
