### ISSUE TITLE
mybatis generator generate failed: Cannot instantiate object of type SPRING

### ISSUE THREAD

**Issue by jast90** [mybatis/generator#40]
Failed to execute goal org.mybatis.generator:mybatis-generator-maven-plugin:1.3.2:generate (default-cli) on project mybatis-generator-sample: Execution default-cli of goal org.mybatis.generator:mybatis-generator-maven-plugin:1.3.2:generate failed: Cannot instantiate object of type SPRING -> [Help 1]

**Comment by wlei-fx** [comment]
hi, did you resolve this problem?

**Comment by jast90** [comment]
@wlei-fx 好像是配置错了。
