### ISSUE TITLE
How can I not generate insertSelective, updateByPrimaryKey, but only generate insert, updateByPrimaryKeySelective

### ISSUE THREAD

**Issue by imic07** [mybatis/generator#405]
In generatorConfig.xml, can configure whether to generate insert, insertSelective, updateByPrimaryKey, updateByPrimaryKeySelective by enableInsert="true" enableUpdateByPrimaryKey="true". How can I not generate insertSelective, updateByPrimaryKey these two methods. Because they are basically useless.

**Comment by jeffgbutler** [comment]
You can write a plugin to do fine grained control over what gets generated.
