### ISSUE TITLE
How to generate multiple different java beans

### ISSUE THREAD

**Issue by zhengjieyuan** [mybatis/generator#409]
I want to generate vo, dto, model files in the project at the same time, how to expand?
tks

**Comment by jeffgbutler** [comment]
You can write a plugin to generate additional objects.

I will say that the generator is basically making DTO type of objects already. They are not really model objects - unless you consider the "anemic domain model" acceptable. I doubt you could auto generate a truly OO domain model from just database table definitions.

 You can also "sort of" make value objects by telling the generator to generate immutable objects - but these will not really fit the strict definition of a value object.

My advice is to consider the generated objects as low level constructs in your application. I would recommend building an actual domain model to match your business problem - and it would be hard to have something like that created by a code generator.

**Comment by zhengjieyuan** [comment]
thanks!
