### ISSUE TITLE
tinyint

### ISSUE THREAD

**Issue by lw5946** [mybatis/generator#411]
the mysql Database fields are tinyint with length 1 , but converted to Boolean

**Comment by jeffgbutler** [comment]
By default, the generator maps a TINYINT to a Byte. The JDBC driver must be reporting a different datatype for these fields. Please share a sample table definition and I'll take a look.

**Comment by jeffgbutler** [comment]
No response

**Comment by neerajhiretual** [comment]
I think for anyone facing similar issue, [here](https://github.com/metabase/metabase/issues/3506) is more detailed discussion and how to overcome such issue. Link not related to mybatis but JDBC issue.
