### ISSUE TITLE
Configurable columns to include in toString plugin

### ISSUE THREAD

**Issue by sgdesmet** [mybatis/generator#413]
It would be convenient if the `ToStringPlugin` could be configured to include only certain properties or just the primary keys. Sometimes sensitive data such as access tokens is contained in a table, and using the ToStringPlugin could lead to inadvertently including this information in logs somewhere.

**Comment by jeffgbutler** [comment]
The plugin is included as an example. It would be easy to create a plugin based on the included plugin if you still need this capability.
