### ISSUE TITLE
how to use Generator to  generate geometry 

### ISSUE THREAD

**Issue by ztelur** [mybatis/generator#418]
below is  the table definition, generator doesn't work fine with geomerty 

```CREATE TABLE MAP_ELEMENT
(
    id bigint PRIMARY KEY AUTO_INCREMENT,
    name varchar(100) NOT NULL,
    url varchar (255),
    type tinyint,
    geom geometry NOT NULL,
    content_Id bigint NOT NULL,
    SPATIAL KEY `i_geomidx` (`geom`)
);

**Comment by jeffgbutler** [comment]
I assume the generator created something like `private Object geom` - is that correct?

Since geometry is not a standard JDBC type, you will need to use a `<columnOverride>` to tell the generator what to generate - and you will likely need to write a type handler for MyBatis as well.

**Comment by jeffgbutler** [comment]
No response
