### ISSUE TITLE
Multiple identical tables for different databases

### ISSUE THREAD

**Issue by codefalse** [mybatis/generator#419]
```xml
<dependency>
   <groupId>org.mybatis.generator</groupId>
   <artifactId>mybatis-generator-core</artifactId>
   <version>1.3.7</version>
</dependency>
<dependency>
  <groupId>mysql</groupId>
  <artifactId>mysql-connector-java</artifactId>
  <version>8.0.12</version>
</dependency>
```
Multiple databases have table manager
Generate a table manager in a database, but all table manager will generate.

**Comment by jeffgbutler** [comment]
I don't understand. Please provide more details.

**Comment by codefalse** [comment]
example: 
-schemas:
--schema1:
---manager
---other table
--schema2:
---manager
They all have a table(manager), In db schema1 and schema2. I want to generate schema1.manager, but all database tables(manager) will be generated.
In `mysql-connector-java5.1.47`  or lower version, no problem.
There is a problem with the latest version
