### ISSUE TITLE
how to add @Alias for generated model?

### ISSUE THREAD

**Issue by Alwayswithme** [mybatis/generator#42]
I want generator auto add @Alias annotation in the generated model
```java
@Alias("user")
public class User {
  // omit ...
}
```

**Comment by mahiarmody** [comment]
Have you taken a look at the MyBatis Generator third party plugins? Here's the link:
https://github.com/mybatis/generator/wiki/Third-Party-Plugins

Particularly, take a look at the Jaxb annotations plugin. The link is:
https://github.com/mahiarmody/Mbg-Plugin-Jaxb/releases/tag/v1.0.0

The Jaxb annotations plugin will not generate the Spring annotations like @alias, but can generate many of the standard built-in Java annotations. For usage and examples, see the Jaxb annotations plugin wiki page. Link is:
https://github.com/mahiarmody/Mbg-Plugin-Jaxb/wiki

See if this plugin helps you.

**Comment by jeffgbutler** [comment]
I agree with @mahiarmody .  However, if the jaxb plugin is more than you are looking for, then you can write your own simple plugin.  Take a look at the Serializable plugin here for a good example:

https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/main/java/org/mybatis/generator/plugins/SerializablePlugin.java

**Comment by Alwayswithme** [comment]
@jeffgbutler  @mahiarmody 
That's all I need, many thanks for your kind help. :)
```java
public class TypeAliasPlugin extends PluginAdapter {

    private FullyQualifiedJavaType typeAlias;

    public TypeAliasPlugin() {
        super();
        typeAlias = new FullyQualifiedJavaType("org.apache.ibatis.type.Alias");
    }

    public boolean validate(List<String> warnings) {
        return true;
    }


    @Override
    public boolean modelBaseRecordClassGenerated(TopLevelClass topLevelClass,
                                                 IntrospectedTable introspectedTable) {
        addTypeAlias(topLevelClass, introspectedTable);
        return true;
    }

    private void addTypeAlias(TopLevelClass topLevelClass, IntrospectedTable introspectedTable) {
        topLevelClass.addImportedType(typeAlias);

        TableConfiguration tableConfiguration = introspectedTable.getTableConfiguration();

        String domainObjectName = tableConfiguration.getDomainObjectName();
        String alias = domainObjectName == null ? tableConfiguration.getTableName() : domainObjectName;
        String aliasAnnotation = String.format("@Alias(\"%s\")", alias);
        topLevelClass.addAnnotation(aliasAnnotation);
    }
}
```

**Comment by CallMeXYZ** [comment]
@Alwayswithme how do u configure  `TypeAliasPlugin ` in `generatorConfig.xml` ? All I got is ClassNotFoundException~
