### ISSUE TITLE
DomainObjectRenamingRule add attribute CamelCase

### ISSUE THREAD

**Issue by leondryu** [mybatis/generator#420]
When using element DomainObjectRenamingRule, the model/mapper will not be CamelCase but FirstCharacterUppercase. However, i think it is quite common that using DomainObjectRenamingRule to eliminate some 'prefix' from the table name, but when you user it the model/mapper will not be CamelCase, that was very inconvenient. 
Could you add an attribute such as KeepCamelCase in DomainObjectRenamingRule so that we can use DomainObjectRenamingRule and keep the model/mapper CamelCase?

**Comment by jeffgbutler** [comment]
Duplicate of #381
