### ISSUE TITLE
How to keep Java model name using Camel Case in V1.3.7?

### ISSUE THREAD

**Issue by diguage** [mybatis/generator#421]
How to keep Java model name using Camel Case in 1.3.7?

`table` tag configuration is as following:

```xml
<table tableName="%">
    <generatedKey column="id" sqlStatement="Mysql" identity="true" type="post"/>
    <domainObjectRenamingRule searchString="^T" replaceString=""/>
</table>
```

**Comment by jeffgbutler** [comment]
This is a duplicate of #381 (fixed, but not released yet).

**Comment by diguage** [comment]
How to configure it?

**Comment by jeffgbutler** [comment]
There is a bug in 1.3.7. If you use the 1.4.0-SNAPSHOT version it should work. You can read about configuring maven to access the snapshot releases here: https://github.com/mybatis/mybatis-3/wiki/Maven

**Comment by diguage** [comment]
@jeffgbutler 
Thanks. I thought it add new configuration option. Sorry.
