### ISSUE TITLE
the code style

### ISSUE THREAD

**Issue by linlinjava** [mybatis/generator#425]
I use the generated code in IDEA, and then I want to use `reformat code` tool from IDEA to reformat all code of my project. However, the generated code from mybatis generator can not follow the default code style of IDEA. Thus, I'd like to take whether it could be a good feature to support code style configuration, at least for IDEA or Eclipse. Currently, I have to skip the package of generated code.

**Comment by jeffgbutler** [comment]
There is support for plugging in your own code formatter. I’ve also just recently rewritten and simplified the bundled code formatters for Java and XML. Hopefully it will be easier to start with the bundled formatters and change them to your liking.

I’m not an IntelliJ user so I don’t know what is default in that IDE. The code produced by the generator doesn’t match the Eclipse default either.

All that to say that you should be able to change the formatting to match your preference without too much work. But I don’t think we need to bundle anything else in the codebase.

**Comment by linlinjava** [comment]
ok， thank you.
