### ISSUE TITLE
What is the right way to use generated code

### ISSUE THREAD

**Issue by PaleNeutron** [mybatis/generator#427]
I have add some methods to the generated mapper interface, for example, a `delete all item in table` method.
Of course, implementation is written in the xml sql file.

However, my database structure changes frequently. So I have to generate code again and again and wish to get rid of keeping custom method in the interface.

It must be something wrong, but I do not know the correct code structure should be.

**Comment by jeffgbutler** [comment]
You can code your custom queries in separate XML files and interfaces if you wish.

Please ask further questions on the user mailing list: https://groups.google.com/forum/#!forum/mybatis-user
