### ISSUE TITLE
Add screenshots to eclipse marketplace

### ISSUE THREAD

**Issue by paulvi** [mybatis/generator#430]
Please add screenshots to https://marketplace.eclipse.org/content/mybatis-generator

**Comment by jeffgbutler** [comment]
There's not much of a UI for screen shots - it's mainly just a launch configuration and help. What would you suggest?

**Comment by paulvi** [comment]
OK, so it can be screenshot of context menu with item to select stressed,  
then next screen what would generated result can look like.
