### ISSUE TITLE
How can I write complex SQL statement having both `and` and `or`

### ISSUE THREAD

**Issue by PeichengLiu** [mybatis/generator#431]
[Example Class Usage Notes](http://www.mybatis.org/generator/generatedobjects/exampleClassUsage.html) gives some simple usages example. But I can not figure out a way, using the existing v1.3.7 API, to generate SQL statement like this:
```SQL
where field1 = 1 and field2 is null
     and (field3 = 9 or field3 is null)
```

**Comment by jeffgbutler** [comment]
You can do it if you think about your query like this:

```sql
where field1 = 1 and field2 is null and field3 = 9
      or (field1 = 1 and field2 is null and field3 is null) 
```

Not great, but that is the best you can do with the example classes. This limitation of the example classes is the main reason that I wrote the new library [MyBatis Dynamic SQL](http://www.mybatis.org/mybatis-dynamic-sql/docs/introduction.html). If you can switch to using code generated for the new library, then you can write your where clause exactly as you've specified.

**Comment by PeichengLiu** [comment]
Unfortunately, my target SQL statement would be more complex and dynamic than the specified one. Moments ago, I had a look at the [MyBatis Dynamic SQL](http://www.mybatis.org/mybatis-dynamic-sql/docs/introduction.html) library you mentioned above. It seems to expose a nice chaining API. So is it possible for me to use both of these two library together in one project? It's impossible for me to completely

> switch to using code generated for the new library

Anyway, thanks for your work!

**Comment by jeffgbutler** [comment]
Yes - you should be able to use both. You would need to add a new context in your generator configuration and generate two sets of code for the table (in different packages).

The "*ByExample" methods have all changed with the new runtime.  The other methods are exactly the same.

**Comment by PeichengLiu** [comment]
OK, thanks!
