### ISSUE TITLE
MyBatisGeneratorConfigurationParser parse properties file bug

### ISSUE THREAD

**Issue by 760374564** [mybatis/generator#433]
private String parsePropertyTokens(String string) {
        final String OPEN = "${"; //$NON-NLS-1$
        final String CLOSE = "}"; //$NON-NLS-1$
        String newString = string;
        if (newString != null) {
            int start = newString.indexOf(OPEN);
            int end = newString.indexOf(CLOSE);

            while (start > -1 && end > start) {
                String prepend = newString.substring(0, start);
                String append = newString.substring(end + CLOSE.length());
                String propName = newString.substring(start + OPEN.length(),
                        end);
                String propValue = resolveProperty(propName);
                if (propValue != null) {
                    newString = prepend + propValue + append;
                }
                start = newString.indexOf(OPEN, end);
                end = newString.indexOf(CLOSE, end);
            }
        }
        return newString;
    }
这个方法中 
    start = newString.indexOf(OPEN, end);
    end = newString.indexOf(CLOSE, end);

这两行代码中end值存在错误引用的问题，导致占位符解析失败。
     start = newString.indexOf(OPEN);
    end = newString.indexOf(CLOSE);
改成这样即可，及永远先处理第一个索引到的值并替换，这样不会出错，版本 1.3.7

**Comment by jeffgbutler** [comment]
This code has been completely rewritten in the current master branch based on pull request #394. Please check it out and let us know if you think there is still a problem. If you find an error, please add a failing test to this class: https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/test/java/org/mybatis/generator/config/xml/PropertyParserTest.java

**Comment by jeffgbutler** [comment]
No response
