### ISSUE TITLE
重大问题：MySQL数据库表中字段名与JavaBean属性名不一致

### ISSUE THREAD

**Issue by Baifujun** [mybatis/generator#434]
`在配置文件中写了property` name="useActualColumnNames" value="true"，但实际上字段名为Z_YL1的字段在JavaBean中生成的是z_YL1属性，而字段名为DELIVERY_HID字段在JavaBean中生成的就是DELIVERY_HID，这是什么BUG？国人帮忙解决一下。

**Comment by HeyuRise** [comment]
你翻译一下让外国友人看看多好，他们都很在意issue的

**Comment by HeyuRise** [comment]
### Translation of the above comment 
he add the property useActualColumnNames in table like 
``` 
    <table tableName="github" domainObjectName="Github">
        <property name="useActualColumnNames" value="true"/>
    </table>
``` 
and his mysql database table colums contains 

| colum | type |
|:-------------:|:-------------|
| Z_YL1 | varchar | 
| DELIVERY_HID | varchar |

the javaBean he generated suppose to like this 
``` 
    private String Z_YL1;

    private String DELIVERY_HID;
``` 
but the actual situation is like this
``` 
    private String z_YL1;

    private String DELIVERY_HID;
```

**Comment by jeffgbutler** [comment]
@HeyuRise thanks for the translation!

This is by design. There were issues with MyBatis with "JavaBeans" that have a single upper case letter at their start so even with `useActualColumnNames` we will change the case of properties like this.
