### ISSUE TITLE
Multiple tables will generate much duplicated code

### ISSUE THREAD

**Issue by riverrrflow** [mybatis/generator#438]
Hello, I found a problem using mybatis generator. Much duplicated code will generated when I hava multiple tables. like this:
![image](https://user-images.githubusercontent.com/43004603/50440081-85896e00-092f-11e9-9a75-000161b0a38b.png)
version:com.arenagod.gradle:mybatis-generator-plugin:1.3

**Comment by jeffgbutler** [comment]
Yes - this is true. If you will switch to the `MyBatis3DynamicSQL` runtime, there will be far less code generated and the generated code will be much more flexible.
