### ISSUE TITLE
Generator Fails When Table Name with substring of another table name exists.

### ISSUE THREAD

**Issue by rajaspatil** [mybatis/generator#44]
MyBatis Generator Fails For Following Condition.

My Database has table with Table Name CMNT_MAST_BRANCH.
I added new Table with CMNT_MAST_BRANCH_HIST.
Generator Generates domain, map and mapper for CMNT_MAST_BRANCH_HIST but
Fails for CMNT_MAST_BRANCH. For This it Tries To Use CMNT_MAST_BRANCH_HIST fields.

My Database is Firebird Classic 2.1, OS is KUbuntu 14.04, Eclipse Kepler.

I have Noticed This Bug earlier Too with Firebird SS 2.1, KUbuntu 12.04 eclipse Juno, Luna etc.etc.

**Comment by jeffgbutler** [comment]
I cannot reproduce this failure.  I generated tables with these exact names and things seemed to work OK.

Can you provide a failing unit test?

**Comment by rajaspatil** [comment]
Thanks For help extended,

Well, I can send you empty database and xml used to generate the code. 

Will it help in reproducing the issue ?

**Comment by jeffgbutler** [comment]
Please post the XML configuration  That might be enough.

**Comment by jeffgbutler** [comment]
No response.  Feel free to reopen if you can reproduce the issue in a unit test.
