### ISSUE TITLE
Turn the automatically generated insert map into dynamic

### ISSUE THREAD

**Issue by Snile826** [mybatis/generator#448]
excuse me.
I want to change the @Insert mapping of the automatically generated annotation mapping code to a dynamic mapping of each field.

such as
        "\<script>",
        "insert into table",
        "\<trim prefix='(' suffix=')' suffixOverrides=','>",
        "\<if test = 'field1!=null'> field1, \</if>",
        "\<if test = 'field2!=null'> field2,  \</if>",
        "\</trim>",
        "\<trim prefix='values (' suffix=')' suffixOverrides=','>",
        "\<if test = 'field1!=null'> #{field1,jdbcType=INTEGER},  \</if>",
        "\<if test = 'field2!=null'> #{field2,jdbcType=VARCHAR}, \</if>",
        "\</trim>",
        "\</script>"

I don't know what the fastest implementation is? Looking at the source code makes me a headache, can't find its generation logic.

thanks

**Comment by Snile826** [comment]
I want to reload the original auto-generated logic through the plugin.....
But after debugging, I still can’t figure it out.

**Comment by jeffgbutler** [comment]
This is exactly what is already generated for the insertSelective method.

Here's the code that does it: https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/main/java/org/mybatis/generator/codegen/mybatis3/xmlmapper/elements/InsertSelectiveElementGenerator.java

**Comment by Snile826** [comment]
The source code does provide a lot of implementations.
But maybe I didn't notice the entry point. I only saw how the IntrospectedTableMyBatis3Impl implementation was changed by the targetRuntinme property of the context tag.
And these are all predefined. Forgive my ignorance.
Do I need to recompile Mybatis?

**Comment by Snile826** [comment]
Thank you very much for your help.
However, I am using a Java annotation-based mapper, so I referenced other code in the source package and found that there is no annotation-based dynamic Insert mapping, so I completed this task through the plugin. This experience made me feel the plugin. The hook is powerful.
But what puzzles me is that I use the maven and mybatis-generator-maven-plugin build project. If you want to make the defined plugin work, you must package the plugin as a jar and upload it to the local repository. I feel that there is some trouble here... ...
I don't know if there is a better solution.

**Comment by Snile826** [comment]
Thank you very much for your help.
However, I am using a Java annotation-based mapper, so I referenced other code in the source package and found that there is no annotation-based dynamic Insert mapping, so I completed this task through the plugin. This experience made me feel the plugin hook is powerful.
But what puzzles me is that I use the maven and mybatis-generator-maven-plugin build project. If you want to make the defined plugin work, you must package the plugin as a jar and upload it to the local repository. I feel that there is some trouble here... ...
I don't know if there is a better solution.

**Comment by Snile826** [comment]
Thank you very much for your help.
However, I am using a Java annotation-based mapper, so I look other code in the source package and found that there is no annotation-based dynamic Insert mapping, so I completed this task through the plugin. This experience made me feel the plugin hook is powerful.
But what puzzles me is that I use the maven and mybatis-generator-maven-plugin build project. If you want to make the defined plugin work, you must package the plugin as a jar and upload it to the local repository. I feel that there is some trouble here... ...
I don't know if there is a better solution.

**Comment by jeffgbutler** [comment]
That's the best way to do it - build your plugin with Maven, then make it a dependency of the plugin. If you don't do it that way, you'll need to add your JAR to the classpath some other way.

It might be worth your time looking at the new MyBatis3DynamicSql runtime. Code generated for that environment gives you a lot of opportunity to customize your experience after the code generation step, so you might not need to deal with plugins.
