### ISSUE TITLE
How can I building MBG from Source?

### ISSUE THREAD

**Issue by hbwhypw** [mybatis/generator#45]
I build according to the reference(http://mybatis.github.io/generator/reference/building.html),but occurred an exception.
>mvn clean install
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] MyBatis Generator
[INFO] MyBatis Generator Core
[INFO] MyBatis Generator Maven Plugin
[INFO] MyBatis Generator Tests (Common Classes)
[INFO] MyBatis Generator Tests (MyBatis3)
[INFO] MyBatis Generator Tests (iBATIS2 - Java2)
[INFO] MyBatis Generator Tests (iBATIS2 - Java5)
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building MyBatis Generator 1.3.3-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-enforcer-plugin:1.4:enforce (enforce-java) @ mybatis-generator ---
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/mybatis-parent/24-S
NAPSHOT/maven-metadata.xml
Downloading: https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/mybatis-parent/24-S
NAPSHOT/mybatis-parent-24-SNAPSHOT.pom
[WARNING] Rule 0: org.apache.maven.plugins.enforcer.RequirePluginVersions failed with message:
Could not find artifact org.mybatis:mybatis-parent:pom:24-SNAPSHOT in sonatype-nexus-snapshots (http
s://oss.sonatype.org/content/repositories/snapshots)

  org.mybatis:mybatis-parent:pom:24-SNAPSHOT

from the specified remote repositories:
  sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots, releases=false,
 snapshots=true),
  central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)

[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] MyBatis Generator .................................. FAILURE [ 12.211 s]
[INFO] MyBatis Generator Core ............................. SKIPPED
[INFO] MyBatis Generator Maven Plugin ..................... SKIPPED
[INFO] MyBatis Generator Tests (Common Classes) ........... SKIPPED
[INFO] MyBatis Generator Tests (MyBatis3) ................. SKIPPED
[INFO] MyBatis Generator Tests (iBATIS2 - Java2) .......... SKIPPED
[INFO] MyBatis Generator Tests (iBATIS2 - Java5) .......... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.798 s
[INFO] Finished at: 2015-09-15T22:26:04+08:00
[INFO] Final Memory: 13M/89M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.4:enforce (enforce-j
ava) on project mybatis-generator: Some Enforcer rules have failed. Look above for specific messages
 explaining why the rule failed. -> [Help 1]

Who can help me ?

**Comment by jeffgbutler** [comment]
This is fixed already - please update your branch.
