### ISSUE TITLE
Do not support mariadb drivers ???

### ISSUE THREAD

**Issue by gackeyZhang** [mybatis/generator#450]
use mariadb-java-client 2.3.0
hint：can’t found drivers

**Comment by jeffgbutler** [comment]
Did you put the driver in the classpath?

**Comment by plus-7** [comment]
spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/drugs?useUnicode=true&characterEncoding=UTF-8

If I use mysql driver and configuration，its ok

**Comment by plus-7** [comment]
![image](https://user-images.githubusercontent.com/43566271/54165948-c5c3ab80-449d-11e9-9721-0025cf8f17a6.png)

**Comment by plus-7** [comment]
> Did you put the driver in the classpath?
If I use mysql driver and configuration，its ok

**Comment by jeffgbutler** [comment]
The generator makes a simple JDBC based connection using the driver manager. I don't use Maria personally, but I can't see any reason it wouldn't work. Do you have a stack trace or error message to show?

If it works with the MySQL driver, then that driver must be in the classpath of the generator. Make sure that the Maria driver is in the classpath of the generator. Your screen shot (from Eclipse maybe?) isn't really telling us anything. Setting the generator classpath properly is different depending on how you are running the generator (eclipse plugin? command line? from maven?)

**Comment by neverso** [comment]
> The generator makes a simple JDBC based connection using the driver manager. I don't use Maria personally, but I can't see any reason it wouldn't work. Do you have a stack trace or error message to show?
> 
> If it works with the MySQL driver, then that driver must be in the classpath of the generator. Make sure that the Maria driver is in the classpath of the generator. Your screen shot (from Eclipse maybe?) isn't really telling us anything. Setting the generator classpath properly is different depending on how you are running the generator (eclipse plugin? command line? from maven?)

i am sorry ，because this is the first time I asked a question on github,I hope you can understand.
I used eclipse plugin, version is 1.3.7

MyBatis Generator Started...
  Buildfile: D:\Develop\eclipse-workspace\.metadata\.plugins\org.mybatis.generator.eclipse.ui\.generatedAntScripts\drugmanagement-generatorConfig.xml.xml
  02:50:52.615 [Worker-10: Launching drugmanagement-generatorConfig.xml] DEBUG org.mybatis.generator.eclipse.ui.ant.logging.AntLogFactory - Logging initialized using 'org.mybatis.generator.eclipse.ui.ant.logging.slf4j.Slf4jLoggingLogFactory@3f79b86' adapter.
  02:50:52.631 [Worker-10: Launching drugmanagement-generatorConfig.xml] DEBUG org.mybatis.generator.logging.LogFactory - Logging initialized using 'org.mybatis.generator.eclipse.ui.ant.logging.AntLogFactory@2fbf974c' adapter.
MyBatis Generator Finished

![image](https://user-images.githubusercontent.com/43566271/54227772-9b283000-453b-11e9-94aa-0ffa758f8709.png)

**Comment by neverso** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN" "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">
<generatorConfiguration>
	
	<classPathEntry location="D:\Develop\mvnRepository\org\mariadb\jdbc\mariadb-java-client\2.3.0\mariadb-java-client-2.3.0.jar" />
	<context id="drugs" targetRuntime="MyBatis3">
		<commentGenerator>
			
			<property name="suppressAllComments" value="true" />
		</commentGenerator>
		
		<jdbcConnection
			connectionURL="jdbc:mariadb://localhost:3306/drugs?useUnicode=true&amp;characterEncoding=UTF-8&amp;serverTimezone=UTC"
			driverClass="com.mariadb.jdbc.Driver" password="ninjafrog" userId="root" />
		
		<javaTypeResolver>
			<property name="forceBigDecimals" value="true" />
		</javaTypeResolver>

		
		<javaModelGenerator targetPackage="com.gackey.medicine.entity"
			targetProject="drugmanagement/src/main/java">
			
			<property name="enableSubPackages" value="false" />
			
			<property name="trimStrings" value="true" />
		</javaModelGenerator>
		
		<sqlMapGenerator targetPackage="mappers" targetProject="drugmanagement/src/main/resources">
			
			<property name="enableSubPackages" value="false" />
		</sqlMapGenerator>
		
		<javaClientGenerator targetPackage="com.gackey.medicine.mapper"
			targetProject="drugmanagement/src/main/java" type="XMLMAPPER">
			
			<property name="enableSubPackages" value="false" />
		</javaClientGenerator>

		
		<table schema="" tableName="test_table" />

		
		

		
		
	</context>
</generatorConfiguration>

**Comment by neverso** [comment]
<classPathEntry location="D:\Develop\mvnRepository\org\mariadb\jdbc\mariadb-java-client\2.3.0\mariadb-java-client-2.3.0.jar" />


This is in the project

**Comment by neverso** [comment]
This is in the project.
<classPathEntry location="D:\Develop\mvnRepository\org\mariadb\jdbc\mariadb-java-client\2.3.0\mariadb-java-client-2.3.0.jar" />

**Comment by neverso** [comment]
This is in the project.
classPathEntry location="D:\Develop\mvnRepository\org\mariadb\jdbc\mariadb-java-client\2.3.0\mariadb-java-client-2.3.0.jar"

**Comment by gackeyZhang** [comment]
driverClass="org.mariadb.jdbc.Driver"
That's right.

**Comment by mmm8955405** [comment]
In the latest version, mariadb sets<property name="nullCatalogMeasCurrent" value="true"/>; Not working
