### ISSUE TITLE
add supports for java 11

### ISSUE THREAD

**Issue by Frodez** [mybatis/generator#451]
Now I'm working on the openjdk11.0.2, and i also use this tool and my extentions to generate DAOs automatically. But this tool doesn't support the version of java11, when i try to do, the mybatis-generator will be crashed：
**java.lang.UnsupportedClassVersionError: mybatis/CustomSettingsPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0**
My IDE is Eclipse4.10.

**Comment by jeffgbutler** [comment]
Are you sure you are running the generator with JRE 11? The error message indicates you are running it with JRE 8.

**Comment by Frodez** [comment]
> Are you sure you are running the generator with JRE 11? The error message indicates you are running it with JRE 8.

Yes,i'm sure that.
In the Eclipse's settings page, i'm already set the Installed JRE to openjdk11.0.2(Window/Preferences/Java/Installed JRE) and Java Compliance to JDK11(Window/Preferences/Java/Compiler).And in my project's properties page, i'm also set to JDK Compliance to JDK11.
And When I change my project's JDK Compliance back to JDK1.8, the error has gone away.

**Comment by jeffgbutler** [comment]
The MBG plugin runs in the same JRE as the workspace. So changing the Java versions of the project won't change how MBG is being run.

From your descriptions, I'm guessing that Eclipse itself is running with a Java 8 JRE. You can change that in the "eclipse.ini" file in your eclipse installation - look for a line that starts with "-vm" and make sure it is pointing to your JRE 11.

**Comment by Frodez** [comment]
> The MBG plugin runs in the same JRE as the workspace. So changing the Java versions of the project won't change how MBG is being run.
> 
> From your descriptions, I'm guessing that Eclipse itself is running with a Java 8 JRE. You can change that in the "eclipse.ini" file in your eclipse installation - look for a line that starts with "-vm" and make sure it is pointing to your JRE 11.

Oh, it explains the matter,and now the problem has been resolved.Thank you very much.
