### ISSUE TITLE
Table name generic matching not need to generate mapper for view

### ISSUE THREAD

**Issue by Hinsteny** [mybatis/generator#455]
**Under mysql 8.0, mybatis-generator 1.3.7**

Database table
```
v_user
v_account
```

### First method

1. Config generatorConfig.xml as blew
```
    <sqlMapGenerator targetPackage="mapper"
      targetProject="src/main/resources">
      <property name="enableSubPackages" value="true"/>
    </sqlMapGenerator>

    <table tableName="v_%" schema="pay" >
    </table>
```
2. Do generate
3. Get result Mapper files
```
resource:
  mapper:
    VAccountMapper.xml
    ViewsMapper.xml
    VUserMapper.xml
```
**Problem: the ViewsMapper is not needed!**  

### Second method

---
1. Config generatorConfig.xml as blew
```
    <sqlMapGenerator targetPackage="mapper"
      targetProject="src/main/resources">
      <property name="enableSubPackages" value="true"/>
    </sqlMapGenerator>

    <table tableName="v_%" schema="pay" catalog="pay">
    </table>
```
2. Do generate
3. Get result Mapper files
```
resource:
  mapper:
    pay: 
      VAccountMapper.xml
      VUserMapper.xml
```

**Problem:  Although the ViewsMapper is not appear, but another issus is occurred, in the VUserMapper.xml there is some error sql like** 

```
insert into pay..v_user
select count(*) from pay..v_user
update pay..v_user
```

**Comment by jeffgbutler** [comment]
You are running into a very common issue with MySQL. You will need to add the `nullCatalogMeansCurrent` property to your connection. MySQL doesn't handle schema and catalog properly. It's best not to specify those attributes in your table configuration.

See here: http://www.mybatis.org/generator/usage/mysql.html

**Comment by Hinsteny** [comment]
OK, i have tried as you said, it works. very thanks.
But i have fund one cacography at that usage doc page
```
<jdbcConnection driverClass="com.mysql.jdbc.Driver" connectionURL="jdbc:mysql://localhost/my_schema"
            userId="my_user" password="my_password">
        <property name="nullCatalogMeansCurrent" value=true" />
    </jdbcConnection>
```

the nullCatalogMeansCurrent property's value "true" should have double quotation marks

**Comment by jeffgbutler** [comment]
I'll fix the documentation, Thanks for letting me know.
