### ISSUE TITLE
建议：针对SQLServer数据库，新增可以配置with nolock

### ISSUE THREAD

**Issue by onlyas** [mybatis/generator#457]
类似这样：       

       StringBuilder sb = new StringBuilder();
        sb.append("select count(*) from "); //$NON-NLS-1$
        sb.append(introspectedTable.getAliasedFullyQualifiedTableNameAtRuntime());
        **if(isSQLServer&&isWithNolock){
            sb.append(" with (nolock) ");
        }**
        answer.addElement(new TextElement(sb.toString()));
        answer.addElement(getExampleIncludeElement());

**Comment by jeffgbutler** [comment]
You could something like this with a plugin. In general, we don't add vendor specific stuff to the base generator code.

**Comment by onlyas** [comment]
谢谢，我已经写了一个插件：
public class SelectWithNolockPlugin extends PluginAdapter {
        @Override
    public boolean sqlMapCountByExampleElementGenerated(XmlElement element, IntrospectedTable introspectedTable) {
        element.getElements().clear();

        StringBuilder sb = new StringBuilder();
        sb.append("select count(*) from "); //$NON-NLS-1$
        sb.append(introspectedTable.getAliasedFullyQualifiedTableNameAtRuntime());
        sb.append(" with (nolock) ");
        element.addElement(new TextElement(sb.toString()));
        element.addElement(getExampleIncludeElement(introspectedTable));

        return true;
    }
}
