### ISSUE TITLE
【bug】oracle namespace bug

### ISSUE THREAD

**Issue by SmallerCoder** [mybatis/generator#460]
Hello,there is a problem that when  execute 'mvn mybatis-generator:generate' command,mybatis-generator will generate  [second namespace].[tablename]  if there exist two same table on different namespace .

for example,table called “ACCOUNT” which  exists in two namespace A,B.  A.ACCOUNT is the table which we will expect mybatis-generator to generate,but  when  execute 'mvn mybatis-generator:generate' command,mybatis-generator will generate  B.ACCOUNT to override A.ACCOUNT

**Comment by jeffgbutler** [comment]
I'm not familiar with Oracle namespaces - is it the same as a schema?

Assuming that the JDBC driver returns information about these two tables in different schemas, you would need to set the `enableSubPackages` property on all the generator configurations to avoid this collision. See this page for an example: http://www.mybatis.org/generator/configreference/xmlconfig.html

**Comment by jeffgbutler** [comment]
No response
