### ISSUE TITLE
The generated .xml has a small bug

### ISSUE THREAD

**Issue by robin536180** [mybatis/generator#462]
When the field is a string object and value = '',  if run as the following code will throw an synax error：   
```xml
 <if test="sysCode != null" >
        AND SYS_CODE = #{sysCode,jdbcType=VARCHAR},
 </if>
```
because the filed 'sysCode' is not null, its value is an empty string, so it matches the if condition.
Actually, it should be generated like this:
```xml 
<if test="sysCode != null and sysCode != ''" >
        AND SYS_CODE = #{sysCode,jdbcType=VARCHAR},
 </if>
```
I hope you can fix this problem, this problem exists for a very long time, thanks!

**Comment by jeffgbutler** [comment]
Empty string and null are **not** the same thing.

Are you using Oracle and VARCHAR2 datatypes? I know that combination tries to treat these two different things as the same which may be causing the confusion.

What is the syntax error you are seeing?

**Comment by robin536180** [comment]
I'm using Mysql, and this no matter with the database. I mean that when a field is a type of string, the generated xml file should add the expression in the if clause.For example:
if my java code is
 `String sysCode = "";`, 
xml file content is
 `<select id="query" parameter="java.lang.String" resultType="java.util.HashMap">
select SYS_CODE as sysCode from table
<where>
<if test="sysCode != null" >
        AND SYS_CODE = #{sysCode,jdbcType=VARCHAR},
 </if>
</where>
</select>`
when I call the query method, the sql will be: 
`select SYS_CODE as sysCode from table where SYS_CODE = ''`,
actually it should not match the if clause, it should be:
`select SYS_CODE as sysCode from table`,
so I had to add the code 
`sysCode != ''`
every string field every time,  because it spends me a lot of time.

**Comment by jeffgbutler** [comment]
Well that is not a syntax error, and it looks like that code is doing what it was designed to do.

But now I'm confused...MyBatis generator does not generate code like this in a where clause. Are you using a plugin that generates extra methods? If so, you could alter that plugin to make it work the way you want it to work.

If you post the relevant parts of your generator configuration, I can point you in the right direction.

**Comment by jeffgbutler** [comment]
No response
