### ISSUE TITLE
comment is empty generated with MyBatis3DynamicSQL runtime

### ISSUE THREAD

**Issue by htyggh** [mybatis/generator#463]
Hello, my English is very poor, please forgive me for using the translation tool to communicate with you
I found in the process of using MBG that using MyBatis3DynamicSQL would not generate custom comments. I know from reading the source code that you cleared the comments here. Why?
![image](https://user-images.githubusercontent.com/34332882/57215374-3e1e9700-701f-11e9-99c1-57a5526c8bcb.png)

**Comment by htyggh** [comment]
I should with addFieldAnnotation addGeneralMethodAnnotation add custom  comment?

**Comment by jeffgbutler** [comment]
You should use the `addJavaDocLine` method to add method or field comments in a plugin. The JavaDoc is initially cleared because the MyBatis3DynamicSQL runtime uses the `@Generated` annotation instead of custom JavaDoc.

If you add JavaDoc in a plugin it will not be cleared.

**Comment by htyggh** [comment]
> You should use the `addJavaDocLine` method to add method or field comments in a plugin. The JavaDoc is initially cleared because the MyBatis3DynamicSQL runtime uses the `@Generated` annotation instead of custom JavaDoc.
> 
> If you add JavaDoc in a plugin it will not be cleared.

![image](https://user-images.githubusercontent.com/34332882/57264936-88e3f180-70a7-11e9-94c5-16249ffebd23.png)
![image](https://user-images.githubusercontent.com/34332882/57264943-94cfb380-70a7-11e9-85b4-f80314421523.png)
But you called the comment plugin before you cleared the comment, which invalidated the custom comment plugin that I implemented on the `CommentGenerator` interface

**Comment by jeffgbutler** [comment]
Thanks - I understand the issue now. I'll need to add methods to the comment generator for this.

**Comment by jeffgbutler** [comment]
Reopening so I remember to make the fix.

**Comment by htyggh** [comment]
Now I use `addGeneralMethodAnnotation` `addFieldAnnotation` `addClassAnnotation` method, adding comments for `MyBatis3DynamicSql` mode
![image](https://user-images.githubusercontent.com/34332882/57496407-56373480-7305-11e9-8364-e93334c0e415.png)

**Comment by htyggh** [comment]
I used the latest version of MBG and found that the problem was not completely fixed. This time, only class Javadoc was fixed, and Javadoc for filed and method was ignored

**Comment by htyggh** [comment]
Now I use Plugin way to generate Javadoc for myBatis3DynamicSQL, myBatis3DynamicSQLV1 and myBatis3DynamicSQLV2
