### ISSUE TITLE
多表查询重复字段问题是怎么解决的？

### ISSUE THREAD

**Issue by wangyushuai** [mybatis/generator#466]
`
select * from A
left join B on A.regionId = B.regionId
where regionId = 'xxx'
`
这样逆向工程生成的regionId 没有前缀, 就会查询报错呢。

**Comment by jeffgbutler** [comment]
In your generator configuration file you can specify an `alias` for a table and then the columns will be uniquely named in the query. See here for details: http://www.mybatis.org/generator/configreference/table.html

**Comment by wangyushuai** [comment]
> In your generator configuration file you can specify an `alias` for a table and then the columns will be uniquely named in the query. See here for details: http://www.mybatis.org/generator/configreference/table.html

THX! !  And I had another question; 
What is the role of the "includeExamplePhrase" parameter in the "applyWhere" method?
`
protected void applyWhere(SQL sql, AppConfigPublishVersionExample example, boolean includeExamplePhrase)
`

**Comment by jeffgbutler** [comment]
It's used when building the where clause for an update by example statement. For those statements, the statement parameters are placed in a Map and we need to include the map key when referencing.

This kind of generated code - that is hard to understand - is one the the main reasons I wrote [MyBatis Dynamic SQL](https://github.com/mybatis/mybatis-dynamic-sql). In that case the generated code is much easier to understand, and far more flexible too.

**Comment by wangyushuai** [comment]
> It's used when building the where clause for an update by example statement. For those statements, the statement parameters are placed in a Map and we need to include the map key when referencing.
> 
> This kind of generated code - that is hard to understand - is one the the main reasons I wrote [MyBatis Dynamic SQL](https://github.com/mybatis/mybatis-dynamic-sql). In that case the generated code is much easier to understand, and far more flexible too.

Thank you very much !
