### ISSUE TITLE
The same comment should not appear multiple times

### ISSUE THREAD

**Issue by zenglian** [mybatis/generator#468]
To make the code cleaner and more readable, please place the same comment in the file header, or create a region for all methods, and place the comment the header of the region. 
See https://en.wikipedia.org/wiki/Don%27t_repeat_yourself.

```
package mapper;

import java.util.List;
import model.Country;
import model.CountryExample;
import org.apache.ibatis.annotations.Param;

public interface CountryMapper {
    /**
     * @mbg.generated generated automatically, do not modify!
     */
    long countByExample(CountryExample example);

    /**
     * @mbg.generated generated automatically, do not modify!
     */
    int deleteByExample(CountryExample example);

    /**
     * @mbg.generated generated automatically, do not modify!
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * @mbg.generated generated automatically, do not modify!
     */
    int insert(Country record);

    /**
     * @mbg.generated generated automatically, do not modify!
     */
    int insertSelective(Country record);

    /**
     * @mbg.generated generated automatically, do not modify!
     */
    List<Country> selectByExample(CountryExample example);

    /**
     * @mbg.generated generated automatically, do not modify!
     */
    Country selectByPrimaryKey(Integer id);

    /**
     * @mbg.generated generated automatically, do not modify!
     */
    int updateByExampleSelective(@Param("record") Country record, @Param("example") CountryExample example);

    /**
     * @mbg.generated generated automatically, do not modify!
     */
    int updateByExample(@Param("record") Country record, @Param("example") CountryExample example);

    /**
     * @mbg.generated generated automatically, do not modify!
     */
    int updateByPrimaryKeySelective(Country record);

    /**
     * @mbg.generated generated automatically, do not modify!
     */
    int updateByPrimaryKey(Country record);
}
```

**Comment by jeffgbutler** [comment]
While I am a fan of the DRY principle, it doesn't apply here These comments have a purpose. They are used by the Java file merger when regenerating code. Kind of like the `@Generated` annotation in Java8.

If you are not concerned about the merge function, then you can disable comments.

**Comment by zenglian** [comment]
Not sure how the merger works, will one @mbg.generated (or none at all) at the file/class level do the trick? 
If it's used to avoid overwritting manually added methods, IMO it's user's responsibility to avoid that. But it can be an option (fail,warn, or overwrite silently).

**Comment by jeffgbutler** [comment]
That won't work. The merger allows a user to add anything to a generated class. If it is not "annotated" like this, then it will survive a merge. Hence "merge" - we merge old code with new code, it's not just a replace. 

I agree with you that changing a generated method is nothing we can prevent.

You can implement your own comment generator and make the comments look any way you want (or remove them). If you aren't using the merge function then it won't harm anything to change them.
