### ISSUE TITLE
generator function and procedure

### ISSUE THREAD

**Issue by wilsonp** [mybatis/generator#47]
I use the mybatis-generator in my project, but only generate table and view .How do I use the mysql function and procedure in mybatis-generator ?

**Comment by jeffgbutler** [comment]
The generator doesn't support generating code for functions and procedures - you will have to write that code yourself.

Let me also say that we have no plans to add this to the generator.  I did a serious investigation into this some years ago and come to the conclusion that the configuration needed to make this happen would actually be worse than just writing the code yourself.

Please use the MyBatis mailing list for questions if you have them.
