### ISSUE TITLE
Do not support batch insert?

### ISSUE THREAD

**Issue by pky920216344** [mybatis/generator#470]
I seem to have seen it in old branch

**Comment by jeffgbutler** [comment]
MyBatis supports batch inserts. See this FAQ page: https://github.com/mybatis/mybatis-3/wiki/FAQ#how-do-i-code-a-batch-insert

Mappers created by the generator will work with MyBatis batch support.

The MyBatis Dynamic SQL library has special support for MyBatis batches. See this page for more details: http://www.mybatis.org/mybatis-dynamic-sql/docs/insert.html

**Comment by pky920216344** [comment]
@jeffgbutler  yeah, i know.
but, i prefer generator.
when generator configuration XML 
 `<context id="MysqlTables" targetRuntime="MyBatis3">
.....
</context>
`
mapper will generate 
`
int insertBatch(Collection<T> collection);
`
and XML
```
  <insert id="insertBatch" parameterType="java.util.Collection">
    <if test="collection != null ">
	insert into `model` ( `name`, `age`)
	 values 
	<foreach collection="collection" item="data" index="index" separator=",">
    (#{data.name,jdbcType=VARCHAR},#{data.age,jdbcType=INTEGER})
	</foreach>
	</if>
  </insert>
```
and when generator configuration XML 
 `<context id="MysqlTables" targetRuntime="MyBatis3DynamicSql">
.....
</context>
`
generate different mapper

**Comment by jeffgbutler** [comment]
That is called a "multi row insert" - not a batch. It is a single insert statement with a lot of parameters.

There are a couple of issues with this approach:

1. It is easy to exceed the maximum number of allowable parameters in a single statement
1. It is not easy to retrieve generated keys for that kind of statement

For these reasons, I have never felt comfortable adding these kinds of statements to generated code. But I believe MyBatis has made some changes recently regarding the generated key issue, so it might be worth looking at again.

**Comment by jeffgbutler** [comment]
Also see this issue for some discussion: https://github.com/mybatis/mybatis-dynamic-sql/issues/53

**Comment by pky920216344** [comment]
@jeffgbutler thank you
