### ISSUE TITLE
countByExample  result is not correct

### ISSUE THREAD

**Issue by winyiwin** [mybatis/generator#471]
when i use MBG,  countByExample method the result is not correct.

my databse has 4 data. but i always select result is 1 .

![image](https://user-images.githubusercontent.com/11864671/61097830-5384c700-a48f-11e9-936e-65854cf9c6c5.png)
![image](https://user-images.githubusercontent.com/11864671/61097857-6b5c4b00-a48f-11e9-8e61-26171e6f60b9.png)
![image](https://user-images.githubusercontent.com/11864671/61097873-74e5b300-a48f-11e9-89ff-629c2d714004.png)

i user springboot 2.1.6.RELEASE  mgb 1.3.7 mybatis 3.5.1

**Comment by jeffgbutler** [comment]
The SQL looks correct. Maybe there is some encoding problem on the connection.

**Comment by winyiwin** [comment]
i'm
