### ISSUE TITLE
table column keyword processing does not work in targetRuntime="MyBatis3DynamicSql"

### ISSUE THREAD

**Issue by pky920216344** [mybatis/generator#474]
this is my config.xml:
![image](https://user-images.githubusercontent.com/23168199/61426604-8b878080-a94d-11e9-9437-ed1e75ab2e15.png)
column name is 'virtual', this is keyword in MySql 8.0+.
i thought that configuration was that all columns would be marked with special symbols, but the result was not.

**Comment by jeffgbutler** [comment]
"autoDelimitKeywords" will check column names against the list of SQL keywords maintained within the generator. That list is here: https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/main/java/org/mybatis/generator/internal/db/SqlReservedWords.java

"VIRTUAL" is not on that list.

If you want to delimit all columns, you can specify the `delemitAllColumns` property on a `<table>` configuration. If you only want to delimit the "VIRTUAL" column, you can do it with a `<columnOverride>`

**Comment by pky920216344** [comment]
thank,solved my problem
