### ISSUE TITLE
how to use generator  to generate javaModule field`s annotation

### ISSUE THREAD

**Issue by JanYunkai** [mybatis/generator#482]
db table user generated JavaModule
class User {
    @Version
    private Integer version;
}

how can i generate @Version

**Comment by jeffgbutler** [comment]
You can write a plugin to do this. Extend PluginAdapter and then override the `modelFieldGenerated` method.

**Comment by pky920216344** [comment]
@JanYunkai  
English：
You can customize a plug-in to add custom annotations to entity attributes, extends org. mybatis. generator. api. PluginAdapter

Rewrite the following methods:
```
Public Boolean model Field Generated (Field,

TopLevelClass topLevelClass, Introspected Column introspected Column,

Introspected Table introspected Table,

Plugin. ModelClassType Model ClassType){

Return true;

}
```

You can refer to my writing [mgb-plugin-pky] (https://github.com/pky920216344/mgb-plugin-pky)

Of course, this is not my original work. I wrote [mbg_lombok_plugin] (https://github.com/WGKLoveStudy/mbg_lombok_plugin/tree/master) after this.

中文：
你可以自定义一个插件来给实体属性添加自定义注解，继承org.mybatis.generator.api.PluginAdapter
重写以下方法：
````
 public boolean modelFieldGenerated(Field field,
                                       TopLevelClass topLevelClass, IntrospectedColumn introspectedColumn,
                                       IntrospectedTable introspectedTable,
                                       Plugin.ModelClassType modelClassType){
 return true;
}
````
你可以参照我的写法 [mgb-plugin-pky](https://github.com/pky920216344/mgb-plugin-pky)
当然这并不是我原创的，我是仿照[mbg_lombok_plugin](https://github.com/WGKLoveStudy/mbg_lombok_plugin/tree/master)这个写的

**Comment by JanYunkai** [comment]
thx every much!
