### ISSUE TITLE
criteria.andValidNotEqualTo(false)

### ISSUE THREAD

**Issue by kelisima001** [mybatis/generator#489]
valid has null and 0,
criteria.andValidNotEqualTo(false)   
cant find any data
y?

**Comment by jeffgbutler** [comment]
This must be coming from some custom plugin - “andValidNotEqualTo” is not a method generated by MyBatis Generator. Please contact whoever  wrote the plugin.

**Comment by kelisima001** [comment]
CommitteeExample example=new CommitteeExample();
        CommitteeExample.Criteria criteria=example.createCriteria();
        criteria.andBidsectiondatakeyIn(bidSectionDataKeyList);
        criteria.andValidIsNotNull();
return committeeMapper.selectByExample(example);
dont use your code?

**Comment by jeffgbutler** [comment]
I apologize- I didn’t pickup that the column name was “valid”. It’s hard to diagnose this without seeing a more complete example. Can you give us more details?

**Comment by kelisima001** [comment]
<dependency>
            <groupId>org.mybatis.spring.boot</groupId>
            <artifactId>mybatis-spring-boot-starter</artifactId>
            <version>1.3.2</version>
        </dependency>

<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.2.RELEASE</version>
        <relativePath/> 
    </parent>

<resultMap id="BaseResultMap" type="com.imacco.bidding.prequalification.entity.Committee">
    <id column="Id" jdbcType="BIGINT" property="id" />
    <result column="BidSectionDataKey" jdbcType="VARCHAR" property="bidsectiondatakey" />
    <result column="CommitteeDataKey" jdbcType="VARCHAR" property="committeedatakey" />
    <result column="CommitteeCaNo" jdbcType="VARCHAR" property="committeecano" />
    <result column="CommitteeName" jdbcType="VARCHAR" property="committeename" />
    <result column="CommitteeUnitName" jdbcType="VARCHAR" property="committeeunitname" />
    <result column="CommitteeCardNo" jdbcType="VARCHAR" property="committeecardno" />
    <result column="CommitteeType" jdbcType="INTEGER" property="committeetype" />
    <result column="CommitteeWork" jdbcType="VARCHAR" property="committeework" />
    <result column="IsLeader" jdbcType="BIT" property="isleader" />
    <result column="PhoneNumber" jdbcType="VARCHAR" property="phonenumber" />
    <result column="valid" jdbcType="BIT" property="valid" />
  </resultMap>

<select id="selectByExample" parameterType="com.imacco.bidding.prequalification.entity.CommitteeExample" resultMap="BaseResultMap">
    select
    <if test="distinct">
      distinct
    </if>
    <include refid="Base_Column_List" />
    from Committee
    <if test="_parameter != null">
      <include refid="Example_Where_Clause" />
    </if>
    <if test="orderByClause != null">
      order by ${orderByClause}
    </if>
  </select>

<sql id="Base_Column_List">
    Id, BidSectionDataKey, CommitteeDataKey, CommitteeCaNo, CommitteeName, CommitteeUnitName, 
    CommitteeCardNo, CommitteeType, CommitteeWork, IsLeader, PhoneNumber, valid
  </sql>


its wired 
used example 

used criteria.andValidIsNotNull();   no data

sir , would u pls tell me?

**Comment by kelisima001** [comment]
<sql id="Base_Column_List">
    Id, BidSectionDataKey, CommitteeDataKey, CommitteeCaNo, CommitteeName, CommitteeUnitName, 
    CommitteeCardNo, CommitteeType, CommitteeWork, IsLeader, PhoneNumber, valid
  </sql>

**Comment by kelisima001** [comment]
sql id="Base_Column_List"
    Id, BidSectionDataKey, CommitteeDataKey, CommitteeCaNo, CommitteeName, CommitteeUnitName, 
    CommitteeCardNo, CommitteeType, CommitteeWork, IsLeader, PhoneNumber, valid
  /sql

**Comment by kelisima001** [comment]
select id="selectByExample" parameterType="com.imacco.bidding.prequalification.entity.CommitteeExample" resultMap="BaseResultMap"
    select
    if test="distinct"
      distinct
    /if
    include refid="Base_Column_List" /
    from Committee
    if test="_parameter != null"
      <include refid="Example_Where_Clause" /
    /if
    if test="orderByClause != null"
      order by ${orderByClause}
    /if
  /select

**Comment by jeffgbutler** [comment]
The most obvious answer is that there aren't any records in the table that meet the conditions you are using. One good way to debug is to turn on logging with MyBatis and verify that the queries are being generated as you expect (see this page for information on how to enable logging: http://www.mybatis.org/mybatis-3/logging.html)

You can also try a plain query. For example, if you are specifying the condition `andValidIsNotNull()` then do a query like `select * from committee where valid is not null`. Do you get any records returned from that query?

**Comment by kelisima001** [comment]
yes,it worked in mysql
SELECT * from Committee where valid is not null

**Comment by kelisima001** [comment]
soooo,is it a bug?

**Comment by kelisima001** [comment]
maybe problems in 
criteria.andBidsectiondatakeyIn(bidSectionDataKeyList);
thank u for  ur post......

**Comment by kelisima001** [comment]
SELECT * from Committee where valid is  null and BidSectionDataKey='3210001010222220190604000005'
1 result

**Comment by kelisima001** [comment]
SELECT * from Committee where valid is not null and BidSectionDataKey='3210001010222220190604000005'
4 result

**Comment by jeffgbutler** [comment]
Please turn on logging and check the generated SQL.

**Comment by jeffgbutler** [comment]
No response
