### ISSUE TITLE
generator jdbcType UNSIGNED -> javaType should be upgrade

### ISSUE THREAD

**Issue by liaomengge** [mybatis/generator#490]

**Comment by liaomengge** [comment]
introspectedColumn.setJdbcType(rs.getInt("DATA_TYPE")); //$NON-NLS-1$
introspectedColumn.setLength(rs.getInt("COLUMN_SIZE")); //$NON-NLS-1$
introspectedColumn.setActualColumnName(rs.getString("COLUMN_NAME")); //$NON-NLS-1$

should add TYPE_NAME, so can discriminate UNSIGNED type~

**Comment by jeffgbutler** [comment]
I think it is a good idea to add the TYPE_NAME to introspected column. I will do that.

I don't think it is a good idea to build the "UNSIGNED" support directly into the generator - this is a platform specific thing and I don't think there is a general solution for all platforms. But you could easily implement a JavaTypeResolver to handle unsigned types for your specific platform.

**Comment by liaomengge** [comment]
> I think it is a good idea to add the TYPE_NAME to introspected column. I will do that.
> 
> I don't think it is a good idea to build the "UNSIGNED" support directly into the generator - this is a platform specific thing and I don't think there is a general solution for all platforms. But you could easily implement a JavaTypeResolver to handle unsigned types for your specific platform.

yes，i'm sympathetic，but i see the introspectedColumn couldn't export the Type_Name properties. so i custom JavaTypeResolver couldn't realize the idea.(i already read the JavaTypeResolver default impl),so could you export the TYPE_NAME,then i can custom my JavaTypeResolver, really hope the next version can do it.

**Comment by liaomengge** [comment]
thanks a lot, may I ask  when the next version will be release ~

**Comment by jeffgbutler** [comment]
Hopefully I will release in the next few weeks. I need to do a new release of MyBatis Dynamic SQL first.

**Comment by liaomengge** [comment]
> Hopefully I will release in the next few weeks. I need to do a new release of MyBatis Dynamic SQL first.

could you upload 1.4.0-snapshot, now i have a lot of project for mysql unsigned,but  i don't want to check all table's column field, thx ~

**Comment by jeffgbutler** [comment]
Snapshots are here: https://oss.sonatype.org/content/repositories/snapshots/org/mybatis/generator/mybatis-generator/

**Comment by liaomengge** [comment]
when i use 1.3.7 ,the is all right,but when i use 1.4.0-snapshot, the bad thing  generate, it's below:

![image](https://user-images.githubusercontent.com/12670328/64412934-1cafe380-d0c3-11e9-94bb-ee8817b2572e.png)

**Comment by liaomengge** [comment]
@jeffgbutler the 1.4.0-snapshot couldn't do it. when i run, the bad thing happend. so i pull the 1.3.7 release version, and modify the code, then upload 1.3.7.x to my local maven repository, then run okay. then i will not manual coverage for the unsigned filed in future.

**Comment by core1942** [comment]
@liaomengge 能把你修改的项目共享一份给我吗？我最近也很困扰这个问题，拜托了

**Comment by liaomengge** [comment]
> 一份

the is update code:
https://github.com/liaomengge/maven-repository/tree/master/repository

**Comment by liaomengge** [comment]
> @liaomengge 能把你修改的项目共享一份给我吗？我最近也很困扰这个问题，拜托了

the is update code:
https://github.com/liaomengge/maven-repository/tree/master/repository
