### ISSUE TITLE
Consider adding Lombok support to the next release？

### ISSUE THREAD

**Issue by 411937647** [mybatis/generator#502]
Now using MBG and Lombok at the same time is very troublesome.
Will Lombok be supported in the next version?

**Comment by pky920216344** [comment]
hi,
maybe you can see [#296 ](https://github.com/mybatis/generator/pull/296)

**Comment by jeffgbutler** [comment]
I have no plans to add Lombok support into the base generator - a plugin like mentioned above is the preferred method of altering the generated code.
