### ISSUE TITLE
The source code repository is too large to download, can you provide other way to download it?

### ISSUE THREAD

**Issue by MrZhangsun** [mybatis/generator#503]

**Comment by kazuki43zoo** [comment]
@MrZhangsun 

You can download source files(sources jar) via [the Maven central repository](https://repo1.maven.org/maven2/org/mybatis/generator/). Can you fix your issue by this comment?

**Comment by jeffgbutler** [comment]
Thanks for reporting this. I've just done a couple of cleanup tasks that have helped.

After #504 and #505, the download is quite a lot smaller (reduced by about 75%).

**Comment by jeffgbutler** [comment]
No response
