### ISSUE TITLE
Field wrap and repeat

### ISSUE THREAD

**Issue by ANoviceOfJava** [mybatis/generator#512]
I don't know if you have encountered this kind of problem. After I use the plugin, there is a field that automatically wraps and repeats. When I rewrite the field name in the database, it is normal.

![微信图片_20191114204021](https://user-images.githubusercontent.com/39426572/68857975-ffc90980-071e-11ea-9323-3d0b19db075f.png)
![微信图片_20191114204013](https://user-images.githubusercontent.com/39426572/68857976-0061a000-071f-11ea-8256-e7bb980647c0.png)

**Comment by jeffgbutler** [comment]
I've not seen this problem before. Are you using any generator plugins?

**Comment by jeffgbutler** [comment]
No response
