### ISSUE TITLE
domainObjectRenamingRule problem

### ISSUE THREAD

**Issue by linchuyao** [mybatis/generator#514]
version 1.3.7 
mysql table name user_login_log   
when i config domainObjectRenamingRule whth ^User geberator result:  Loginlog  not CamelCaseString version 1.3.6 not problem

if (domainObjectRenamingRule != null) {
            Pattern pattern = Pattern.compile(domainObjectRenamingRule.getSearchString());
            String replaceString = domainObjectRenamingRule.getReplaceString();
            replaceString = replaceString == null ? "" : replaceString; //$NON-NLS-1$
            Matcher matcher = pattern.matcher(finalDomainObjectName);
            finalDomainObjectName = getCamelCaseString(matcher.replaceAll(replaceString), true); ??????
        }

**Comment by jeffgbutler** [comment]
Duplicate of #382
