### ISSUE TITLE
XML manespace

### ISSUE THREAD

**Issue by booyaka-w** [mybatis/generator#525]
When using suppressallcomments = fasle,

Content is generated twice in namespace,

Two resultmaps and all methods,

I don't know what the reason is. Can you help me to have a look

**Comment by booyaka-w** [comment]
I found something，
XmlFileMergerJaxp.class 135line
if (isGeneratedNode(node)) {
	nodesToDelete.add(node);
} else if (isWhiteSpace(node) && isGeneratedNode(children.item(i + 1))) {
	nodesToDelete.add(node);
}
if  suppressallcomments = fasle；
nodesToDelete  always empty
That's why two resultmaps are generated

**Comment by booyaka-w** [comment]
@jeffgbutler

**Comment by jeffgbutler** [comment]
I cannot duplicate this problem. Please post your configuration, and also any errors or warnings from the generation run.

**Comment by booyaka-w** [comment]
Thank you for your reply


This is my project


If the


<property name="suppressAllComments" value="true" /&gt;


Generating corresponding XML will result in multiple resultmaps


<property name="suppressAllComments" value="fasle" /&gt;


I don't know if I'm using it the wrong way,


Thank you for your advice






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jeff Butler"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 凌晨3:32
收件人:&nbsp;"mybatis/generator"<generator@noreply.github.com&gt;;
抄送:&nbsp;"布呀卡"<515767010@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mybatis/generator] XML manespace (#525)




I cannot duplicate this problem. Please post your configuration, and also any errors or warnings from the generation run.

**Comment by booyaka-w** [comment]
I'm sorry I forgot to tell you the project running directory


Executing the main method in demo






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Jeff Butler"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 凌晨3:32
收件人:&nbsp;"mybatis/generator"<generator@noreply.github.com&gt;;
抄送:&nbsp;"布呀卡"<515767010@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [mybatis/generator] XML manespace (#525)




I cannot duplicate this problem. Please post your configuration, and also any errors or warnings from the generation run.

**Comment by jeffgbutler** [comment]
XML merging requires the comments. If you disable the comments, then this is expected behavior.

`<property name="suppressAllComments" value="true" />` will cause duplicate methods

This is documented here: http://mybatis.org/generator/configreference/commentGenerator.html

**Comment by jeffgbutler** [comment]
No response.
