### ISSUE TITLE
domainObjectRenamingRule not work

### ISSUE THREAD

**Issue by LzhBruce** [mybatis/generator#536]
when I use domainObjectRenamingRule config in table label, the result not What I want.
table name is "per_unit_machine", Object name is "PerUnitMachine". When I use domainObjectRenamingRule param. 
the new domain name is "Unitmachine", not "UnitMachine" that I want.
mybatis-generator-core version is 1.3.7

detail info :
<domainObjectRenamingRule searchString="^Per" replaceString=""/>

**Comment by jeffgbutler** [comment]
This has been fixed in version 1.4.0 - please upgrade to the new version.

Duplicate of #381.

**Comment by LzhBruce** [comment]
thanks.
