### ISSUE TITLE
MyBatis3FormattingUtilities中枚举类的中没有指定javaType

### ISSUE THREAD

**Issue by tigerxn** [mybatis/generator#553]
MyBatis3FormattingUtilities中枚举类的中没有指定javaType，在按照枚举类查询或更新时会报错。
java.lang.IllegalArgumentException: Object does not represent an enum type.

**Comment by jeffgbutler** [comment]
Please provide more details, or a failing test, or a sample project with the error you are seeing.

There are quite a few existing tests using enum types so you could use one of them as the basis for a new test.

**Comment by jeffgbutler** [comment]
No response
