### ISSUE TITLE
postgresql jsonb字段生成后需要在配置项后添加::jsonb后缀

### ISSUE THREAD

**Issue by euler-king** [mybatis/generator#554]
postgresql jsonb字段生成后需要在配置项后添加::jsonb后缀
如：#{arrayInfos,jdbcType=VARCHAR,typeHandler=ListStringTypeHandler}::jsonb

**Comment by jeffgbutler** [comment]
Thanks for letting us know about this. I'll have to think about a good solution - and it will be different depending on the runtime you are using.

If you are using the legacy MyBatis3 runtime, then you are going to have to make these changes manually to the generated code.

If you using the MyBatis3DynamicSql runtime it is more difficult. I will need to make a change in that library to support this.

**Comment by jeffgbutler** [comment]
Will be resolved in MyBatis Dynamic SQL: https://github.com/mybatis/mybatis-dynamic-sql/issues/200
