### ISSUE TITLE
自动生成代码中注释的屏蔽

### ISSUE THREAD

**Issue by jason-liu379626076** [mybatis/generator#557]
配置了<property name="suppressAllComments" value="true"/>， 还是会自动生成

@Generated("org.mybatis.generator.api.MyBatisGenerator") 这个注释

**Comment by jeffgbutler** [comment]
I'm sorry, I don't understand what this means.

**Comment by jeffgbutler** [comment]
No response.

**Comment by clcy1243** [comment]
at 1.4.x, if you use MyBatis3DynamicSql,  this annotation will always generated, because commentGenerator not support DynamicSql runtime, I write a new CommentGenerator to fix this bug.
