### ISSUE TITLE
Can generate Raw ColumnName in domain class

### ISSUE THREAD

**Issue by Mumutu** [mybatis/generator#56]
hi~ 
 I want to build the xxxExample automatically with some string from a web control now is JQGrid, so the problem is the `setOrderByClause` method , for it needs the raw column name  not like the other `Criteria` method;
 I wonder is there any way to add the **raw column name** in domain class  with an annotation when we config `useActualColumnNames="false"` 
 Thanks

**Comment by jeffgbutler** [comment]
I'm sorry, but I'm not totally clear on what you are asking.

I will say that you can write a plugin to add extra information to the domain class.  The "modelFieldGenerated" method in a plugin is called for every column in the table.  You can use the IntrospectedColumn object to obtain the actual column name.

**Comment by Mumutu** [comment]
Thanks a lot   I am new to this .. sorry for bothering you~  I think your answer can solve my problem
