### ISSUE TITLE
生成多余mapper字段

### ISSUE THREAD

**Issue by tianly123** [mybatis/generator#560]
生成多余mapper字段造成Mapped Statements collection already contains value for

 ` <select id="selectByExampleWithRowbounds" parameterType="com.nige.comm.model.UserExample" resultMap="BaseResultMap">
    
    select
    <if test="distinct">
      distinct
    </if>
    <include refid="Base_Column_List" />
    from user
    <if test="_parameter != null">
      <include refid="Example_Where_Clause" />
    </if>
    <if test="orderByClause != null">
      order by ${orderByClause}
    </if>
  </select>
  <select id="selectByExampleWithRowbounds" parameterType="com.nige.comm.model.UserExample" resultMap="BaseResultMap">
  
  select
  <if test="distinct">
    distinct
  </if>
  <include refid="Base_Column_List" />
  from user
  <if test="_parameter != null">
    <include refid="Example_Where_Clause" />
  </if>
  <if test="orderByClause != null">
    order by ${orderByClause}
  </if>
</select>`‘
`
<dependency>
            <groupId>org.mybatis.generator</groupId>
            <artifactId>mybatis-generator-core</artifactId>
            <version>1.3.7</version>
        </dependency>
`

**Comment by tianly123** [comment]
`dd`

**Comment by tianly123** [comment]
error info: Mapped Statements collection already contains value for ****
Involved field："selectByExampleWithRowbounds" 
version:1.3.7
I have both tables, bu error only happens in one of them

**Comment by tianly123** [comment]
it is not painful, But I have to tell you

**Comment by jeffgbutler** [comment]
Did you disable all comments? This breaks the code merge and is the usual cause of a problem like this.
