### ISSUE TITLE
为什么生成的实体类的属性与表字段名顺序不一致？

### ISSUE THREAD

**Issue by waitshang** [mybatis/generator#562]
如图：
![image](https://user-images.githubusercontent.com/11643284/76823388-10b19500-684f-11ea-8fd2-f2bddbaaef69.png)
之前在覆盖的时候顺序都是一致的，换了系统后，顺序不一致了。

**Comment by jeffgbutler** [comment]
I don't really understand this issue. Are you using any generator plugins that might interfere with the order? The generator will use the columns in order received from the JDBC driver except for the following:

1. Primary Key columns will always be first
1. BLOB columns will always be last

**Comment by jeffgbutler** [comment]
No response
