### ISSUE TITLE
document typo in quickstart section

### ISSUE THREAD

**Issue by haydenzhourepo** [mybatis/generator#572]
document url : https://mybatis.org/generator/quickstart.html
 typo below:
![image](https://user-images.githubusercontent.com/21101605/79710958-1a6c6380-82f9-11ea-87da-b988171c722b.png)

Sample Configuration for MyBatis3  section  targetRuntime should be MyBatis3

**Comment by haydenzhourepo** [comment]
where is the document project i can submiit a pr

**Comment by jeffgbutler** [comment]
Thanks! The doc page is here:

https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/site/xhtml/quickstart.xhtml

**Comment by haydenzhourepo** [comment]
#573
