### ISSUE TITLE
commentGenerator label error

### ISSUE THREAD

**Issue by xidianzyf** [mybatis/generator#578]
I want to add the 
`<commentGenerator>
            <property name="addRemarkComments" value="true" />
        </commentGenerator>`
to
 
> generatorConfig.xml

but it doesn't work with this error:

> [ERROR] Failed to execute goal org.mybatis.generator:mybatis-generator-maven-plugin:1.4.0:generate (default-cli) on project hitao: XML Parser Error on line 40: 元素类型为 "xt" 的内容必须匹配 "(property*,plugin*,commentGenerator?,(connectionFactory|jdbcConnection),javaTypeResolver?,javaModelGenerator,sqlMapGenerator?,javaClientGenerator?,table -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

I don't know how to fix it, can you help me?
My total xml is
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration
        PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
        "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">

<generatorConfiguration>

    <context id="DB2Tables" targetRuntime="MyBatis3">
        <commentGenerator>
            <property name="addRemarkComments" value="true" />
        </commentGenerator>
        <plugin type="org.mybatis.generator.plugins.RowBoundsPlugin"></plugin>
        <jdbcConnection driverClass="com.mysql.jdbc.Driver"
                        connectionURL="jdbc:mysql://localhost:3306/hitao"
                        userId="root"
                        password="123456">
        </jdbcConnection>

        <javaTypeResolver>
            <property name="forceBigDecimals" value="false"/>
        </javaTypeResolver>

        <javaModelGenerator targetPackage="com.qingtai.hitao.model" targetProject="src/main/java">
            <property name="enableSubPackages" value="true"/>
            <property name="trimStrings" value="true"/>
        </javaModelGenerator>

        <sqlMapGenerator targetPackage="mapper" targetProject="src/main/resources">
            <property name="enableSubPackages" value="true"/>
        </sqlMapGenerator>

        <javaClientGenerator type="XMLMAPPER" targetPackage="com.qingtai.hitao.dao"
                             targetProject="src/main/java">
            <property name="enableSubPackages" value="true"/>
        </javaClientGenerator>

        <table tableName="t_user" domainObjectName="User"></table>
        <table tableName="t_goods" domainObjectName="Goods"></table>
        <table tableName="t_notification" domainObjectName="Notification"></table>
    </context>

</generatorConfiguration>`

and i ran the cmd `mvn -Dmybatis.generator.overwrite=true mybatis-generator:generate`

**Comment by jeffgbutler** [comment]
This is an XML parse error. Move `<commentGenerator>` after `<plugin>`.

With MySql, you will also need to add the `useInformationSchema` property to the JDBC URL.
