### ISSUE TITLE
commentGenerator  overide methoed addFieldComment can`t be invoked

### ISSUE THREAD

**Issue by 15702992009** [mybatis/generator#600]
public class CommentGenerator extends DefaultCommentGenerator {...}

System.out.println("CommentGenerator constructor is called ");
 System.out.println("addConfigurationProperties() is called ");
but override method addFieldComment() can`t  be invoked;

**Comment by 15702992009** [comment]
`
public class CommentGenerator extends DefaultCommentGenerator {
    private boolean addRemarkComments = false;

    public CommentGenerator() {
        System.out.println("CommentGenerator constructor is called ");
    }


    @Override
    public void addConfigurationProperties(Properties properties) {
       
        System.out.println("addConfigurationProperties is called ");
    }

    @Override
    public void addFieldComment(Field field,
                                IntrospectedTable introspectedTable,
                                IntrospectedColumn introspectedColumn) {
        System.out.println("addFieldComment is called ");
    }

}
`

CommentGenerator constructor is called 
addConfigurationProperties is called 
Existing file D:\jacob\libinfo\src\main\java\com\jacob\mbg\model\Sj100000.java was overwritten
Existing file D:\jacob\libinfo\src\main\java\com\jacob\mbg\mapper\Sj100000Mapper.java was overwritten
Existing file D:\jacob\libinfo\src\main\java\com\jacob\mbg\mapper\Sj100000DynamicSqlSupport.java was overwritten

**Comment by jeffgbutler** [comment]
It depends on what runtime you are using. That method is not called in the newer runtimes based on MyBatis Dynamic SQL. For that runtime, look to the *Annotation* methods in comment generator like `addFieldAnnotation`.

**Comment by jeffgbutler** [comment]
No response
