### ISSUE TITLE
TableConfiguration add attribute canNullStatementsEnabled

### ISSUE THREAD

**Issue by euler-king** [mybatis/generator#601]
TableConfiguration add an attribute canNullStatementsEnabled default value true;

private boolean canNullStatementsEnabled;

public boolean areAnyStatementsEnabled() {

        return canNullStatementsEnabled
                || selectByExampleStatementEnabled
                || selectByPrimaryKeyStatementEnabled || insertStatementEnabled
                || updateByPrimaryKeyStatementEnabled
                || deleteByExampleStatementEnabled
                || deleteByPrimaryKeyStatementEnabled
                || countByExampleStatementEnabled
                || updateByExampleStatementEnabled;

}

**Comment by jeffgbutler** [comment]
I don't understand - what is the purpose of this attribute? How would it be used?

**Comment by euler-king** [comment]
I config all current attribute enable = false;
so method areAnyStatementsEnabled() return false;
but I config self plugin to generator other file content or other mybatis xml tag

**Comment by euler-king** [comment]
> I don't understand - what is the purpose of this attribute? How would it be used?

I config all current attribute enable = false;
so method areAnyStatementsEnabled() return false;
but I config self plugin to generator other file content or other mybatis xml tag

**Comment by euler-king** [comment]
> I don't understand - what is the purpose of this attribute? How would it be used?

Can it be solved ？

**Comment by jeffgbutler** [comment]
I'm not clear on the use case. Are you trying to completely replace the built in generators? There are a couple of ways to accomplish that:

1. You could disable all the regular code generators in your plugin, and then create whatever artifacts you want in that same plugin
2. You could write a new runtime implementation that ignored those attributes and ran a custom code generator. In fact, this is exactly how the new runtimes for MyBatisDynamicSql work and you can see the code here: https://github.com/mybatis/generator/tree/master/core/mybatis-generator-core/src/main/java/org/mybatis/generator/runtime

In either case, you would not need to disable everything in XML, you could just do it in your plugin or runtime.

**Comment by jeffgbutler** [comment]
Another idea...the `<javaClientGenerator>` and `<sqlMapGenerator>` configuration elements are both optional. If you omit them, then only the model objects are generated (and plugin methods are called where you could generate something else).

In other words, there are many ways to accomplish different use cases with the generator as-is. If you let us know more about what you're trying to accomplish we can help.

**Comment by jeffgbutler** [comment]
No response or activity.
