### ISSUE TITLE
Why not consider the function of a federated query

### ISSUE THREAD

**Issue by signner** [mybatis/generator#602]
Why not consider the function of a federated query？It's a bit troublesome to implement the plug-in method by yourself, if you can perfect it.

**Comment by jeffgbutler** [comment]
Can you provide an example of what you would like generated?

**Comment by kaiqivvv** [comment]
Hi, I am katch, for example：select a.*, b.* from a left join b on a.id = b.aid where a.name like '%jame%' and b.age > 20  order by b.name,a.age limit 1,10, Can you consider implementation? thanks

**Comment by jeffgbutler** [comment]
@kaiqivvv  [MyBatis Dynamic SQL](https://mybatis.org/mybatis-dynamic-sql/) supports joins. If you change your runtime in the generator, you'll have almost everything you need - you'll just need to add a result map to match your query. Or you could write a generic mapper method that would work for any join like this:

```java
@SelectProvider(type=SqlProviderAdapter.class, method="select")
List<Map<String, Object>> generalSelect(SelectStatementProvider selectStatement);
```

The generator configuration looks like this:

```xml
<context targetRuntime="MyBatis3DynamicSql">
...
</context>
```

**Comment by jeffgbutler** [comment]
No response
