### ISSUE TITLE
Supporting to group multi columns in one Java Object

### ISSUE THREAD

**Issue by viinhpham** [mybatis/generator#614]
Do we have plan to support to group multi columns in one Java Object at <table>generation table, something like:

       <table tableName="user" domainObjectName="user">
       <groupColumn class ="a.b.c.User" >
            <columnOverride column="name"/>
            <columnOverride column="email" />
          <groupColumn>
        </table>

---------
```
package a.b.c;
public class User {
    private String name;
    private String mail
  //other stuffs
```
}

**Comment by jeffgbutler** [comment]
Do you mean that you want the generator to create nested objects? I don't plan to do that.

**Comment by jeffgbutler** [comment]
No response.
