### ISSUE TITLE
Why not  generated a insertMultipleSelective  method?

### ISSUE THREAD

**Issue by 411937647** [mybatis/generator#615]
Why not  generated a insertMultipleSelective  method?

And i remember there used to be a selectByEntity method,It's very useful. Why is it gone?

**Comment by jeffgbutler** [comment]
> Why not generated a insertMultipleSelect method?

Do you mean a multi-row insert? I could add that.

> And i remember there used to be a selectByEntity method,It's very useful. Why is it gone?

Do you mean the old `selectByExample` method? In the new runtime for MyBatis Dynamic SQL there is no longer an example class - the new general `select` method is far more powerful than `selectByExample`

**Comment by 411937647** [comment]
I'm sorry I didn't make myself clear.
I mean I mean it's generated  now is 'insertMultiple' ,and i need a 'insertMultipleSelective',just like 'insertSelective'.
It consists of 'toPropertyWhenPresent'  instead of  'toProperty'.

**Comment by jeffgbutler** [comment]
I don't think such a statement would work. You would end up with invalid SQL like this:

```sql
insert into foo(col1, col2, col3) values (?,?,?), (?,?), (?,?,?), (?) 
```

Were you thinking of something different than this?

**Comment by 411937647** [comment]
Thank you. It was my thoughtlessness。
