### ISSUE TITLE
SQL injection in order by clause

### ISSUE THREAD

**Issue by asnowfox** [mybatis/generator#621]
I reviewed the SQL generated by mybatis-generator, and I saw all the order by clause is looked like this:
    <if test="orderByClause != null">
      order by ${orderByClause}
    </if>
I think there will be a SQL injection security vulnerability in the order by clause.

Any suggestions?

**Comment by jeffgbutler** [comment]
The best option is to use a different runtime - "MyBatis3DynamicSql"

If you prefer one of the legacy runtimes, then you could disable the generation of select by example statements.

**Comment by asnowfox** [comment]
> The best option is to use a different runtime - "MyBatis3DynamicSql"
> 
> If you prefer one of the legacy runtimes, then you could disable the generation of select by example statements.

Thanks. But I am wondering Why not considering to solve this problem in the legacy runtime？

**Comment by jeffgbutler** [comment]
This problem isn't really solvable in the legacy runtime as databases generally do not allow bind parameters in "order by" clauses.

If you look at the support for the "by example" methods, you will also find quite a few strings that look like possible SQL injection. This is due to they way that the legacy runtime works. Removing this problem - and making the "by example" methods much better overall - was one of my primary motivations for creating a new runtime.

The only way to avoid this problem in the legacy runtime is to disable the "by example" statements. You can do that easily by using the "MyBatis3Simple" runtime - which is just the legacy runtime with no dynamic SQL generation.

**Comment by asnowfox** [comment]
If I change to MyBatis3DynamicSql engine. I think it will be a huge source code reconstruction. Is it OK to check the sort injection  like this: 
@Getter
@Setter
@AllArgsConstructor
public class PageQuery {
    int start;
    int limit;
    String sort;
    String keyword;

    public String sortBy() {
        if (sort == null)
            return null;
        sort = sort.trim();
        if ("".equalsIgnoreCase(sort))
            return null;

        if (sort.contains("`")) {
            throw new BusinessException(GlobalErrorCode.PARAMETER_ERROR);
        }
        String[] words = sort.split(",");
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < words.length; i++) {
            String w = words[i];
            sb.append("`").append(w).append("`,");
        }
        return sb.toString().substring(0, sb.length() - 1);
    }
}

Moreover, Is it possilbe to change generated code to do similar check or change the 

**setOrderByClause(String orderByClause)**

to 

**setOrderByClause(List<String> orderByClause)**

and build the SQL in mapper XML file to fix this security vulnerability ?

Thanks

**Comment by jeffgbutler** [comment]
It's a very good idea to do some kind of data sanitation - especially if the order by values could come from user input. There's a good article about it here: https://www.baeldung.com/sql-injection#user-data-sanitization. I like their column whitelist idea.

**Comment by asnowfox** [comment]
In my case I have more than 30 tables and some of them have to receive the parameter from user input.  I sanitated the order by input by add the “`”  character in proper position. I think and hope it will be safe enough.

Thanks jeffbutler and your great artifact.

**Comment by asnowfox** [comment]
In my case I have more than 30 tables and some of them have to receive the parameter from user input. I sanitated the order by input by add the “`” character in proper position. I think and hope it will be safe enough.

Thanks jeffbutler and your great artifact.
