### ISSUE TITLE
the problem with the same tablename in different db

### ISSUE THREAD

**Issue by saiyujs** [mybatis/generator#622]
![image](https://user-images.githubusercontent.com/62423061/92573966-14334f80-f2b9-11ea-9432-ab0fb47f21fd.png)
![image](https://user-images.githubusercontent.com/62423061/92574055-2f05c400-f2b9-11ea-9a66-1440b00efa44.png)

i need to mapping the testDB,but it map to the gponinformacionDB.i have set to use the testDB.

**Comment by jeffgbutler** [comment]
You can specify the specific catalog in the configuration:

```xml
<table catalog="test" tableName="billing"/>
```

**Comment by LittleShrimp1987** [comment]
```xml
<jdbcConnection driverClass="com.mysql.cj.jdbc.Driver"
                        connectionURL="jdbc:mysql://localhost:3306/testDB" userId="user"
                        password="password">
            <property name="nullCatalogMeansCurrent" value="true" />
        </jdbcConnection>
```

try this, may help

**Comment by jeffgbutler** [comment]
No response

**Comment by saiyujs** [comment]
thanks
