### ISSUE TITLE
Generate more code for "MyBatis3DynamicSql" runtime

### ISSUE THREAD

**Issue by a188037445** [mybatis/generator#633]
Need:
- a select method to return `List<Map<String, Object>>` type
- self join support

I know how to implement them by exploring issues in [mybatis-dynamic-sql](https://github.com/mybatis/mybatis-dynamic-sql) project, but it will be useful if the generator can generate them automatically.

**Comment by jeffgbutler** [comment]
As of version 1.2.1, MyBatis Dynamic SQL includes utility mappers with many common methods - including the select method you suggest. See this code: https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/main/java/org/mybatis/dynamic/sql/util/mybatis3/CommonSelectMapper.java

For self join, are you suggesting the generator create multiple "support" classes to enable the self join?

**Comment by a188037445** [comment]
Thank you.

> For self join, are you suggesting the generator create multiple "support" classes to enable the self join?

I think it is acceptable.

**Comment by jeffgbutler** [comment]
Honestly, I don't think the generator needs to do anything different for self-joins. You can do self-joins easily with what's already generated. Here's a good example: https://github.com/mybatis/mybatis-dynamic-sql/blob/master/src/test/java/examples/joins/JoinMapperTest.java#L838-L867

**Comment by a188037445** [comment]
Yes, it's a simple way to do self-joins, but I should new an object, for reusing the object, I should define it to a field variable, if I use self-joins in somewhere else, I should do this again.

So although this is an acceptable solution, but I think it's not good enough.

I suggest that we can add an option to `generatorConfig.xml`, which indicates if the generator should generate a self-join object for a table. The object can be a "user2" in `UserDynamicSQLSupport`, then we don't need two DynamicSQLSupport classes.

**Comment by jeffgbutler** [comment]
Newing up an object has virtually no penalty in modern Java, so I wouldn't be too concerned about it. The MyBatis Dynamic SQL library is nearly 100% immutable - which means there are many intermediate objects being created and thrown away during normal operations. Adding another one isn't going to make any noticeable difference.

If you really wanted to make a "permanent" object in the support class, you could accomplish that with a plugin - we wouldn't need to change anything in the generator.

**Comment by a188037445** [comment]
Very Good!

**Comment by a188037445** [comment]
Thank you, I'll try it later.
