### ISSUE TITLE
enum generator

### ISSUE THREAD

**Issue by Justmysteriousman** [mybatis/generator#635]
it's there any way to generate enum from db column of type enum?

**Comment by Justmysteriousman** [comment]
i have a column with enum type in mysql;by default,it will be char by the plugin

**Comment by jeffgbutler** [comment]
I think it would be difficult. Enum is not a standard JDBC type so the generator would not know about it. You would need to create the Java enum manually. Then you might try a column override to specify the type. You'll also need to specify a type handler for MyBatis.

**Comment by jeffgbutler** [comment]
No response
