### ISSUE TITLE
not generate insertMultiple method

### ISSUE THREAD

**Issue by xyting** [mybatis/generator#636]
I using version 1.4.0 to generate MyBatis3DynamicSql codes, but the generated code without the `insertMultiple` method

**Comment by jeffgbutler** [comment]
Are you using the `MyBatis3DynamicSqlV1` runtime? That runtime doesn't generate insertMultiple. Also, that runtime will be deleted in the next release.

**Comment by xyting** [comment]
using `MyBatis3DynamicSql`

**Comment by jeffgbutler** [comment]
Please post your config.

**Comment by jeffgbutler** [comment]
If you are using generated keys, but not the JDBC standard generated key, that will also block the method from being generated. MyBatis only supports generated key on multi-row inserts with the JDBC standard.

**Comment by jeffgbutler** [comment]
No response

**Comment by xyting** [comment]
> Please post your config.

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE generatorConfiguration
        PUBLIC "-//mybatis.org//DTD MyBatis Generator Configuration 1.0//EN"
        "http://mybatis.org/dtd/mybatis-generator-config_1_0.dtd">
<generatorConfiguration>
    <properties resource="generator.properties"/>
    <context id="MySQL" targetRuntime="MyBatis3DynamicSql" defaultModelType="flat">
        <property name="beginningDelimiter" value="`"/>
        <property name="endingDelimiter" value="`"/>
        <property name="javaFileEncoding" value="UTF-8"/>
        <plugin type="org.mybatis.generator.plugins.SerializablePlugin"/>
        <plugin type="org.mybatis.generator.plugins.ToStringPlugin"/>
        <plugin type="org.mybatis.generator.plugins.FluentBuilderMethodsPlugin"/>
        <plugin type="org.mybatis.generator.plugins.EqualsHashCodePlugin"/>
        <commentGenerator type="com.a.b.MySQLCommentGenerator">
            <property name="addApiSchema" value="false" />
            <property name="addRemarkComments" value="true" />
        </commentGenerator>
        <jdbcConnection driverClass="${jdbc.driverClass}"
                        connectionURL="${jdbc.connectionURL}"
                        userId="${jdbc.userId}"
                        password="${jdbc.password}">
            <property name="nullCatalogMeansCurrent" value="true"/>
            <property name="useInformationSchema" value="true" />
        </jdbcConnection>
        <javaTypeResolver>
            <property name="forceBigDecimals" value="false"/>
            <property name="useJSR310Types" value="true"/>
        </javaTypeResolver>
        <javaModelGenerator targetPackage="com.a.b.model"
                            targetProject="src/main/java">
            <property name="trimStrings" value="true"/>
        </javaModelGenerator>
        <javaClientGenerator targetPackage="com.a.b.mapper"
                             targetProject="src/main/java"/>
        <table tableName="%">
            <generatedKey column="id" sqlStatement="MySql" identity="true"/>
        </table>
    </context>
</generatorConfiguration>

**Comment by jeffgbutler** [comment]
The `<generatedKey...>` is the problem. InsertMultiple only works with JDBC standard generated values.

**Comment by xyting** [comment]
> The `<generatedKey...>` is the problem. InsertMultiple only works with JDBC standard generated values.

Thanks, I think the doc should be updated to mention this
