### ISSUE TITLE
Cannot assign package for *DynamicSqlSupport.java files.

### ISSUE THREAD

**Issue by wuweiran** [mybatis/generator#637]
In Dynamic SQL mode, the generator cannot assign package for *DynamicSqlSupport.java files.
```
<javaClientGenerator targetPackage="x.mapper" targetProject="src/main/java">
    <property name="enableSubPackages" value="false"/>
</javaClientGenerator>
<table tableName="a" mapperName="b.AMapper">
    <generatedKey column="id" sqlStatement="MySql" identity="true"/>
</table>
```
For example, the above configuration does not generate AMapperDynamicSqlSupport.java in the same package as that of AMapper.java file. This will cause that all mappers are in different packages as we want, while the dynamic SQL support files remains in the root package unorganized.
An extra attribute of `<table>` or generating support files in the same package with mappers by default would be good to solve the issue.

**Comment by jeffgbutler** [comment]
I'll add something for this in the next release.
