### ISSUE TITLE
please help me....

### ISSUE THREAD

**Issue by steveGuRen** [mybatis/generator#64]
When I use the generator to generate java model bean, all the field in java bean is used lowercase.That's diffierent from the name of my database.I just want to the field name in java bean the same as my database.How to do it ? —  —、、I hava google, but have not answer.

**Comment by sshic** [comment]
try not to use uppercase letters while defining database table names, it cause problems a lot circumstances

**Comment by jeffgbutler** [comment]
Please use the mailing list for questions.

But look at the "useActualColumnNames" property on the `<table>` element.

http://www.mybatis.org/generator/configreference/table.html
