### ISSUE TITLE
Using "enableSelectByExample" Can Cause Errors in DSQL Runtime

### ISSUE THREAD

**Issue by xingda** [mybatis/generator#647]
# MyBatis version
not for sure, I'm reporting a bug of MyBatis generator.

# MyBatis generator version
1.4.0

## Database vendor and version
MySql Ver 8.0.21 for Win64 on x86_64

## Test case or example project
N/A

## Steps to reproduce
1. Config my own generatorConfig.xml
2. Use the default TargetRuntime - MyBatis3DynamicSql
3. Define table property with parameters like following:
```xml
<table tableName="mytable" domainObjectName="MyTable" enableCountByExample="false"
 enableUpdateByExample="false" enableDeleteByExample="false" enableSelectByExample="false"
 selectByExampleQueryId="false"></table>
```

## Expected result
The generated code can be built successfully

## Actual result
Build reports error - "Result Maps collection already contains value for yourpackage.mapper.MyTableMapper.MyTableResult

## Cause analysis
In the config file, the property of table's parameters, like enableSelectByExample or selectByExampleQueryId, may cause the error. After I remove those parameters, the generated mapper class is built well.
In the generator offficial documet, it says those parameters should be ignored when the target runtime is mybatis3dynamicsql. But it seems not like that, please help to check it out.

**Comment by jeffgbutler** [comment]
This is related to the use of `enableSelectByExample="false"`. As stated, this attribute should be ignored in the DSQL runtime. But it is being improperly used to determine whether to reuse a result map.

@xingda Thanks for reporting this!

**Comment by xingda** [comment]
@jeffgbutler Thanks for solving this.
