### ISSUE TITLE
The generator can not get the database column's comment?

### ISSUE THREAD

**Issue by jatesun** [mybatis/generator#65]
Hello,sorry to bother you.Here is the thing,I try to modify the generator .But I found it can not get database column's comment(I'm sure that the column has comment).Is there anything that I can't notice???Thank you very much

**Comment by a-n-ermakov** [comment]
You can use option "addRemarkComments" (completed in PR #43) for standard DefaultCommentGenerator. But this feature not released yet, so you have to clone and compile master branch to use such functionality.

**Comment by jatesun** [comment]
ok,thank you.I'll try it

**Comment by zscgrhg** [comment]
cant not get database column's comment for oracle 11g

**Comment by zscgrhg** [comment]
<jdbcConnection driverClass="${dbDriver}"
                        connectionURL="${dbUrl}"
                        userId="${dbUser}"
                        password="${dbPass}">
            
            <property name="remarksReporting" value="true"></property>
        </jdbcConnection>

**Comment by zscgrhg** [comment]
<jdbcConnection >
            
            <property name="remarksReporting" value="true"></property>
        </jdbcConnection>
