### ISSUE TITLE
Oracle table field type NVARCHAR2 turn 2 Object,is not String.

### ISSUE THREAD

**Issue by mrgao0612** [mybatis/generator#663]
please tell me, how should i solve this issue?think you very much!

**Comment by jeffgbutler** [comment]
Do you mean that `NVARCHAR2` columns are generated as attributes of type `Object`? If so, you can use a `<columnOverride>` to specify the type you prefer. For example:

```xml
<table tableName="foo">
  <columnOverride column="bar" javaType="java.lang.String" />
</table>
```

**Comment by jeffgbutler** [comment]
No response.
