### ISSUE TITLE
getGetterMethodName treat java.lang.Boolean as isXYZ() instead of getXYZ()

### ISSUE THREAD

**Issue by snojcb** [mybatis/generator#676]
In org.mybatis.generator.internal.util.JavaBeansUtil.getGetterMethodName(String property, FullyQualifiedJavaType fullyQualifiedJavaType)

This code:

```
        if (fullyQualifiedJavaType.equals(FullyQualifiedJavaType
                .getBooleanPrimitiveInstance())) {
            sb.insert(0, "is"); //$NON-NLS-1$
        } else {
            sb.insert(0, "get"); //$NON-NLS-1$
        }
```
treats primitive boolean types as resulting in isXYZ() getter names.  Shouldn't java.lang.Boolean types also be treated as isXYZ()??

```
        if (fullyQualifiedJavaType.equals(FullyQualifiedJavaType.getBooleanPrimitiveInstance()) ||
        		fullyQualifiedJavaType.equals(new FullyQualifiedJavaType("java.lang.Boolean"))) {
            sb.insert(0, "is"); //$NON-NLS-1$
        } else {
            sb.insert(0, "get"); //$NON-NLS-1$
        }
```

Thank you for considering this issue.

**Comment by jeffgbutler** [comment]
The JavaBeans specification only allows "is" accessors for primitive boolean fields. This hasn't been updated for auto-boxing. I've also confirmed that Eclipse, IntelliJ, and Lombok still follow the convention that "is" only applies to primitive booleans.
