### ISSUE TITLE
Missing @Mapper annotation in XXMapper.java when using targetruntime=MyBatis3 by Gradle

### ISSUE THREAD

**Issue by xingda** [mybatis/generator#678]
### Precondition:
1. making tool is Gradle v6.8.2
2. genetor is gradle.plugin.com.arenagod.gradle:mybatis-generator-plugin:1.4
### generatorConfig.xml is like following:
.....
"context id="xxxx" targetRuntime="MyBatis3""
.....
"javaClientGenerator targetPackage="com.example.mapper"
                             targetProject="src/main/java"
                             type="ANNOTATEDMAPPER" "
"table tableName="user" domainObjectName="User" enableCountByExample="false"  enableDeleteByExample="false" enableSelectByExample="false" enableUpdateByExample="false" "
### UserMapper.java like this:

public interface UserMapper {
....
}
### Expected result:
@Mapper
public interface UserMapper {
}

**Comment by jeffgbutler** [comment]
There is a plugin for this:

```xml
<plugin type="org.mybatis.generator.plugins.MapperAnnotationPlugin"/>
```
