### ISSUE TITLE
Something is wrong with doc of <table> Element  rootInterface property

### ISSUE THREAD

**Issue by redmark** [mybatis/generator#689]
The document said:  rootInterface, | This property is ignored is the target runtime is "MyBatis3DynamicSql" or "MyBatis3Kotlin".
But  the rootInterface property still woks actually in 1.4 version ,  maybe the document is wrong.  I think the function is useful, don't drop it please.

**Comment by jeffgbutler** [comment]
@redmark You are correct - it is only ignored by Kotlin. Thanks for reporting this!
