### ISSUE TITLE
Failed to get table comment in mysql.

### ISSUE THREAD

**Issue by medusar** [mybatis/generator#714]
Mybatis generator failed to get table remarks in mysql.

I have created a table in mysql:
```
create table my_table(
 //ignore useless fields.
) comment 'my table for test'
```
[Code in DatabaseIntrospector](https://github.com/mybatis/generator/blob/ceb4b65a500b65a2aa2ebea7c5d9538db6ee75a1/core/mybatis-generator-core/src/main/java/org/mybatis/generator/internal/db/DatabaseIntrospector.java#L639) failed to get the right comment for my table, because it uses `rs.getString("REMARKS")`, it seems changing `"REMARKS"` to `"TABLE_COMMENT"` will work.

**Comment by jeffgbutler** [comment]
"REMARKS" is the JDBC standard so we won't change that.

Try setting a connection property `useInformationSchema=true` in the connection URL - this is a well known issue with MySQL.
