### ISSUE TITLE
There is no getter for property named 'distinct' in 'class com.xxx.domain.SysUserExample$Criteria

### ISSUE THREAD

**Issue by zhoulei4652** [mybatis/generator#717]
SysUserMapper.java in dao layer
one of generated method as below
```java
List<SysUser> selectByExample(SysUserExample.Criteria example);
```
when I invoke this method, it will throw below execption
```
There is no getter for property named 'distinct' in 'class com.xxx.domain.SysUserExample$Criteria
```

I need to manully modify parameter from ```SysUserExample.Criteria example``` to ```SysUserExample example```

and then, it will run properly.

my test code
```java
    @Test
    public void testGeneratorMyBatis3Simple() throws IOException {
        InputStream resource = Resources.getResourceAsStream("sqlMapConfig.xml");
        SqlSessionFactory sqlSessionFactory = new SqlSessionFactoryBuilder().build(resource);
        SqlSession sqlSession = sqlSessionFactory.openSession();
        SysUserMapper mapper = sqlSession.getMapper(SysUserMapper.class);
        // SysUser sysUser = mapper.selectByPrimaryKey((long) 30);

        SysUserExample example = new SysUserExample();
        SysUserExample.Criteria criteria = example.createCriteria();
        criteria.andEmailEqualTo("126.com");
       // List<SysUser> users = mapper.selectByExample(example);
        List<SysUser> users = mapper.selectByExample(criteria);
        System.out.println(users);
        sqlSession.close();
    }
```

mybatis: 3.4.5
mybaits-generator: 1.4.0

**Comment by jeffgbutler** [comment]
As you have seen, the "distinct" property is in the `Example` class - not the `Criteria` class.

Are you using any generator plugins? By default the generator creates `selectByExample(XXXExample example)` methods, not  `selectByExample(XXXExample.Criteria example)` - this has been true for years.

**Comment by zhoulei4652** [comment]
you are right, the code was modified by other plugins.

thanks for your timely response and support.
