### ISSUE TITLE
MyBatis3DynamicSql target runtime causes a name collision warning for tables with identically named columns

### ISSUE THREAD

**Issue by mahiarmody** [mybatis/generator#724]
When using the MyBatis3DynamicSql target runtime for the MyBatis Generator (mbg), if a table contains a column having the same name as the table name, mbg reports the following warning:
`Shortcut field for SQLColumn "xxxx" skipped in class com.aaa.bbb.FooBarDynamicSqlSupport due to name collision`

To fix this I would propose that the word "Table" be appended to the name of generated static inner class instance variable (rather than keeping it as only the table name) so that the conflict with the dynamically generated column of the same name is avoided.

For example, say I have the following table:

> create table **Owner_Type**
(
	owner_type_id IDENTITY(1,1) not null constraint Owner_Type__owner_type_id__PK Primary Key,
	**owner_type** Varchar_ignorecase(50) not null,
	owner_type_tag varchar(5) not null
);

MyBatis Generator config file:
> &lt;context id="xxxxx" targetRuntime="**MyBatis3DynamicSql**"&gt;
.......
.....
&lt;table catalog="xxx" schema="public" tableName="Owner_Type" domainObjectName="**OwnerType**"&gt;
.....
			&lt;columnOverride column="owner_type" property="**ownerType**" /&gt;
		&lt;/table&gt;

Upon running the mbg the following warning is reported:

`Shortcut field for SQLColumn "ownerType" skipped in class xxxx.yyy.generated.OwnerTypeDynamicSqlSupport due to name collision 
`

The generated Java code is
```
public final class OwnerTypeDynamicSqlSupport {
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-09T16:06:54.788677-10:00", comments="Source Table: xxx.PUBLIC.OWNER_TYPE")
    public static final OwnerType ownerType = new OwnerType();

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-09T16:06:54.788865-10:00", comments="Source field: xxx.PUBLIC.OWNER_TYPE.OWNER_TYPE_ID")
    public static final SqlColumn<Long> ownerTypeId = ownerType.ownerTypeId;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-09T16:06:54.789079-10:00", comments="Source field: xxx.PUBLIC.OWNER_TYPE.OWNER_TYPE_TAG")
    public static final SqlColumn<OwnerTypeTag> ownerTypeTag = ownerType.ownerTypeTag;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-09T16:06:54.788784-10:00", comments="Source Table: xxx.PUBLIC.OWNER_TYPE")
    public static final class OwnerType extends SqlTable {
        public final SqlColumn<Long> ownerTypeId = column("OWNER_TYPE_ID", JDBCType.BIGINT);

        public final SqlColumn<OwnerType> ownerType = column("OWNER_TYPE", JDBCType.VARCHAR);

        public final SqlColumn<OwnerTypeTag> ownerTypeTag = column("OWNER_TYPE_TAG", JDBCType.VARCHAR);

        public OwnerType() {
            super("xxx.PUBLIC.OWNER_TYPE");
        }
    }
}
```

As is evident, the the shortcut field **SqlColumn&lt;OwnerType&gt; ownerType** is not generated because it would conflict with the name of instance variable of the static inner class viz. **ownerType**

To prevent this collision, would it be possible to append the word "Table" to the name of the static inner class instance variable, thereby changing:
>    public static final OwnerType **ownerType** = new OwnerType();

To

>    public static final OwnerType **ownerType*Table*** = new OwnerType();

**Comment by jeffgbutler** [comment]
Appending table would not fix this in all cases. What if there was a table like this:

```sql
create table foo (
  id int not null,
  fooTable varchar(50) not null
)
```

Name conflicts are inevitable and the way the generator is currently coded handles conflicts in a consistent manner. So we won't be implementing this change.
