### ISSUE TITLE
"The connection attempt failed" when including username and password in database URL

### ISSUE THREAD

**Issue by wbt** [mybatis/generator#731]
In [the jdbcConnection element](http://mybatis.org/generator/configreference/jdbcConnection.html), when an all-alphanumeric userId and password are included in the URL (whether or not the userId and password are included as separate parameters), I get an error like the following: 
>“Failed to execute goal org.mybatis.generator:mybatis-generator-maven-plugin:1.4.0:generate (Generate MyBatis Artifacts) on project myproject: The connection attempt failed.”

An example URL structure which works is 
```
    <jdbcConnection
      driverClass="org.postgresql.Driver"
      connectionURL="jdbc:postgresql://localhost:5432/postgres?currentSchema=myschema"
      userId="myDBusername"
      password="myDBpassword2"
    />
```

An example URL structure which produces the error is:
```
    <jdbcConnection
      driverClass="org.postgresql.Driver"
      connectionURL="jdbc:postgresql://myDBusername:myDBpassword2@localhost:5432/postgres?currentSchema=myschema"
    />
```

When using certain environments (e.g. Heroku), this data can come from a dynamically updated database URL environment variable including the username and password, while there are not separate variables with just that information.  Thus, it's important to be able to parse username and password from the 'connectionURL' attribute.

**Comment by jeffgbutler** [comment]
The generator does not parse the connectionURL - it is passed directly to the driver. So you must use the driver specific means of supplying userID and password on the URL. You can see examples here: https://jdbc.postgresql.org/documentation/head/connect.html

Looks like you should use the following:

```
<jdbcConnection driverClass="org.postgresql.Driver"
  connectionURL="jdbc:postgresql://localhost:5432/postgres?currentSchema=myschema&user=myDBusername&password=myDBpassword"
/>
```

**Comment by wbt** [comment]
Thanks for your helpful answer; that solved it!
