### ISSUE TITLE
how to set targetProject ?

### ISSUE THREAD

**Issue by ft20082** [mybatis/generator#733]
directory tree:
```
pom.xml
module1/
          -- pom.xml
          -- src/main/java/....
          -- src/main/resource/mybatis-config.xml
```
mybatis generate config in module1/src/main/resurce/

how to set targetProject when do mvn command in  root.xml path and mvn command in project1.xml path ?

**Comment by jeffgbutler** [comment]
Where do you want the generated files written? If you use the special value `targetProject="MAVEN"` and the files will be written to `module1/target/generated-sources/mybatis-generator`.

**Comment by jeffgbutler** [comment]
No response

**Comment by yanjia92** [comment]
> Where do you want the generated files written? If you use the special value `targetProject="MAVEN"` and the files will be written to `module1/target/generated-sources/mybatis-generator`.

@jeffgbutler if I want to place files in module1/src/main/java, how should I set targetProject? I'm using Windows
