### ISSUE TITLE
idea "add contextGenerateAdditionalFiles() contextGenerateAdditionalFiles(IntrospectedTable introspectedTable) methods to plugin interface"

### ISSUE THREAD

**Issue by ningpp** [mybatis/generator#752]
```
    default List<GeneratedFile> contextGenerateAdditionalFiles() {
        return Collections.emptyList();
    }

    default List<GeneratedFile> contextGenerateAdditionalFiles(IntrospectedTable introspectedTable) {
        return Collections.emptyList();
    }
```

have these method ,  we can generate openapi definition ,  generate proto ...

**Comment by jeffgbutler** [comment]
There are existing methods similar to these that you can use to generate Java, XML, and Kotlin files. These are the only file types understood by the generator. Is there some reason you cannot use the existing methods?

**Comment by ningpp** [comment]
I write a plugin generate open api definition file(json format).
