### ISSUE TITLE
Generate selectByPrimaryKeys(TID[])

### ISSUE THREAD

**Issue by djechelon** [mybatis/generator#758]
It would be a lot useful, along with the auto-generated `selectByPrimaryKey` in the auto-generated Java mappers, to generate a method that returns a collection of entities selected by multiple primary key values.

That would translate into `SELECT --- WHERE _id_ IN (?,?,?,?)`

And yes, I **could** try on my own to implement a plugin for that, but I really have no clue where the code that generates the regular `selectByPrimaryKey` is located.

I'm using `MyBatis3DynamicSql`

**Comment by jeffgbutler** [comment]
This would be a simple method to generate in a plugin. The only issue is that it probably should only be generated if there is a single column in the primary key. The generated method could look like this:

```java
    default List<Foo> selectByPrimaryKeys(List<Integer> ids) {
        return select(c -> c.where(id, isIn(ids)));
    }
```

You could use this class as a model (it's where the `selectByPrimaryKey` method is generated): https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/main/java/org/mybatis/generator/runtime/dynamic/sql/elements/SelectByPrimaryKeyMethodGenerator.java

**Comment by djechelon** [comment]
What if I make a change to Mybatis code and open a pull request? Could it go to the future version?

I agree with the single column constraint

**Comment by jeffgbutler** [comment]
I think this should be done in a plugin. You could publish your plugin on the wiki page here: https://github.com/mybatis/generator/wiki/Third-Party-Tools

**Comment by djechelon** [comment]
Please, there is truly something I would like to be explained (and then we will close this issue).

You and the source code of the generator refer to `select( LAMBDA EXPRESSION )`, but all my methods are generate differently.

Example

```java
    @Generated("org.mybatis.generator.api.MyBatisGenerator")
    default User selectByPrimaryKey(Integer userid_) {
        return SelectDSL.selectWithMapper(this::selectOne, userid, userfirstname, userlastname, useremail, usercreated, usercreatedby, userupdated, userupdatedby)
                .from(user)
                .where(userid, isEqualTo(userid_))
                .build()
                .execute();
    }

```


My configuration


```xml
    <context id="amlc_auth" targetRuntime="MyBatis3DynamicSql" defaultModelType="hierarchical">
        <plugin type="org.mybatis.generator.plugins.RowBoundsPlugin"/>
        <plugin type="it.orbit.mybatis.plugins.LombokPlugin">

            <property name="getter" value="true"/>
            <property name="setter" value="true"/>
            <property name="accessors" value="true"/>
            <property name="accessors.chain" value="true"/>
            <!-- annotation's option(array of String) -->

            <!-- disable annotations -->
            <property name="noArgsConstructor" value="true"/>
            <property name="allArgsConstructor" value="true"/>
        </plugin>
        <commentGenerator>
            <property name="suppressDate" value="true"/>
            <property name="suppressAllComments" value="true"/>
        </commentGenerator>

        <jdbcConnection driverClass="${jdbcDriverClass}"
                        connectionURL="${jdbcUrl}"
                        userId="${jdbcUsername}"
                        password="${jdbcPassword}"
        >
            <property name="nullCatalogMeansCurrent" value="true"/>
        </jdbcConnection>

        <javaTypeResolver type="org.mybatis.generator.internal.types.JavaTypeResolverDefaultImpl">
            <property name="useJSR310Types" value="true"/>
        </javaTypeResolver>

        <javaModelGenerator targetPackage="it.orbit.amlc.backend.data.entities"
                            targetProject="${workingDir}/src/main/java"/>

        <javaClientGenerator targetPackage="it.orbit.amlc.backend.data.mappers"
                             targetProject="${workingDir}/src/main/java" type="ANNOTATEDMAPPER"/>

        <table tableName="Users" domainObjectName="User" mapperName="UserBaseMapper">
            <property name="rootInterface" value="it.orbit.common.data.mappers.BaseMapper&lt;User,Integer&gt;"/>
            <generatedKey column="UserId" identity="true" sqlStatement="JDBC"/>
            <columnOverride column="UserCreated" jdbcType="TIMESTAMP_WITH_TIMEZONE" javaType="java.time.OffsetDateTime"/>
            <columnOverride column="UserUpdated" jdbcType="TIMESTAMP_WITH_TIMEZONE" javaType="java.time.OffsetDateTime"/>
        </table>

        <table tableName="Roles" domainObjectName="Role" mapperName="RoleBaseMapper">
            <property name="rootInterface" value="it.orbit.common.data.mappers.BaseMapper&lt;Role,String&gt;"/>
            <columnOverride column="RoleCreated" jdbcType="TIMESTAMP_WITH_TIMEZONE" javaType="java.time.OffsetDateTime"/>
            <columnOverride column="RoleUpdated" jdbcType="TIMESTAMP_WITH_TIMEZONE" javaType="java.time.OffsetDateTime"/>
        </table>

        <table tableName="RolePermissions" domainObjectName="RolePermission" mapperName="RolePermissionBaseMapper">
            <property name="rootInterface" value="it.orbit.common.data.mappers.BaseMapper&lt;RolePermission,Short&gt;"/>
            <generatedKey column="RolePermissionId" identity="true" sqlStatement="JDBC"/>
        </table>

        <table tableName="UserRoles" domainObjectName="UserRole" mapperName="UserRoleBaseMapper">
            <property name="rootInterface" value="it.orbit.common.data.mappers.BaseMapper&lt;UserRole,Integer&gt;"/>
        </table>

    </context>
```


The lambda looks damn cool as I want to do implementations that create such an expression dynamically based on a filter.

Do I bother too much if I ask why I don't see any lambda like yours above in my generated code?

Thanks

**Comment by jeffgbutler** [comment]
It looks like you might be using an older version of the generator. If you upgrade to version 1.4.0, you will see a different method generated that looks like this:

```java
    default Optional<Foo> selectByPrimaryKey(Integer id_) {
        return selectOne(c ->
            c.where(id, isEqualTo(id_))
        );
    }
```

I think it looks cool too!

You will also need to upgrade the version of MyBatis Dynamic SQL.

**Comment by jeffgbutler** [comment]
BTW - please read the release notes for version 1.4.0 - there were quite a lot of changes in that release. http://mybatis.org/generator/whatsNew.html

**Comment by djechelon** [comment]
Ok, for sake of discussion.

I discovered that Telenia's [Gradle Mybatis Plugin](https://github.com/teleniasoftware/mybatis-generator-plugin) uses an older version of the generator, and that I incorrectly tried to force it to use the most recent.

Now it works as expected, so I can start hacking to create a plugin
