### ISSUE TITLE
plugin will auto generate xxx.java.1 file

### ISSUE THREAD

**Issue by tim232385** [mybatis/generator#768]
I already set overwrite tag to false
My model name `TUser` is exist, after plugins run, i get `xxx.java.1` file in my targetPackage.
how to disable gen this file (xxx.java.1, xxx.java.2)

    <groupId>org.mybatis.generator</groupId>    
    <artifactId>mybatis-generator-maven-plugin</artifactId>    
    <version>1.3.7</version>  
	<configuration>
        <verbose>false</verbose>
        <overwrite>false</overwrite>
    </configuration>
    
![未命名](https://user-images.githubusercontent.com/25591501/141752011-151453d3-7ab0-4047-b3d8-2821242e6c48.png)

**Comment by jeffgbutler** [comment]
If you set overwrite to "true", then these files will not be generated.
