### ISSUE TITLE
session table can not generator correctly

### ISSUE THREAD

**Issue by ft20082** [mybatis/generator#781]
db table 
```
CREATE TABLE `session` (
  ....
) ENGINE=MEMORY DEFAULT CHARSET=utf8mb4;
```

but generator properties is:
```
/**
     * 
     * thd_id
     */
    private Long thdId;

    /**
     * 
     * conn_id
     */
    private Long connId;

    /**
     * 
     * user
     */
    private String user;

    /**
     * 
     * db
     */
    private String db;

    /**
     * 
     * command
     */
    private String command;

    /**
     * 
     * state
     */
    private String state;

    /**
     * 
     * time
     */
    private Long time;

    /**
     * 
     * progress
     */
    private BigDecimal progress;

    /**
     * 
     * rows_examined
     */
    private Long rowsExamined;

    /**
     * 
     * rows_sent
     */
    private Long rowsSent;

    /**
     * 
     * rows_affected
     */
    private Long rowsAffected;

    /**
     * 
     * tmp_tables
     */
    private Long tmpTables;

    /**
     * 
     * tmp_disk_tables
     */
    private Long tmpDiskTables;

    /**
     * 
     * full_scan
     */
    private String fullScan;

    /**
     * 
     * last_wait
     */
    private String lastWait;

    /**
     * 
     * source
     */
    private String source;

    /**
     * 
     * trx_state
     */
    private String trxState;

    /**
     * 
     * trx_autocommit
     */
    private String trxAutocommit;

    /**
     * 
     * pid
     */
    private String pid;

    /**
     * 
     * program_name
     */
    private String programName;
```

config is:
```
<table tableName="session" alias="session" domainObjectName="Session" >
            <property name="useActualColumnNames" value="false"/>
</table>
```

**Comment by jeffgbutler** [comment]
What is incorrect? There's not enough information here to understand the issue.

**Comment by ft20082** [comment]
> What is incorrect? There's not enough information here to understand the issue.
column, the generated column may virtual table, it is not the session table column

**Comment by ft20082** [comment]
session is reserved word ? how to set if want to use ?

**Comment by ft20082** [comment]
[DEBUG] Found column "thd_id", data type -5, in table "sys..session"
[DEBUG] Found column "conn_id", data type -5, in table "sys..session"
[DEBUG] Found column "user", data type 12, in table "sys..session"
[DEBUG] Found column "db", data type 12, in table "sys..session"
[DEBUG] Found column "command", data type 12, in table "sys..session"
[DEBUG] Found column "state", data type 12, in table "sys..session"
[DEBUG] Found column "time", data type -5, in table "sys..session"
[DEBUG] Found column "current_statement", data type -1, in table "sys..session"
[DEBUG] Found column "statement_latency", data type -1, in table "sys..session"
[DEBUG] Found column "progress", data type 3, in table "sys..session"
[DEBUG] Found column "lock_latency", data type -1, in table "sys..session"
[DEBUG] Found column "rows_examined", data type -5, in table "sys..session"
[DEBUG] Found column "rows_sent", data type -5, in table "sys..session"
[DEBUG] Found column "rows_affected", data type -5, in table "sys..session"
[DEBUG] Found column "tmp_tables", data type -5, in table "sys..session"
[DEBUG] Found column "tmp_disk_tables", data type -5, in table "sys..session"
[DEBUG] Found column "full_scan", data type 12, in table "sys..session"
[DEBUG] Found column "last_statement", data type -1, in table "sys..session"
[DEBUG] Found column "last_statement_latency", data type -1, in table "sys..session"
[DEBUG] Found column "current_memory", data type -1, in table "sys..session"
[DEBUG] Found column "last_wait", data type 12, in table "sys..session"
[DEBUG] Found column "last_wait_latency", data type -1, in table "sys..session"
[DEBUG] Found column "source", data type 12, in table "sys..session"
[DEBUG] Found column "trx_latency", data type -1, in table "sys..session"
[DEBUG] Found column "trx_state", data type 1, in table "sys..session"
[DEBUG] Found column "trx_autocommit", data type 1, in table "sys..session"
[DEBUG] Found column "pid", data type 12, in table "sys..session"
[DEBUG] Found column "program_name", data type 12, in table "sys..session"

**Comment by ft20082** [comment]
找到了解决的办法，设置下 table 属性 catalog，应该在文档里标注出，sys.  catalog 下都有哪些表，这样的话，比较容易搞清楚

**Comment by ft20082** [comment]
sys..session table is in druid table

**Comment by ft20082** [comment]
<jdbcConnection driverClass="com.mysql.jdbc.Driver" connectionURL="jdbc:mysql://localhost/my_schema"
            userId="my_user" password="my_password">
        <property name="nullCatalogMeansCurrent" value="true" />
    </jdbcConnection>
