### ISSUE TITLE
Are there any plans to create MultipleInsertSelective?

### ISSUE THREAD

**Issue by ko-sasaki** [mybatis/generator#808]
Are there any plans to create MultipleInsertSelective?

I haven't been able to use MultipleInsert effectively because it specifies all columns.

**Comment by jeffgbutler** [comment]
I haven't considered it because I don't think it would generate valid SQL. Perhaps I'm missing something. Can you provide an example of the kind of SQL statement that you would like to see?

**Comment by jeffgbutler** [comment]
No response
