### ISSUE TITLE
[BUG]find the same tablename but not the schema has been set

### ISSUE THREAD

**Issue by mykright** [mybatis/generator#816]
`<table schema="way" tableName="person" >
            <property name="useActualColumnNames" value="false"/>
            <generatedKey column="id" sqlStatement="MySql" identity="true" />
        </table>`

in DB_A,I create two schema,named `key` and `way`.
and in both of them ,there is a table named person.

I have set the schema of DB,but it doesn't work.
it always generator the table in `key`

**Comment by jeffgbutler** [comment]
Please see this documentation page for advice related to MySQL: https://mybatis.org/generator/usage/mysql.html
