### ISSUE TITLE
Support translations on reference doc

### ISSUE THREAD

**Issue by awxiaoxian2020** [mybatis/generator#848]
I want to make a PR. But I'm confused by the project structure. I don't know where I can make the translation directory.

**Comment by jeffgbutler** [comment]
The docs are in this directory: https://github.com/mybatis/generator/tree/master/core/mybatis-generator-core/src/site

**Comment by awxiaoxian2020** [comment]
> The docs are in this directory: https://github.com/mybatis/generator/tree/master/core/mybatis-generator-core/src/site

I know about it. But my problem is where I should make the `zh` directory.

**Comment by jeffgbutler** [comment]
As a start, Make the zh directory there. Then duplicate the files and structure into the new zh directory. Then the work begins 😀

**Comment by awxiaoxian2020** [comment]
> As a start, Make the zh directory there. Then duplicate the files and structure into the new zh directory. Then the work begins 😀

Thanks! I will start it.
