### ISSUE TITLE
How to Modify the Generated namespace

### ISSUE THREAD

**Issue by cosoc** [mybatis/generator#851]
How to Modify the Generated namespace

**Comment by jeffgbutler** [comment]
With the `targetPackage` attribute on `<sqlMapGenerator>`, and `<javaClientGenerator>`.

**Comment by cosoc** [comment]
> 使用, 和的`targetPackage`属性。`<sqlMapGenerator>``<javaClientGenerator>`


```
        <javaClientGenerator type="XMLMAPPER"
                             targetPackage=""my.pack.database.postgresql.generator"
                             targetProject="./src/main/java">
            <property name="enableSubPackages" value="false"/>
        </javaClientGenerator>
```

I want the file storage path and namespace to be separated. I want to manually change the location after generation to prevent overwriting!


Whether attributes can be add: namespacePrefix

```
        <javaClientGenerator type="XMLMAPPER"
                             targetPackage=""my.pack.database.postgresql.generator"
                             namespacePrefix="my.pack.database.postgresql"
                             targetProject="./src/main/java">
            <property name="enableSubPackages" value="false"/>
        </javaClientGenerator>
```

**Comment by jeffgbutler** [comment]
You could add a path to the `targetProject` attribute - that would cause the files to be written in a different place.

You could also write a plugin to alter many things about the generated code.

Lastly, I will say that the XMLMAPPER is in maintenance mode only and we won't be making changes to it. We recommend everyone switch to the newer runtimes for MyBatis Dynamic SQL - they are far more capable than the old XML based mappers and they don't contain any XML at all.

**Comment by jeffgbutler** [comment]
No response
