### ISSUE TITLE
Eclipse plugin:'CRLF' will be replaced by 'LF' when xml file need merge

### ISSUE THREAD

**Issue by Xcorpio** [mybatis/generator#87]
hi,
'\r\n' will convert to '\n'  if the xml mapper file exists.

**Comment by Xcorpio** [comment]
![Uploading BaiduShurufa_2016-5-23_15-38-8.png…]()

**Comment by jeffgbutler** [comment]
Please make use the mailing list for questions.

**Comment by jeffgbutler** [comment]
See here:

http://mybatis-user.963551.n3.nabble.com/Eclipse-Generator-CRLF-will-be-replaced-by-LF-when-xml-file-need-merge-td4029459.html
