### ISSUE TITLE
maven plugin does not interpolate system properties when creating generator configuration

### ISSUE THREAD

**Issue by psacc** [mybatis/generator#88]
https://github.com/mybatis/generator/blob/master/core/mybatis-generator-maven-plugin/src/main/java/org/mybatis/generator/maven/MyBatisGeneratorMojo.java#L191

Looking at this code the generator configuration takes into account only the maven project model properties and does not take into account system properties in the interpolation as would be expected since the syntax is the same used for maven interpolation.

The issue is that there is no clear way to override properties values using the maven plugin with system properties (i.e. passing -D arguments to the maven build) that does not require to alter some of the maven configuration files (settings.xml or pom.xml).

**Comment by jeffgbutler** [comment]
Well this is a tricky one.  You are correct that the system properties are not included in the project properties.  I think the best way to fix this is to create a consolidated properties object that adds the system properties to the project properties.  This means that if a system property has the same name as a project property, the system property will override the project property.  I believe is what the normal intention would be.

**Comment by psacc** [comment]
I'm not that into maven to know if there's a proper maven api to achieve this, but I can manage to use the java api to access the system properties and propose a fix.

I need some guidance on how to properly write a test for this scenario so that the fix can be tested.

**Comment by jeffgbutler** [comment]
I think I want to make a change in the base generator code to deal with this.  There are actually three sets of properties:  the Maven (or Ant) properties, the properties loaded from the <properties> configuration element, and then the system properties.  There should be some kind of hierarchy for deciding which one wins if there is a name collision.  I think this priority makes sense:

1. System Properties
2. <properties> properties
3. Maven or Ant properties

Meaning that system properties will always win if there is a collision.

BTW - I've spent some time with the Maven plugin test harness and it's a lot of work for not much payback.  If I make the change in the base generator code it will be easier to write some tests.

**Comment by psacc** [comment]
Ok, great, the order you propose definitely makes sense to me.
Let me know if I can help in some way.
Thanks

**Comment by jeffgbutler** [comment]
I did some manual testing for this and I believe I have it correct.  Let me know if there is any issue for you in your environment.
