### ISSUE TITLE
A problem when using generated method "update..."

### ISSUE THREAD

**Issue by loganisGx** [mybatis/generator#885]
The generated XML file looks like :
```xml
<update id="updateByPrimaryKeySelective" parameterType="model">
   update table_name
   <set>
        <if test="model.attribute != null">
               ....
        </if>
        ...
   </set>
   where primary_key = #{}
</update>
```

But when all attributes in the input parameter 'model' are null, "set" command is not contained in the final SQL.
Just like : update table_name where primary_key = 1L

The version I use is 1.3.5,I have not used the latest version,so I don't know if this problem is still exists.

**Comment by jeffgbutler** [comment]
There's nothing we can do about this in the older XML based runtime. You will likely get an SQLException when MyBatis tries to execute the statement in this case. You will need to validate the input record before calling MyBatis.

In the newer MyBatis Dynamic SQL runtime we do check for this possibility and throw an exception before MyBatis tries to execute the statement.

**Comment by loganisGx** [comment]
Thanks for replying and your advices.
THANK YOU!
