### ISSUE TITLE
Is there an option to append the word "Record" to Kotlin data classes?

### ISSUE THREAD

**Issue by seki-shinnosuke** [mybatis/generator#911]
>Generated Kotlin data classes no longer have the word "Record" appended to their names. 

https://mybatis.org/generator/whatsNew.html
It's a breaking change.
Is there any way to change it other than the "domainObjectName" option?
If you use "domainObjectName", you have to set "mapperName" and "dynamicSqlSupportClassName" and "dynamicSqlTableObjectName" which is annoying.

**Comment by jeffgbutler** [comment]
This change is extensively documented on the page you noted, There were several good reasons for making this change as noted on that page. The most important reason is that there was a conflict between the rename option and practice of adding "Record". I do not plan to go back and add "Record" to the generated class.

Specifying a "domainObjectName" should work for renaming the data class, but it will not also rename the other generated items as you note. Those generated items never had "Record" in their names anyway, so I don't understand what issue you are raising about specifying the other name overrides like "mapperName" and "dynamicSqlSupportClassName". If you have found an issue related to just renaming the domain object, please code a failing test so we can understand the issue.

If you want to always have "Record" appended to the domain object name, you could accomplish that with a plugin. You could use one of the sample plugins as a model for writing such a plugin (https://github.com/mybatis/generator/blob/master/core/mybatis-generator-core/src/main/java/org/mybatis/generator/plugins/RenameExampleClassPlugin.java)

**Comment by seki-shinnosuke** [comment]
You can easily identify it as a Mybatis data class by appending the word "Record".
I found the following changes necessary and cumbersome to maintain the class names generated in the past.

```config.xml
ASIS
<table tableName="test_sample" />


TOBE
<table tableName="test_sample" domainObjectName="TestSampleRecord" mapperName="TestSampleMapper">
  <property name="dynamicSqlSupportClassName" value="TestSampleDynamicSqlSupport"/>
  <property name="dynamicSqlTableObjectName" value="TestSample"/>
</table>
```

>The most important reason is that there was a conflict between the rename option and practice of adding "Record". 

I can understand what you are saying.

**Comment by jeffgbutler** [comment]
I see what you're saying about the other attributes. You can use a plugin to change the name of the generated data class and all other attributes will remain as is. But more has changed for Kotlin than just this class name in version 1.4.1 of the generator. So even if you change the name with a plugin, there may still be other cleanup to do.

The Kotlin code generated by version 1.4.0 had quite a few limitations and didn't match the format we use for MyBatis Dynamic SQL everywhere else. I know there is some refactoring involved with changing to this new version, but I think it will be worth it in the end. It has certainly been worth the effort in my projects that use this code.

**Comment by seki-shinnosuke** [comment]
Sure.
We will proceed with refactoring based on version 1.4.1.

I appreciate your kind response during your busy time.
