### ISSUE TITLE
Support for Maven's toolchains

### ISSUE THREAD

**Issue by juanpablo-santos** [mybatis/generator#916]
It appears that the maven plugin relies on the `java` executable found on classpath, but it would be nice if it could also use the one provided by [Maven's toolchains](https://maven.apache.org/plugins/maven-toolchains-plugin/index.html). F.ex., check `AbstractRunMojo` changes at this [PR](https://github.com/spring-projects/spring-boot/pull/18732/files).

**Comment by jeffgbutler** [comment]
@juanpablo-santos I've spent a fair amount of time looking into this.

The first thing to know is that the generator runs in the same JVM as Maven itself - we do not fork a new JVM when running the generator. If we were to implement toolchains, we would need to first make the generator run in a fork - which is difficult, and then use the toolchain - which would be relatively simple.

This reminds me of Kent Beck's famous quote:

> for each desired change, make the change easy (warning: this may be hard), then make the easy change

I'm wondering if you have a specific need for toolchain support, or if this is just a "nice to have".

**Comment by juanpablo-santos** [comment]
Hi @jeffgbutler , thanks for your time looking into this :-)

our ci builds use extensively toolchains, so we can mix&match several JDKs inside the same mvn run. We were bound to be using some old plugin that was needing jdk7 (don't remember which know, possibly something jaxws related, but no really sure right now), which prevented us from using the mybatis generator on the same run.

In any case, we've moved away from that plugin so our builds are a bit simpler today and we're not facing the issue anymore; we would hit it again if f.ex. another plugin would mandate another JDK like jdk-11 or so, but that seems unlikely nowadays. Please feel free to close the issue if you deem it appropiate

**Comment by hazendaz** [comment]
closing ticket as user worked around issue and noted it can now be closed.
