### ISSUE TITLE
Wrong import statement being generated?

### ISSUE THREAD

**Issue by cbottomline** [mybatis/generator#917]
The generated files are using `import javax.annotation.Generated`.  Should it be `import javax.annotation.processing.Generated`?  

Environment:
Java: 11
MyBatis: 3.5.11
MyBatis Generator: 1.4.1

**Comment by jeffgbutler** [comment]
That's the correct annotation, it was removed from the core distribution in Java 11. You can add this dependency to get it back:

```xml
    <dependency>
      <groupId>javax.annotation</groupId>
      <artifactId>javax.annotation-api</artifactId>
      <version>1.3.2</version>
    </dependency>
```

In the next version of the generator, the default will switch to use the "jakarta" namespace instead of "javax".
