### ISSUE TITLE
Deprecated SqlBuilder Code Generated

### ISSUE THREAD

**Issue by jakez15** [mybatis/generator#92]
The SqlBuilder class is deprecated in mybatis-3.4.0.  Any plans to update the generator to work with v3.4.0?

**Comment by jeffgbutler** [comment]
The generator supports the new SQL class, and has for quite some time.  But it is in version 1.3.3-SNAPSHOT.  I'm working on getting that build released, but if you need it in the short term you can pull it out of the snapshot repository.  See this page for instructions on how to do that:

https://github.com/mybatis/mybatis-3/wiki/Maven#snapshot

**Comment by jakez15** [comment]
Excellent, thanks!

**Comment by jakez15** [comment]
Is there a date you are targeting for the release or is it done when it's done?

**Comment by jeffgbutler** [comment]
Every time I say a date, I regret it.  So it's done when it's done.  I do have a bit more time to work on this now than I have had in the past, so hopefully soon.
