### ISSUE TITLE
Support spring-boot 3.0

### ISSUE THREAD

**Issue by ewinchen** [mybatis/generator#933]
Generated Objects are generated with `import javax.annotation.Generated;`, however, spring-boot 3.0 migrated to jarkata instead.
Counld anyone kindly help to fix this, thanks.

**Comment by jeffgbutler** [comment]
This is already fixed in #836, but not released yet.

**Comment by jabrena** [comment]
Any estimation to release a new version?

**Comment by jeffgbutler** [comment]
Released today.
