### ISSUE TITLE
Unable to generate code in the 'maven update project' lifecycle. "Maven generate sources" must be run manually

### ISSUE THREAD

**Issue by mmm8955405** [mybatis/generator#934]
```xml
<plugin>
  <groupId>org.mybatis.generator</groupId>
  <artifactId>mybatis-generator-maven-plugin</artifactId>
  <version>1.4.1</version>
  <executions>
    <execution>
      <id>generate myBatis</id>
      <phase>generate-sources</phase>
      <goals>
        <goal>generate</goal>
      </goals>
    </execution>
  </executions>
  <dependencies>
    <dependency>
      <groupId>org.mariadb.jdbc</groupId>
      <artifactId>mariadb-java-client</artifactId>
      <version>${mariadb.version}</version>
    </dependency>
  </dependencies>
</plugin>
```

**In Jooq's plug-in, the generate sources life cycle can directly generate code through the maven update project**

```xml
<plugin>
  <groupId>org.jooq</groupId>
  <artifactId>jooq-codegen-maven</artifactId>
  <executions>
    <execution>
      <id>generate-jooq</id>
      <phase>generate-sources</phase>
      <goals>
        <goal>generate</goal>
      </goals>
    </execution>
  </executions>
  <dependencies>
    <dependency>
      <groupId>org.mariadb.jdbc</groupId>
      <artifactId>mariadb-java-client</artifactId>
      <version>${mariadb.version}</version>
    </dependency>
  </dependencies>
  <configuration>
    <configurationFile>/src/main/resources/generate/jooq/JooqConfig.xml</configurationFile>
  </configuration>
</plugin>
```

**Comment by jeffgbutler** [comment]
Maven does not have an "update project" lifecycle. Are you using some IDE? Which one?

I don't know much about jOOQ - perhaps they have some plugin that hooks into an IDE lifecycle phase?

**Comment by mmm8955405** [comment]
I use eclipse and Spring Tool Suite 4.
At present, I'm not sure whether Jooq's plug-in has been executed in the "compile" life cycle, but it uses the same execution phase as mybatis plug-in.(generate-sources)
as follows：
`<executions>
    <execution>
      <id>generate-jooq</id>
      <phase>generate-sources</phase>
      <goals>
        <goal>generate</goal>
      </goals>
    </execution>
  </executions>`
But it does generate code. During maven update.
![7f5ccc13624e50bc3c22ea53723c981](https://user-images.githubusercontent.com/5687907/209047540-637f8b44-6046-4434-af16-c455d4a0a770.jpg)

**Comment by mmm8955405** [comment]
> I see how it works - they've got an eclipse lifecycle mapping file embedded in their plugin: https://github.com/jOOQ/jOOQ/blob/main/jOOQ-codegen-maven/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml
> 
> You can configure this yourself in Eclipse if you want to for now. I'll add something similar into our plugin.

You are so great!
