### ISSUE TITLE
Cannot Disabe XML Overwriting

### ISSUE THREAD

**Issue by l00pss** [mybatis/generator#935]
Hi
When I overwrite false in the Generator plugin, the interfaces do not overwrite, but the XML is overwritten and the attachments I have made on the XML are deleted. How can I make XML not overwrite? Thanks

**Comment by jeffgbutler** [comment]
You can use the `UnmergeableXmlMappersPlugin` for this.

http://mybatis.org/generator/reference/plugins.html#org-mybatis-generator-plugins-unmergeablexmlmappersplugin
