### ISSUE TITLE
Feature request: plugin support for kotlin override modifier generation

### ISSUE THREAD

**Issue by Turmiht** [mybatis/generator#996]
Seemly currently `org.mybatis.generator.api.dom.kotlin.KotlinFunction` do not contains a way to add `override` modifier(It's not in `KotlinModifier` variants.
My workaround for that is using withAnnotation("override"), which is fragile when other annotations added after `override`.
Maybe there should be a dedicated method in `KotlinFunction.Builder` for doing it.

**Comment by jeffgbutler** [comment]
Good catch! I think it will be easiest to add a value to `KotlinModifier` - nothing else should need to change.
